//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.Filters {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aaru.Filters.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppleDouble_Name {
            get {
                return ResourceManager.GetString("AppleDouble_Name", resourceCulture);
            }
        }
        
        internal static string AppleSingle_Name {
            get {
                return ResourceManager.GetString("AppleSingle_Name", resourceCulture);
            }
        }
        
        internal static string BZip2_Name {
            get {
                return ResourceManager.GetString("BZip2_Name", resourceCulture);
            }
        }
        
        internal static string Cannot_seek_before_stream_start {
            get {
                return ResourceManager.GetString("Cannot_seek_before_stream_start", resourceCulture);
            }
        }
        
        internal static string Cannot_seek_after_stream_end {
            get {
                return ResourceManager.GetString("Cannot_seek_after_stream_end", resourceCulture);
            }
        }
        
        internal static string GZip_Name {
            get {
                return ResourceManager.GetString("GZip_Name", resourceCulture);
            }
        }
        
        internal static string LZip_Name {
            get {
                return ResourceManager.GetString("LZip_Name", resourceCulture);
            }
        }
        
        internal static string MacBinary_Name {
            get {
                return ResourceManager.GetString("MacBinary_Name", resourceCulture);
            }
        }
        
        internal static string Start_cant_be_a_negative_number {
            get {
                return ResourceManager.GetString("Start_cant_be_a_negative_number", resourceCulture);
            }
        }
        
        internal static string End_cant_be_a_negative_number {
            get {
                return ResourceManager.GetString("End_cant_be_a_negative_number", resourceCulture);
            }
        }
        
        internal static string End_is_after_stream_end {
            get {
                return ResourceManager.GetString("End_is_after_stream_end", resourceCulture);
            }
        }
        
        internal static string Cannot_set_position_past_stream_end {
            get {
                return ResourceManager.GetString("Cannot_set_position_past_stream_end", resourceCulture);
            }
        }
        
        internal static string Cannot_read_past_stream_end {
            get {
                return ResourceManager.GetString("Cannot_read_past_stream_end", resourceCulture);
            }
        }
        
        internal static string Cannot_write_past_stream_end {
            get {
                return ResourceManager.GetString("Cannot_write_past_stream_end", resourceCulture);
            }
        }
        
        internal static string Cannot_seek_past_stream_end {
            get {
                return ResourceManager.GetString("Cannot_seek_past_stream_end", resourceCulture);
            }
        }
        
        internal static string Growing_OffsetStream_is_not_supported {
            get {
                return ResourceManager.GetString("Growing_OffsetStream_is_not_supported", resourceCulture);
            }
        }
        
        internal static string PcExchange_Name {
            get {
                return ResourceManager.GetString("PcExchange_Name", resourceCulture);
            }
        }
        
        internal static string Non_seekable_streams_are_not_supported {
            get {
                return ResourceManager.GetString("Non_seekable_streams_are_not_supported", resourceCulture);
            }
        }
        
        internal static string Non_readable_streams_are_not_supported {
            get {
                return ResourceManager.GetString("Non_readable_streams_are_not_supported", resourceCulture);
            }
        }
        
        internal static string Asynchronous_IO_is_not_supported {
            get {
                return ResourceManager.GetString("Asynchronous_IO_is_not_supported", resourceCulture);
            }
        }
        
        internal static string This_stream_is_read_only {
            get {
                return ResourceManager.GetString("This_stream_is_read_only", resourceCulture);
            }
        }
        
        internal static string XZ_Name {
            get {
                return ResourceManager.GetString("XZ_Name", resourceCulture);
            }
        }
        
        internal static string ZZZNoFilter_Name {
            get {
                return ResourceManager.GetString("ZZZNoFilter_Name", resourceCulture);
            }
        }
    }
}
