//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.Archives {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aaru.Archives.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID: 0x{0:X8}.
        /// </summary>
        internal static string Application_ID_0 {
            get {
                return ResourceManager.GetString("Application_ID_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive options: {0}.
        /// </summary>
        internal static string Archive_options_0 {
            get {
                return ResourceManager.GetString("Archive_options_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capabilities:.
        /// </summary>
        internal static string Capabilities {
            get {
                return ResourceManager.GetString("Capabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component name for language with code {0}: {1}.
        /// </summary>
        internal static string Component_name_for_language_with_code_0_1 {
            get {
                return ResourceManager.GetString("Component_name_for_language_with_code_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component version: {0}.{1}.
        /// </summary>
        internal static string Component_version_0_1 {
            get {
                return ResourceManager.GetString("Component_version_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC16 of header: 0x{0:X4}.
        /// </summary>
        internal static string CRC16_of_header_0 {
            get {
                return ResourceManager.GetString("CRC16_of_header_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive contains {0} files (pointer: {1}).
        /// </summary>
        internal static string File_contains_0_files_pointer_1 {
            get {
                return ResourceManager.GetString("File_contains_0_files_pointer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive contains {0} languages:.
        /// </summary>
        internal static string File_contains_0_languages {
            get {
                return ResourceManager.GetString("File_contains_0_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive contains {0} requisites.
        /// </summary>
        internal static string File_contains_0_requisites {
            get {
                return ResourceManager.GetString("File_contains_0_requisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files for `{0}` language:.
        /// </summary>
        internal static string Files_for_0_language {
            get {
                return ResourceManager.GetString("Files_for_0_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files for all languages:.
        /// </summary>
        internal static string Files_for_all_languages {
            get {
                return ResourceManager.GetString("Files_for_all_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required {0} version {1}.{2}.
        /// </summary>
        internal static string Required_UID_0_version_1_2 {
            get {
                return ResourceManager.GetString("Required_UID_0_version_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required variant: {0}.
        /// </summary>
        internal static string Required_variant_0 {
            get {
                return ResourceManager.GetString("Required_variant_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisite #{0}:.
        /// </summary>
        internal static string Requisite_0 {
            get {
                return ResourceManager.GetString("Requisite_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisite for language {0}: {1}.
        /// </summary>
        internal static string Requisite_for_language_0_1 {
            get {
                return ResourceManager.GetString("Requisite_for_language_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIS contains an application.
        /// </summary>
        internal static string SIS_contains_an_application {
            get {
                return ResourceManager.GetString("SIS_contains_an_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID 0x{0:X8}.
        /// </summary>
        internal static string SIS_Platform_UID_0 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 3230.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_3230 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_3230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 3250.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_3250 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_3250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 3650.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_3650 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_3650", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 6260.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_6260 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 6600.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_6600 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 6620.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_6620 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6620", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 6630.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_6630 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6630", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 6670.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_6670 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6670", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 6680.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_6680 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6680", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 6681.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_6681 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6681", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 6682.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_6682 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6682", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 7610.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_7610 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_7610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 7650.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_7650 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_7650", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 7710 (Series 90).
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_7710_Series_90 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_7710_Series_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 9300.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_9300 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_9300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia 9500.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_9500 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_9500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia Belle.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_Belle {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_Belle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia E60.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_E60 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_E60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia E61.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_E61 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_E61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia E70.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_E70 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_E70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia N-Gage.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_N_Gage {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N_Gage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia N70.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_N70 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia N71.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_N71 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia N73.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_N73 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia N80.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_N80 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia N90.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_N90 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia N91.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_N91 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia N92.
        /// </summary>
        internal static string SIS_Platform_UID_Nokia_N92 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 1st Edition.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_1st_Edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_1st_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 1st Edition, Feature Pack 1.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_1st_Edition_Feature_Pack_1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_1st_Edition_Feature_Pack_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 2nd Edition.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_2nd_Edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_2nd_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 2nd Edition, Feature Pack 1.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 2nd Edition, Feature Pack 2.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_2 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 2nd Edition, Feature Pack 3.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_3 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 3rd Edition.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_3rd_Edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_3rd_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 3rd Edition, Feature Pack 1.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_3rd_Edition_Feature_Pack_1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_3rd_Edition_Feature_Pack_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 3rd Edition, Feature Pack 2.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_3rd_Edition_Feature_Pack_2 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_3rd_Edition_Feature_Pack_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 5th Edition.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_5th_Edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_5th_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 v1.0.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_v1_0 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_v1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 60 v1.1.
        /// </summary>
        internal static string SIS_Platform_UID_Series_60_v1_1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_v1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series 80 2nd Edition.
        /// </summary>
        internal static string SIS_Platform_UID_Series_80_2nd_edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_80_2nd_edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siemens SX1.
        /// </summary>
        internal static string SIS_Platform_UID_Siemens_SX1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Siemens_SX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonyEricsson P80x.
        /// </summary>
        internal static string SIS_Platform_UID_SonyEricsson_P80x {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_SonyEricsson_P80x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonyEricsson P90x.
        /// </summary>
        internal static string SIS_Platform_UID_SonyEricsson_P90x {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_SonyEricsson_P90x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbian^3.
        /// </summary>
        internal static string SIS_Platform_UID_Symbian_3 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Symbian_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIQ v2.0.
        /// </summary>
        internal static string SIS_Platform_UID_UIQ_20 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_UIQ_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIQ v2.1.
        /// </summary>
        internal static string SIS_Platform_UID_UIQ_21 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_UIQ_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIQ v3.0.
        /// </summary>
        internal static string SIS_Platform_UID_UIQ_30 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_UIQ_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymbianOS 3 or later.
        /// </summary>
        internal static string Symbian_3_or_later {
            get {
                return ResourceManager.GetString("Symbian_3_or_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymbianOS 6 or later.
        /// </summary>
        internal static string Symbian_6_or_later {
            get {
                return ResourceManager.GetString("Symbian_6_or_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymbianOS 9.1 or later.
        /// </summary>
        internal static string Symbian_9_1_or_later {
            get {
                return ResourceManager.GetString("Symbian_9_1_or_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbian Installation File.
        /// </summary>
        internal static string Symbian_Installation_File {
            get {
                return ResourceManager.GetString("Symbian_Installation_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbian Installation File.
        /// </summary>
        internal static string Symbian_Name {
            get {
                return ResourceManager.GetString("Symbian_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIDs checksum: 0x{0:X8}.
        /// </summary>
        internal static string UIDs_checksum_0 {
            get {
                return ResourceManager.GetString("UIDs_checksum_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown EPOC magic 0x{0:X8}.
        /// </summary>
        internal static string Unknown_EPOC_magic_0 {
            get {
                return ResourceManager.GetString("Unknown_EPOC_magic_0", resourceCulture);
            }
        }
    }
}
