//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.Tests {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aaru.Tests.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Size_0 {
            get {
                return ResourceManager.GetString("Size_0", resourceCulture);
            }
        }
        
        internal static string Decoded_0 {
            get {
                return ResourceManager.GetString("Decoded_0", resourceCulture);
            }
        }
        
        internal static string Manufacturer_0 {
            get {
                return ResourceManager.GetString("Manufacturer_0", resourceCulture);
            }
        }
        
        internal static string Product_name_0 {
            get {
                return ResourceManager.GetString("Product_name_0", resourceCulture);
            }
        }
        
        internal static string Product_revision_0 {
            get {
                return ResourceManager.GetString("Product_revision_0", resourceCulture);
            }
        }
        
        internal static string Serial_number_0 {
            get {
                return ResourceManager.GetString("Serial_number_0", resourceCulture);
            }
        }
        
        internal static string Manufacturing_date_0 {
            get {
                return ResourceManager.GetString("Manufacturing_date_0", resourceCulture);
            }
        }
        
        internal static string CRC_0 {
            get {
                return ResourceManager.GetString("CRC_0", resourceCulture);
            }
        }
        
        internal static string Structure_version_0 {
            get {
                return ResourceManager.GetString("Structure_version_0", resourceCulture);
            }
        }
        
        internal static string Specification_version_0 {
            get {
                return ResourceManager.GetString("Specification_version_0", resourceCulture);
            }
        }
        
        internal static string TAAC_0 {
            get {
                return ResourceManager.GetString("TAAC_0", resourceCulture);
            }
        }
        
        internal static string NSAC_0 {
            get {
                return ResourceManager.GetString("NSAC_0", resourceCulture);
            }
        }
        
        internal static string Transfer_speed_0 {
            get {
                return ResourceManager.GetString("Transfer_speed_0", resourceCulture);
            }
        }
        
        internal static string Classes_0 {
            get {
                return ResourceManager.GetString("Classes_0", resourceCulture);
            }
        }
        
        internal static string Read_block_length_0 {
            get {
                return ResourceManager.GetString("Read_block_length_0", resourceCulture);
            }
        }
        
        internal static string Reads_partial_blocks_0 {
            get {
                return ResourceManager.GetString("Reads_partial_blocks_0", resourceCulture);
            }
        }
        
        internal static string Writes_misaligned_blocks_0 {
            get {
                return ResourceManager.GetString("Writes_misaligned_blocks_0", resourceCulture);
            }
        }
        
        internal static string Reads_misaligned_blocks_0 {
            get {
                return ResourceManager.GetString("Reads_misaligned_blocks_0", resourceCulture);
            }
        }
        
        internal static string DSR_implemented_0 {
            get {
                return ResourceManager.GetString("DSR_implemented_0", resourceCulture);
            }
        }
        
        internal static string Card_size_0 {
            get {
                return ResourceManager.GetString("Card_size_0", resourceCulture);
            }
        }
        
        internal static string Reading_current_at_minimum_Vdd_0 {
            get {
                return ResourceManager.GetString("Reading_current_at_minimum_Vdd_0", resourceCulture);
            }
        }
        
        internal static string Reading_current_at_maximum_Vdd_0 {
            get {
                return ResourceManager.GetString("Reading_current_at_maximum_Vdd_0", resourceCulture);
            }
        }
        
        internal static string Writing_current_at_minimum_Vdd_0 {
            get {
                return ResourceManager.GetString("Writing_current_at_minimum_Vdd_0", resourceCulture);
            }
        }
        
        internal static string Writing_current_at_maximum_Vdd_0 {
            get {
                return ResourceManager.GetString("Writing_current_at_maximum_Vdd_0", resourceCulture);
            }
        }
        
        internal static string Card_size_multiplier_0 {
            get {
                return ResourceManager.GetString("Card_size_multiplier_0", resourceCulture);
            }
        }
        
        internal static string Erase_sector_size_0 {
            get {
                return ResourceManager.GetString("Erase_sector_size_0", resourceCulture);
            }
        }
        
        internal static string Erase_group_size_0 {
            get {
                return ResourceManager.GetString("Erase_group_size_0", resourceCulture);
            }
        }
        
        internal static string Write_protect_group_size_0 {
            get {
                return ResourceManager.GetString("Write_protect_group_size_0", resourceCulture);
            }
        }
        
        internal static string Write_protect_group_enable_0 {
            get {
                return ResourceManager.GetString("Write_protect_group_enable_0", resourceCulture);
            }
        }
        
        internal static string Default_ECC_0 {
            get {
                return ResourceManager.GetString("Default_ECC_0", resourceCulture);
            }
        }
        
        internal static string Read_to_write_factor_0 {
            get {
                return ResourceManager.GetString("Read_to_write_factor_0", resourceCulture);
            }
        }
        
        internal static string write_block_length_0 {
            get {
                return ResourceManager.GetString("write_block_length_0", resourceCulture);
            }
        }
        
        internal static string Writes_partial_blocks_0 {
            get {
                return ResourceManager.GetString("Writes_partial_blocks_0", resourceCulture);
            }
        }
        
        internal static string File_format_group_0 {
            get {
                return ResourceManager.GetString("File_format_group_0", resourceCulture);
            }
        }
        
        internal static string Copy_0 {
            get {
                return ResourceManager.GetString("Copy_0", resourceCulture);
            }
        }
        
        internal static string Permanent_write_protect_0 {
            get {
                return ResourceManager.GetString("Permanent_write_protect_0", resourceCulture);
            }
        }
        
        internal static string Temporary_write_protect_0 {
            get {
                return ResourceManager.GetString("Temporary_write_protect_0", resourceCulture);
            }
        }
        
        internal static string File_format_0 {
            get {
                return ResourceManager.GetString("File_format_0", resourceCulture);
            }
        }
        
        internal static string ECC_0 {
            get {
                return ResourceManager.GetString("ECC_0", resourceCulture);
            }
        }
        
        internal static string Not_decoded_0 {
            get {
                return ResourceManager.GetString("Not_decoded_0", resourceCulture);
            }
        }
        
        internal static string Version_0 {
            get {
                return ResourceManager.GetString("Version_0", resourceCulture);
            }
        }
        
        internal static string Erase_block_enable_0 {
            get {
                return ResourceManager.GetString("Erase_block_enable_0", resourceCulture);
            }
        }
        
        internal static string Data_stat_after_erase_0 {
            get {
                return ResourceManager.GetString("Data_stat_after_erase_0", resourceCulture);
            }
        }
        
        internal static string Security_0 {
            get {
                return ResourceManager.GetString("Security_0", resourceCulture);
            }
        }
        
        internal static string Bus_widths_0 {
            get {
                return ResourceManager.GetString("Bus_widths_0", resourceCulture);
            }
        }
        
        internal static string Spec_3_0 {
            get {
                return ResourceManager.GetString("Spec_3_0", resourceCulture);
            }
        }
        
        internal static string Extended_security_0 {
            get {
                return ResourceManager.GetString("Extended_security_0", resourceCulture);
            }
        }
        
        internal static string Spec_4_0 {
            get {
                return ResourceManager.GetString("Spec_4_0", resourceCulture);
            }
        }
        
        internal static string Spec_X_0 {
            get {
                return ResourceManager.GetString("Spec_X_0", resourceCulture);
            }
        }
        
        internal static string Command_support_0 {
            get {
                return ResourceManager.GetString("Command_support_0", resourceCulture);
            }
        }
        
        internal static string Manufacturer_reserved_0 {
            get {
                return ResourceManager.GetString("Manufacturer_reserved_0", resourceCulture);
            }
        }
        
        internal static string Open_0 {
            get {
                return ResourceManager.GetString("Open_0", resourceCulture);
            }
        }
        
        internal static string Sectors_0 {
            get {
                return ResourceManager.GetString("Sectors_0", resourceCulture);
            }
        }
        
        internal static string Sector_size_0 {
            get {
                return ResourceManager.GetString("Sector_size_0", resourceCulture);
            }
        }
        
        internal static string Media_type_0 {
            get {
                return ResourceManager.GetString("Media_type_0", resourceCulture);
            }
        }
        
        internal static string _0_not_found {
            get {
                return ResourceManager.GetString("_0_not_found", resourceCulture);
            }
        }
        
        internal static string Filter_0 {
            get {
                return ResourceManager.GetString("Filter_0", resourceCulture);
            }
        }
        
        internal static string Image_format_0 {
            get {
                return ResourceManager.GetString("Image_format_0", resourceCulture);
            }
        }
        
        internal static string Cannot_open_image_for_0 {
            get {
                return ResourceManager.GetString("Cannot_open_image_for_0", resourceCulture);
            }
        }
        
        internal static string No_partitions_found_for_0 {
            get {
                return ResourceManager.GetString("No_partitions_found_for_0", resourceCulture);
            }
        }
        
        internal static string Filesystem_not_identified_for_0 {
            get {
                return ResourceManager.GetString("Filesystem_not_identified_for_0", resourceCulture);
            }
        }
        
        internal static string No_filesystems_found_for_0 {
            get {
                return ResourceManager.GetString("No_filesystems_found_for_0", resourceCulture);
            }
        }
        
        internal static string Not_identified_for_0 {
            get {
                return ResourceManager.GetString("Not_identified_for_0", resourceCulture);
            }
        }
        
        internal static string Could_not_instantiate_filesystem_for_0 {
            get {
                return ResourceManager.GetString("Could_not_instantiate_filesystem_for_0", resourceCulture);
            }
        }
        
        internal static string Application_ID_0 {
            get {
                return ResourceManager.GetString("Application_ID_0", resourceCulture);
            }
        }
        
        internal static string Bootable_0 {
            get {
                return ResourceManager.GetString("Bootable_0", resourceCulture);
            }
        }
        
        internal static string Clusters_0 {
            get {
                return ResourceManager.GetString("Clusters_0", resourceCulture);
            }
        }
        
        internal static string Cluster_size_0 {
            get {
                return ResourceManager.GetString("Cluster_size_0", resourceCulture);
            }
        }
        
        internal static string System_ID_0 {
            get {
                return ResourceManager.GetString("System_ID_0", resourceCulture);
            }
        }
        
        internal static string Filesystem_type_0 {
            get {
                return ResourceManager.GetString("Filesystem_type_0", resourceCulture);
            }
        }
        
        internal static string Volume_name_0 {
            get {
                return ResourceManager.GetString("Volume_name_0", resourceCulture);
            }
        }
        
        internal static string Volume_serial_0 {
            get {
                return ResourceManager.GetString("Volume_serial_0", resourceCulture);
            }
        }
        
        internal static string Unmountable_0 {
            get {
                return ResourceManager.GetString("Unmountable_0", resourceCulture);
            }
        }
        
        internal static string Unexpected_error_0_when_reading_directory_1_of_2 {
            get {
                return ResourceManager.GetString("Unexpected_error_0_when_reading_directory_1_of_2", resourceCulture);
            }
        }
        
        internal static string Unexpected_error_0_retrieving_stats_for_1_in_2 {
            get {
                return ResourceManager.GetString("Unexpected_error_0_retrieving_stats_for_1_in_2", resourceCulture);
            }
        }
        
        internal static string Wrong_info_for_0_in_1 {
            get {
                return ResourceManager.GetString("Wrong_info_for_0_in_1", resourceCulture);
            }
        }
        
        internal static string Got_wrong_data_for_directory_0_in_1 {
            get {
                return ResourceManager.GetString("Got_wrong_data_for_directory_0_in_1", resourceCulture);
            }
        }
        
        internal static string Contents_for_0_in_1_must_be_defined_in_unit_test_declaration {
            get {
                return ResourceManager.GetString("Contents_for_0_in_1_must_be_defined_in_unit_test_declaration", resourceCulture);
            }
        }
        
        internal static string Got_wrong_data_for_symbolic_link_0_in_1 {
            get {
                return ResourceManager.GetString("Got_wrong_data_for_symbolic_link_0_in_1", resourceCulture);
            }
        }
        
        internal static string Invalid_target_for_symbolic_link_0_in_1 {
            get {
                return ResourceManager.GetString("Invalid_target_for_symbolic_link_0_in_1", resourceCulture);
            }
        }
        
        internal static string Defined_extended_attributes_for_0_in_1_are_not_supported_by_filesystem {
            get {
                return ResourceManager.GetString("Defined_extended_attributes_for_0_in_1_are_not_supported_by_filesystem", resourceCulture);
            }
        }
        
        internal static string Unexpected_error_0_when_listing_extended_attributes_for_1_in_2 {
            get {
                return ResourceManager.GetString("Unexpected_error_0_when_listing_extended_attributes_for_1_in_2", resourceCulture);
            }
        }
        
        internal static string Extended_attributes_for_0_in_1_must_be_defined_in_unit_test_declaration {
            get {
                return ResourceManager.GetString("Extended_attributes_for_0_in_1_must_be_defined_in_unit_test_declaration", resourceCulture);
            }
        }
        
        internal static string Could_not_find_the_children_of_0_in_1_2 {
            get {
                return ResourceManager.GetString("Could_not_find_the_children_of_0_in_1_2", resourceCulture);
            }
        }
        
        internal static string Found_the_following_unexpected_children_of_0_in_1_2 {
            get {
                return ResourceManager.GetString("Found_the_following_unexpected_children_of_0_in_1_2", resourceCulture);
            }
        }
        
        internal static string Unexpected_error_0_when_reading_1_in_2 {
            get {
                return ResourceManager.GetString("Unexpected_error_0_when_reading_1_in_2", resourceCulture);
            }
        }
        
        internal static string Unexpected_error_0_retrieving_extended_attributes_for_1_in_2 {
            get {
                return ResourceManager.GetString("Unexpected_error_0_retrieving_extended_attributes_for_1_in_2", resourceCulture);
            }
        }
        
        internal static string Got_MD5_0_for_1_of_2_in_3_but_expected_4 {
            get {
                return ResourceManager.GetString("Got_MD5_0_for_1_of_2_in_3_but_expected_4", resourceCulture);
            }
        }
        
        internal static string Could_not_find_the_following_extended_attributes_of_0_in_1_2 {
            get {
                return ResourceManager.GetString("Could_not_find_the_following_extended_attributes_of_0_in_1_2", resourceCulture);
            }
        }
        
        internal static string Found_the_following_unexpected_extended_attributes_of_0_in_1_2 {
            get {
                return ResourceManager.GetString("Found_the_following_unexpected_extended_attributes_of_0_in_1_2", resourceCulture);
            }
        }
        
        internal static string Hash_0 {
            get {
                return ResourceManager.GetString("Hash_0", resourceCulture);
            }
        }
        
        internal static string Expected_0_partitions_in_1_but_found_2 {
            get {
                return ResourceManager.GetString("Expected_0_partitions_in_1_but_found_2", resourceCulture);
            }
        }
        
        internal static string Expected_partition_0_to_start_at_sector_1_but_found_it_starts_at_2_in_3 {
            get {
                return ResourceManager.GetString("Expected_partition_0_to_start_at_sector_1_but_found_it_starts_at_2_in_3", resourceCulture);
            }
        }
        
        internal static string Expected_partition_0_to_have_1_sectors_but_found_it_has_2_sectors_in_3 {
            get {
                return ResourceManager.GetString("Expected_partition_0_to_have_1_sectors_but_found_it_has_2_sectors_in_3", resourceCulture);
            }
        }
        
        internal static string Could_not_instantiate_filesystem_plugin {
            get {
                return ResourceManager.GetString("Could_not_instantiate_filesystem_plugin", resourceCulture);
            }
        }
        
        internal static string Could_not_instantiate_filesystem_0 {
            get {
                return ResourceManager.GetString("Could_not_instantiate_filesystem_0", resourceCulture);
            }
        }
        
        internal static string Could_not_mount_0_in_partition_1 {
            get {
                return ResourceManager.GetString("Could_not_mount_0_in_partition_1", resourceCulture);
            }
        }
        
        internal static string Tracks_0 {
            get {
                return ResourceManager.GetString("Tracks_0", resourceCulture);
            }
        }
        
        internal static string Track_session_0 {
            get {
                return ResourceManager.GetString("Track_session_0", resourceCulture);
            }
        }
        
        internal static string Track_start_0 {
            get {
                return ResourceManager.GetString("Track_start_0", resourceCulture);
            }
        }
        
        internal static string Track_end_0 {
            get {
                return ResourceManager.GetString("Track_end_0", resourceCulture);
            }
        }
        
        internal static string Track_pregap_0 {
            get {
                return ResourceManager.GetString("Track_pregap_0", resourceCulture);
            }
        }
        
        internal static string Track_flags_0 {
            get {
                return ResourceManager.GetString("Track_flags_0", resourceCulture);
            }
        }
        
        internal static string Last_sector_for_tracks_is_0_but_it_is_1_for_image {
            get {
                return ResourceManager.GetString("Last_sector_for_tracks_is_0_but_it_is_1_for_image", resourceCulture);
            }
        }
        
        internal static string Expected_0_filesystems_in_1_but_found_2 {
            get {
                return ResourceManager.GetString("Expected_0_filesystems_in_1_but_found_2", resourceCulture);
            }
        }
        
        internal static string Could_not_instantiate_filesystem_for_0_track_1_filesystem_2 {
            get {
                return ResourceManager.GetString("Could_not_instantiate_filesystem_for_0_track_1_filesystem_2", resourceCulture);
            }
        }
        
        internal static string Subchannel_hash_0 {
            get {
                return ResourceManager.GetString("Subchannel_hash_0", resourceCulture);
            }
        }
        
        internal static string Is_tape_0 {
            get {
                return ResourceManager.GetString("Is_tape_0", resourceCulture);
            }
        }
        
        internal static string Tape_files_0 {
            get {
                return ResourceManager.GetString("Tape_files_0", resourceCulture);
            }
        }
        
        internal static string Tape_partitions_0 {
            get {
                return ResourceManager.GetString("Tape_partitions_0", resourceCulture);
            }
        }
        
        internal static string Cannot_open_specified_file {
            get {
                return ResourceManager.GetString("Cannot_open_specified_file", resourceCulture);
            }
        }
        
        internal static string Image_format_not_identified_not_proceeding_with_analysis {
            get {
                return ResourceManager.GetString("Image_format_not_identified_not_proceeding_with_analysis", resourceCulture);
            }
        }
        
        internal static string Unable_to_open_image_format {
            get {
                return ResourceManager.GetString("Unable_to_open_image_format", resourceCulture);
            }
        }
        
        internal static string No_partitions_found {
            get {
                return ResourceManager.GetString("No_partitions_found", resourceCulture);
            }
        }
        
        internal static string Excepted_0_partitions_but_found_1 {
            get {
                return ResourceManager.GetString("Excepted_0_partitions_but_found_1", resourceCulture);
            }
        }
        
        internal static string Expected_no_filesystems_identified_in_partition_0_but_found_1 {
            get {
                return ResourceManager.GetString("Expected_no_filesystems_identified_in_partition_0_but_found_1", resourceCulture);
            }
        }
        
        internal static string Expected_0_filesystems_identified_in_partition_1_but_found_2 {
            get {
                return ResourceManager.GetString("Expected_0_filesystems_identified_in_partition_1_but_found_2", resourceCulture);
            }
        }
        
        internal static string Excepted_volume_name_0_for_filesystem_1_in_partition_2_but_found_3 {
            get {
                return ResourceManager.GetString("Excepted_volume_name_0_for_filesystem_1_in_partition_2_but_found_3", resourceCulture);
            }
        }
        
        internal static string Expected_directories_not_found {
            get {
                return ResourceManager.GetString("Expected_directories_not_found", resourceCulture);
            }
        }
        
        internal static string Expected_files_not_found {
            get {
                return ResourceManager.GetString("Expected_files_not_found", resourceCulture);
            }
        }
        
        internal static string Error_0_reading_root_directory_0 {
            get {
                return ResourceManager.GetString("Error_0_reading_root_directory_0", resourceCulture);
            }
        }
        
        internal static string Error_getting_stat_for_entry_0 {
            get {
                return ResourceManager.GetString("Error_getting_stat_for_entry_0", resourceCulture);
            }
        }
        
        internal static string Found_unexpected_directory_0 {
            get {
                return ResourceManager.GetString("Found_unexpected_directory_0", resourceCulture);
            }
        }
        
        internal static string Found_unexpected_file_0 {
            get {
                return ResourceManager.GetString("Found_unexpected_file_0", resourceCulture);
            }
        }
        
        internal static string Error_0_getting_extended_attributes_for_entry_1 {
            get {
                return ResourceManager.GetString("Error_0_getting_extended_attributes_for_entry_1", resourceCulture);
            }
        }
        
        internal static string Found_unexpected_extended_attribute_0_in_file_1 {
            get {
                return ResourceManager.GetString("Found_unexpected_extended_attribute_0_in_file_1", resourceCulture);
            }
        }
        
        internal static string Error_0_reading_extended_attributes_for_entry_1 {
            get {
                return ResourceManager.GetString("Error_0_reading_extended_attributes_for_entry_1", resourceCulture);
            }
        }
        
        internal static string Invalid_checksum_for_xattr_0_for_file_1 {
            get {
                return ResourceManager.GetString("Invalid_checksum_for_xattr_0_for_file_1", resourceCulture);
            }
        }
        
        internal static string Expected_extended_attributes_not_found_for_file_0 {
            get {
                return ResourceManager.GetString("Expected_extended_attributes_not_found_for_file_0", resourceCulture);
            }
        }
        
        internal static string Error_0_reading_file_1 {
            get {
                return ResourceManager.GetString("Error_0_reading_file_1", resourceCulture);
            }
        }
        
        internal static string Invalid_checksum_for_file_0 {
            get {
                return ResourceManager.GetString("Invalid_checksum_for_file_0", resourceCulture);
            }
        }
        
        internal static string No_filesystems_found {
            get {
                return ResourceManager.GetString("No_filesystems_found", resourceCulture);
            }
        }
        
        internal static string Test_file_not_found {
            get {
                return ResourceManager.GetString("Test_file_not_found", resourceCulture);
            }
        }
        
        internal static string Filter_for_test_file_is_not_detected {
            get {
                return ResourceManager.GetString("Filter_for_test_file_is_not_detected", resourceCulture);
            }
        }
        
        internal static string Image_format_for_test_file_is_not_detected {
            get {
                return ResourceManager.GetString("Image_format_for_test_file_is_not_detected", resourceCulture);
            }
        }
        
        internal static string Cannot_open_image_for_test_file {
            get {
                return ResourceManager.GetString("Cannot_open_image_for_test_file", resourceCulture);
            }
        }
        
        internal static string Output_file_already_exists_not_continuing {
            get {
                return ResourceManager.GetString("Output_file_already_exists_not_continuing", resourceCulture);
            }
        }
        
        internal static string Input_image_format_not_identified_not_proceeding_with_conversion {
            get {
                return ResourceManager.GetString("Input_image_format_not_identified_not_proceeding_with_conversion", resourceCulture);
            }
        }
        
        internal static string Output_format_does_not_support_media_type_cannot_continue {
            get {
                return ResourceManager.GetString("Output_format_does_not_support_media_type_cannot_continue", resourceCulture);
            }
        }
        
        internal static string Input_image_does_not_support_long_sectors {
            get {
                return ResourceManager.GetString("Input_image_does_not_support_long_sectors", resourceCulture);
            }
        }
        
        internal static string Could_not_treat_existing_image_as_optical_disc {
            get {
                return ResourceManager.GetString("Could_not_treat_existing_image_as_optical_disc", resourceCulture);
            }
        }
        
        internal static string Could_not_treat_new_image_as_optical_disc {
            get {
                return ResourceManager.GetString("Could_not_treat_new_image_as_optical_disc", resourceCulture);
            }
        }
        
        internal static string Existing_image_contains_no_tracks {
            get {
                return ResourceManager.GetString("Existing_image_contains_no_tracks", resourceCulture);
            }
        }
        
        internal static string Error_0_creating_output_image {
            get {
                return ResourceManager.GetString("Error_0_creating_output_image", resourceCulture);
            }
        }
        
        internal static string Error_0_setting_metadata {
            get {
                return ResourceManager.GetString("Error_0_setting_metadata", resourceCulture);
            }
        }
        
        internal static string Converting_media_tag_0 {
            get {
                return ResourceManager.GetString("Converting_media_tag_0", resourceCulture);
            }
        }
        
        internal static string _0_sectors_to_convert {
            get {
                return ResourceManager.GetString("_0_sectors_to_convert", resourceCulture);
            }
        }
        
        internal static string Error_0_sending_tracks_list_to_output_image {
            get {
                return ResourceManager.GetString("Error_0_sending_tracks_list_to_output_image", resourceCulture);
            }
        }
        
        internal static string Error_0_writing_sector_1_not_continuing {
            get {
                return ResourceManager.GetString("Error_0_writing_sector_1_not_continuing", resourceCulture);
            }
        }
        
        internal static string Error_0_reading_tag_not_continuing {
            get {
                return ResourceManager.GetString("Error_0_reading_tag_not_continuing", resourceCulture);
            }
        }
        
        internal static string Error_0_writing_tag_not_continuing {
            get {
                return ResourceManager.GetString("Error_0_writing_tag_not_continuing", resourceCulture);
            }
        }
        
        internal static string Error_0_writing_tag_for_sector_1_not_continuing {
            get {
                return ResourceManager.GetString("Error_0_writing_tag_for_sector_1_not_continuing", resourceCulture);
            }
        }
        
        internal static string Error_0_closing_output_image_Contents_are_not_correct {
            get {
                return ResourceManager.GetString("Error_0_closing_output_image_Contents_are_not_correct", resourceCulture);
            }
        }
        
        internal static string Hashes_are_different {
            get {
                return ResourceManager.GetString("Hashes_are_different", resourceCulture);
            }
        }
        
        internal static string Image_format_for_test_file_is_not_for_an_optical_disc {
            get {
                return ResourceManager.GetString("Image_format_for_test_file_is_not_for_an_optical_disc", resourceCulture);
            }
        }
        
        internal static string Partitions_0 {
            get {
                return ResourceManager.GetString("Partitions_0", resourceCulture);
            }
        }
        
        internal static string Could_not_instantiate_input_plugin_for_0 {
            get {
                return ResourceManager.GetString("Could_not_instantiate_input_plugin_for_0", resourceCulture);
            }
        }
        
        internal static string Could_not_instantiate_output_plugin_for_0 {
            get {
                return ResourceManager.GetString("Could_not_instantiate_output_plugin_for_0", resourceCulture);
            }
        }
        
        internal static string Trying_to_convert_unsupported_media_type_0_for_1 {
            get {
                return ResourceManager.GetString("Trying_to_convert_unsupported_media_type_0_for_1", resourceCulture);
            }
        }
        
        internal static string Error_0_writing_sector_1 {
            get {
                return ResourceManager.GetString("Error_0_writing_sector_1", resourceCulture);
            }
        }
        
        internal static string Open_created_0 {
            get {
                return ResourceManager.GetString("Open_created_0", resourceCulture);
            }
        }
        
        internal static string Sectors_output_0 {
            get {
                return ResourceManager.GetString("Sectors_output_0", resourceCulture);
            }
        }
        
        internal static string Sector_size_output_0 {
            get {
                return ResourceManager.GetString("Sector_size_output_0", resourceCulture);
            }
        }
        
        internal static string Tracks_output_0 {
            get {
                return ResourceManager.GetString("Tracks_output_0", resourceCulture);
            }
        }
        
        internal static string Track_session_output_0 {
            get {
                return ResourceManager.GetString("Track_session_output_0", resourceCulture);
            }
        }
        
        internal static string Track_start_output_0 {
            get {
                return ResourceManager.GetString("Track_start_output_0", resourceCulture);
            }
        }
        
        internal static string Track_end_output_0 {
            get {
                return ResourceManager.GetString("Track_end_output_0", resourceCulture);
            }
        }
        
        internal static string Track_pregap_output_0 {
            get {
                return ResourceManager.GetString("Track_pregap_output_0", resourceCulture);
            }
        }
        
        internal static string Track_flags_output_0 {
            get {
                return ResourceManager.GetString("Track_flags_output_0", resourceCulture);
            }
        }
        
        internal static string Last_sector_for_tracks_is_0_but_it_is_1_for_image_output {
            get {
                return ResourceManager.GetString("Last_sector_for_tracks_is_0_but_it_is_1_for_image_output", resourceCulture);
            }
        }
        
        internal static string Long_hash_output {
            get {
                return ResourceManager.GetString("Long_hash_output", resourceCulture);
            }
        }
        
        internal static string Hash_output {
            get {
                return ResourceManager.GetString("Hash_output", resourceCulture);
            }
        }
        
        internal static string Subchannel_hash_output_0 {
            get {
                return ResourceManager.GetString("Subchannel_hash_output_0", resourceCulture);
            }
        }
    }
}
