//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.Devices {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aaru.Devices.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string READ_BUFFER_took_0_ms {
            get {
                return ResourceManager.GetString("READ_BUFFER_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_BUFFER_DMA_took_0_ms {
            get {
                return ResourceManager.GetString("READ_BUFFER_DMA_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_DMA_took_0_ms {
            get {
                return ResourceManager.GetString("READ_DMA_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_MULTIPLE_took_0_ms {
            get {
                return ResourceManager.GetString("READ_MULTIPLE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_NATIVE_MAX_ADDRESS_took_0_ms {
            get {
                return ResourceManager.GetString("READ_NATIVE_MAX_ADDRESS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_SECTORS_took_0_ms {
            get {
                return ResourceManager.GetString("READ_SECTORS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_LONG_took_0_ms {
            get {
                return ResourceManager.GetString("READ_LONG_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SEEK_took_0_ms {
            get {
                return ResourceManager.GetString("SEEK_took_0_ms", resourceCulture);
            }
        }
        
        internal static string GET_NATIVE_MAX_ADDRESS_EXT_took_0_ms {
            get {
                return ResourceManager.GetString("GET_NATIVE_MAX_ADDRESS_EXT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_DMA_EXT_took_0_ms {
            get {
                return ResourceManager.GetString("READ_DMA_EXT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_LOG_EXT_took_0_ms {
            get {
                return ResourceManager.GetString("READ_LOG_EXT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_LOG_DMA_EXT_took_0_ms {
            get {
                return ResourceManager.GetString("READ_LOG_DMA_EXT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_MULTIPLE_EXT_took_0_ms {
            get {
                return ResourceManager.GetString("READ_MULTIPLE_EXT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_NATIVE_MAX_ADDRESS_EXT_took_0_ms {
            get {
                return ResourceManager.GetString("READ_NATIVE_MAX_ADDRESS_EXT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_SECTORS_EXT_took_0_ms {
            get {
                return ResourceManager.GetString("READ_SECTORS_EXT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SET_FEATURES_took_0_ms {
            get {
                return ResourceManager.GetString("SET_FEATURES_took_0_ms", resourceCulture);
            }
        }
        
        internal static string DOOR_LOCK_took_0_ms {
            get {
                return ResourceManager.GetString("DOOR_LOCK_took_0_ms", resourceCulture);
            }
        }
        
        internal static string DOOR_UNLOCK_took_0_ms {
            get {
                return ResourceManager.GetString("DOOR_UNLOCK_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MEDIA_EJECT_took_0_ms {
            get {
                return ResourceManager.GetString("MEDIA_EJECT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string IDENTIFY_PACKET_DEVICE_took_0_ms {
            get {
                return ResourceManager.GetString("IDENTIFY_PACKET_DEVICE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string CFA_TRANSLATE_SECTOR_took_0_ms {
            get {
                return ResourceManager.GetString("CFA_TRANSLATE_SECTOR_took_0_ms", resourceCulture);
            }
        }
        
        internal static string CFA_REQUEST_EXTENDED_ERROR_CODE_took_0_ms {
            get {
                return ResourceManager.GetString("CFA_REQUEST_EXTENDED_ERROR_CODE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string CHECK_MEDIA_CARD_TYPE_took_0_ms {
            get {
                return ResourceManager.GetString("CHECK_MEDIA_CARD_TYPE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SMART_DISABLE_OPERATIONS_took_0_ms {
            get {
                return ResourceManager.GetString("SMART_DISABLE_OPERATIONS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SMART_ENABLE_ATTRIBUTE_AUTOSAVE_took_0_ms {
            get {
                return ResourceManager.GetString("SMART_ENABLE_ATTRIBUTE_AUTOSAVE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SMART_DISABLE_ATTRIBUTE_AUTOSAVE_took_0_ms {
            get {
                return ResourceManager.GetString("SMART_DISABLE_ATTRIBUTE_AUTOSAVE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SMART_ENABLE_OPERATIONS_took_0_ms {
            get {
                return ResourceManager.GetString("SMART_ENABLE_OPERATIONS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SMART_EXECUTE_OFF_LINE_IMMEDIATE_took_0_ms {
            get {
                return ResourceManager.GetString("SMART_EXECUTE_OFF_LINE_IMMEDIATE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SMART_READ_DATA_took_0_ms {
            get {
                return ResourceManager.GetString("SMART_READ_DATA_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SMART_READ_LOG_took_0_ms {
            get {
                return ResourceManager.GetString("SMART_READ_LOG_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SMART_RETURN_STATUS_took_0_ms {
            get {
                return ResourceManager.GetString("SMART_RETURN_STATUS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SEND_CSD_took_0_ms {
            get {
                return ResourceManager.GetString("SEND_CSD_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SEND_CID_took_0_ms {
            get {
                return ResourceManager.GetString("SEND_CID_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SEND_OP_COND_took_0_ms {
            get {
                return ResourceManager.GetString("SEND_OP_COND_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SEND_EXT_CSD_took_0_ms {
            get {
                return ResourceManager.GetString("SEND_EXT_CSD_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SET_BLOCKLEN_took_0_ms {
            get {
                return ResourceManager.GetString("SET_BLOCKLEN_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_SINGLE_BLOCK_took_0_ms {
            get {
                return ResourceManager.GetString("READ_SINGLE_BLOCK_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_MULTIPLE_BLOCK_took_0_ms {
            get {
                return ResourceManager.GetString("READ_MULTIPLE_BLOCK_took_0_ms", resourceCulture);
            }
        }
        
        internal static string Multiple_READ_SINGLE_BLOCKs_took_0_ms {
            get {
                return ResourceManager.GetString("Multiple_READ_SINGLE_BLOCKs_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SEND_STATUS_took_0_ms {
            get {
                return ResourceManager.GetString("SEND_STATUS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SD_STATUS_took_0_ms {
            get {
                return ResourceManager.GetString("SD_STATUS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SD_SEND_OP_COND_took_0_ms {
            get {
                return ResourceManager.GetString("SD_SEND_OP_COND_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SEND_SCR_took_0_ms {
            get {
                return ResourceManager.GetString("SEND_SCR_took_0_ms", resourceCulture);
            }
        }
        
        internal static string ADAPTEC_TRANSLATE_took_0_ms {
            get {
                return ResourceManager.GetString("ADAPTEC_TRANSLATE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string ADAPTEC_SET_ERROR_THRESHOLD_took_0_ms {
            get {
                return ResourceManager.GetString("ADAPTEC_SET_ERROR_THRESHOLD_took_0_ms", resourceCulture);
            }
        }
        
        internal static string ADAPTEC_READ_RESET_USAGE_COUNTER_took_0_ms {
            get {
                return ResourceManager.GetString("ADAPTEC_READ_RESET_USAGE_COUNTER_took_0_ms", resourceCulture);
            }
        }
        
        internal static string ADAPTEC_WRITE_DATA_BUFFER_took_0_ms {
            get {
                return ResourceManager.GetString("ADAPTEC_WRITE_DATA_BUFFER_took_0_ms", resourceCulture);
            }
        }
        
        internal static string ADAPTEC_READ_DATA_BUFFER_took_0_ms {
            get {
                return ResourceManager.GetString("ADAPTEC_READ_DATA_BUFFER_took_0_ms", resourceCulture);
            }
        }
        
        internal static string ARCHIVE_CORP_REQUEST_BLOCK_ADDRESS_took_0_ms {
            get {
                return ResourceManager.GetString("ARCHIVE_CORP_REQUEST_BLOCK_ADDRESS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string ARCHIVE_CORP_SEEK_BLOCK_took_0_ms {
            get {
                return ResourceManager.GetString("ARCHIVE_CORP_SEEK_BLOCK_took_0_ms", resourceCulture);
            }
        }
        
        internal static string CERTANCE_PARK_UNPARK_took_0_ms {
            get {
                return ResourceManager.GetString("CERTANCE_PARK_UNPARK_took_0_ms", resourceCulture);
            }
        }
        
        internal static string FUJITSU_DISPLAY_took_0_ms {
            get {
                return ResourceManager.GetString("FUJITSU_DISPLAY_took_0_ms", resourceCulture);
            }
        }
        
        internal static string HL_DT_ST_READ_DVD_RAW_took_0_ms {
            get {
                return ResourceManager.GetString("HL_DT_ST_READ_DVD_RAW_took_0_ms", resourceCulture);
            }
        }
        
        internal static string HP_READ_LONG_took_0_ms {
            get {
                return ResourceManager.GetString("HP_READ_LONG_took_0_ms", resourceCulture);
            }
        }
        
        internal static string KREON_DEPRECATED_UNLOCK_took_0_ms {
            get {
                return ResourceManager.GetString("KREON_DEPRECATED_UNLOCK_took_0_ms", resourceCulture);
            }
        }
        
        internal static string KREON_SET_LOCK_STATE_took_0_ms {
            get {
                return ResourceManager.GetString("KREON_SET_LOCK_STATE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string KREON_GET_FEATURE_LIST_took_0_ms {
            get {
                return ResourceManager.GetString("KREON_GET_FEATURE_LIST_took_0_ms", resourceCulture);
            }
        }
        
        internal static string KREON_EXTRACT_SS_took_0_ms {
            get {
                return ResourceManager.GetString("KREON_EXTRACT_SS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MediaTek_READ_DRAM_took_0_ms {
            get {
                return ResourceManager.GetString("MediaTek_READ_DRAM_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MINIDISC_READ_DTOC_took_0_ms {
            get {
                return ResourceManager.GetString("MINIDISC_READ_DTOC_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MINIDISC_READ_UTOC_took_0_ms {
            get {
                return ResourceManager.GetString("MINIDISC_READ_UTOC_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MINIDISC_command_D5h_took_0_ms {
            get {
                return ResourceManager.GetString("MINIDISC_command_D5h_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MINIDISC_STOP_PLAY_took_0_ms {
            get {
                return ResourceManager.GetString("MINIDISC_STOP_PLAY_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MINIDISC_READ_POSITION_took_0_ms {
            get {
                return ResourceManager.GetString("MINIDISC_READ_POSITION_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MINIDISC_GET_TYPE_took_0_ms {
            get {
                return ResourceManager.GetString("MINIDISC_GET_TYPE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string GET_CONFIGURATION_Starting_Feature_Number_1_Return_Type_2_Sense_3_Last_Error_4_took_0_ms {
            get {
                return ResourceManager.GetString("GET_CONFIGURATION_Starting_Feature_Number_1_Return_Type_2_Sense_3_Last_Error_4_to" +
                        "ok_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_DISC_STRUCTURE_Media_Type_1_Address_2_Layer_Number_3_Format_4_AGID_5_Sense_6_Last_Error_7_took_0_ms {
            get {
                return ResourceManager.GetString("READ_DISC_STRUCTURE_Media_Type_1_Address_2_Layer_Number_3_Format_4_AGID_5_Sense_6" +
                        "_Last_Error_7_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_TOC_PMA_ATIP_took_MSF_1_Format_2_Track_Session_Number_3_Sense_4_LastError_5_0_ms {
            get {
                return ResourceManager.GetString("READ_TOC_PMA_ATIP_took_MSF_1_Format_2_Track_Session_Number_3_Sense_4_LastError_5_" +
                        "0_ms", resourceCulture);
            }
        }
        
        internal static string READ_DISC_INFORMATION_Data_Type_1_Sense_2_Last_Error_3_took_0_ms {
            get {
                return ResourceManager.GetString("READ_DISC_INFORMATION_Data_Type_1_Sense_2_Last_Error_3_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_CD_LBA_1_Block_Size_2_Transfer_Length_3_Expected_Sector_Type_4_DAP_5_Relative_Address_6_Sync_7_Headers_8_User_Data_9_ECC_EDC_10_C2_11_Subchannel_12_Sense_13_Last_Error_14_took_0_ms {
            get {
                return ResourceManager.GetString("READ_CD_LBA_1_Block_Size_2_Transfer_Length_3_Expected_Sector_Type_4_DAP_5_Relativ" +
                        "e_Address_6_Sync_7_Headers_8_User_Data_9_ECC_EDC_10_C2_11_Subchannel_12_Sense_13" +
                        "_Last_Error_14_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_CD_MSF_Start_MSF_1_End_MSF_2_Block_Size_3_Expected_Sector_Type_4_DAP_5_Sync_6_Headers_7_User_Data_8_ECC_EDC_9_C2_10_Subchannel_11_Sense_12_LastError_13_took_0_ms {
            get {
                return ResourceManager.GetString("READ_CD_MSF_Start_MSF_1_End_MSF_2_Block_Size_3_Expected_Sector_Type_4_DAP_5_Sync_" +
                        "6_Headers_7_User_Data_8_ECC_EDC_9_C2_10_Subchannel_11_Sense_12_LastError_13_took" +
                        "_0_ms", resourceCulture);
            }
        }
        
        internal static string PREVENT_ALLOW_MEDIUM_REMOVAL_Persistent_1_Prevent_2_Sense_3_LastError_4_took_0_ms {
            get {
                return ResourceManager.GetString("PREVENT_ALLOW_MEDIUM_REMOVAL_Persistent_1_Prevent_2_Sense_3_LastError_4_took_0_ms" +
                        "", resourceCulture);
            }
        }
        
        internal static string START_STOP_UNIT_Immediate_1_FormatLayer_2_Power_Conditions_3_Change_Format_Layer_4_Load_Eject_5_Start_6_Sense_7_Last_Error_8_took_0_ms {
            get {
                return ResourceManager.GetString("START_STOP_UNIT_Immediate_1_FormatLayer_2_Power_Conditions_3_Change_Format_Layer_" +
                        "4_Load_Eject_5_Start_6_Sense_7_Last_Error_8_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_READ_SUB_CHANNEL_MCN_Sense_1_Last_Error_2_took_0_ms {
            get {
                return ResourceManager.GetString("READ_READ_SUB_CHANNEL_MCN_Sense_1_Last_Error_2_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_READ_SUB_CHANNEL_ISRC_Track_Number_1_Sense_2_Last_Error_3_took_0_ms {
            get {
                return ResourceManager.GetString("READ_READ_SUB_CHANNEL_ISRC_Track_Number_1_Sense_2_Last_Error_3_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SET_CD_SPEED_Rotational_Control_1_Read_Speed_2_Write_Speed_3_Sense_4_Last_Error_5_took_0_ms {
            get {
                return ResourceManager.GetString("SET_CD_SPEED_Rotational_Control_1_Read_Speed_2_Write_Speed_3_Sense_4_Last_Error_5" +
                        "_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_TRACK_INFORMATION_Data_Type_1_Sense_2_Last_Error_3_took_0_ms {
            get {
                return ResourceManager.GetString("READ_TRACK_INFORMATION_Data_Type_1_Sense_2_Last_Error_3_took_0_ms", resourceCulture);
            }
        }
        
        internal static string NEC_READ_CD_DA_took_0_ms {
            get {
                return ResourceManager.GetString("NEC_READ_CD_DA_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MEDIUM_SCAN_took_0_ms {
            get {
                return ResourceManager.GetString("MEDIUM_SCAN_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PIONEER_READ_CD_DA_took_0_ms {
            get {
                return ResourceManager.GetString("PIONEER_READ_CD_DA_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PIONEER_READ_CD_DA_MSF_took_0_ms {
            get {
                return ResourceManager.GetString("PIONEER_READ_CD_DA_MSF_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PIONEER_READ_CD_XA_took_0_ms {
            get {
                return ResourceManager.GetString("PIONEER_READ_CD_XA_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLASMON_READ_SECTOR_LOCATION_took_0_ms {
            get {
                return ResourceManager.GetString("PLASMON_READ_SECTOR_LOCATION_took_0_ms", resourceCulture);
            }
        }
        
        internal static string Plextor_READ_CD_DA_LBA_1_Block_Size_2_Transfer_Length_3_Subchannel_4_Sense_5_Last_Error_6_took_0_ms {
            get {
                return ResourceManager.GetString("Plextor_READ_CD_DA_LBA_1_Block_Size_2_Transfer_Length_3_Subchannel_4_Sense_5_Last" +
                        "_Error_6_took_0_ms", resourceCulture);
            }
        }
        
        internal static string Plextor_READ_DVD_RAW_took_0_ms {
            get {
                return ResourceManager.GetString("Plextor_READ_DVD_RAW_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_READ_EEPROM_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_READ_EEPROM_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_POWEREC_GET_SPEEDS_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_POWEREC_GET_SPEEDS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_GET_SILENT_MODE_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_GET_SILENT_MODE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_GET_GIGAREC_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_GET_GIGAREC_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_GET_VARIREC_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_GET_VARIREC_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_GET_SECUREC_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_GET_SECUREC_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_GET_SPEEDREAD_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_GET_SPEEDREAD_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_GET_SINGLE_SESSION_HIDE_CD_R_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_GET_SINGLE_SESSION_HIDE_CD_R_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_GET_BOOK_BITSETTING_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_GET_BOOK_BITSETTING_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PLEXTOR_GET_TEST_WRITE_DVD_took_0_ms {
            get {
                return ResourceManager.GetString("PLEXTOR_GET_TEST_WRITE_DVD_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_6_took_0_ms {
            get {
                return ResourceManager.GetString("READ_6_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_10_took_0_ms {
            get {
                return ResourceManager.GetString("READ_10_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_12_took_0_ms {
            get {
                return ResourceManager.GetString("READ_12_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_16_took_0_ms {
            get {
                return ResourceManager.GetString("READ_16_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_LONG_10_took_0_ms {
            get {
                return ResourceManager.GetString("READ_LONG_10_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_LONG_16_took_0_ms {
            get {
                return ResourceManager.GetString("READ_LONG_16_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SEEK_6_took_0_ms {
            get {
                return ResourceManager.GetString("SEEK_6_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SEEK_10_took_0_ms {
            get {
                return ResourceManager.GetString("SEEK_10_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_ATTRIBUTE_took_0_ms {
            get {
                return ResourceManager.GetString("READ_ATTRIBUTE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string INQUIRY_took_0_ms {
            get {
                return ResourceManager.GetString("INQUIRY_took_0_ms", resourceCulture);
            }
        }
        
        internal static string TEST_UNIT_READY_took_0_ms {
            get {
                return ResourceManager.GetString("TEST_UNIT_READY_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MODE_SENSE_6_took_0_ms {
            get {
                return ResourceManager.GetString("MODE_SENSE_6_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MODE_SENSE_10_took_0_ms {
            get {
                return ResourceManager.GetString("MODE_SENSE_10_took_0_ms", resourceCulture);
            }
        }
        
        internal static string PREVENT_ALLOW_MEDIUM_REMOVAL_took_0_ms {
            get {
                return ResourceManager.GetString("PREVENT_ALLOW_MEDIUM_REMOVAL_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_CAPACITY_took_0_ms {
            get {
                return ResourceManager.GetString("READ_CAPACITY_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_CAPACITY_16_took_0_ms {
            get {
                return ResourceManager.GetString("READ_CAPACITY_16_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_MEDIA_SERIAL_NUMBER_took_0_ms {
            get {
                return ResourceManager.GetString("READ_MEDIA_SERIAL_NUMBER_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MODE_SELECT_6_took_0_ms {
            get {
                return ResourceManager.GetString("MODE_SELECT_6_took_0_ms", resourceCulture);
            }
        }
        
        internal static string MODE_SELECT_10_took_0_ms {
            get {
                return ResourceManager.GetString("MODE_SELECT_10_took_0_ms", resourceCulture);
            }
        }
        
        internal static string REQUEST_SENSE_took_0_ms {
            get {
                return ResourceManager.GetString("REQUEST_SENSE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string LOAD_UNLOAD_6_took_0_ms {
            get {
                return ResourceManager.GetString("LOAD_UNLOAD_6_took_0_ms", resourceCulture);
            }
        }
        
        internal static string LOCATE_10_took_0_ms {
            get {
                return ResourceManager.GetString("LOCATE_10_took_0_ms", resourceCulture);
            }
        }
        
        internal static string LOCATE_16_took_0_ms {
            get {
                return ResourceManager.GetString("LOCATE_16_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_BLOCK_LIMITS_took_0_ms {
            get {
                return ResourceManager.GetString("READ_BLOCK_LIMITS_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_POSITION_took_0_ms {
            get {
                return ResourceManager.GetString("READ_POSITION_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_REVERSE_6_took_0_ms {
            get {
                return ResourceManager.GetString("READ_REVERSE_6_took_0_ms", resourceCulture);
            }
        }
        
        internal static string READ_REVERSE_16_took_0_ms {
            get {
                return ResourceManager.GetString("READ_REVERSE_16_took_0_ms", resourceCulture);
            }
        }
        
        internal static string RECOVER_BUFFERED_DATA_took_0_ms {
            get {
                return ResourceManager.GetString("RECOVER_BUFFERED_DATA_took_0_ms", resourceCulture);
            }
        }
        
        internal static string REPORT_DENSITY_SUPPORT_took_0_ms {
            get {
                return ResourceManager.GetString("REPORT_DENSITY_SUPPORT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string REWIND_took_0_ms {
            get {
                return ResourceManager.GetString("REWIND_took_0_ms", resourceCulture);
            }
        }
        
        internal static string TRACK_SELECT_took_0_ms {
            get {
                return ResourceManager.GetString("TRACK_SELECT_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SPACE_took_0_ms {
            get {
                return ResourceManager.GetString("SPACE_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SYQUEST_READ_6_took_0_ms {
            get {
                return ResourceManager.GetString("SYQUEST_READ_6_took_0_ms", resourceCulture);
            }
        }
        
        internal static string SYQUEST_READ_10_took_0_ms {
            get {
                return ResourceManager.GetString("SYQUEST_READ_10_took_0_ms", resourceCulture);
            }
        }
        
        internal static string Platform_0_not_yet_supported {
            get {
                return ResourceManager.GetString("Platform_0_not_yet_supported", resourceCulture);
            }
        }
        
        internal static string Invalid_remote_URI {
            get {
                return ResourceManager.GetString("Invalid_remote_URI", resourceCulture);
            }
        }
        
        internal static string Error_connecting_to_host {
            get {
                return ResourceManager.GetString("Error_connecting_to_host", resourceCulture);
            }
        }
        
        internal static string Invalid_remote_protocol {
            get {
                return ResourceManager.GetString("Invalid_remote_protocol", resourceCulture);
            }
        }
        
        internal static string Host_not_found {
            get {
                return ResourceManager.GetString("Host_not_found", resourceCulture);
            }
        }
        
        internal static string Connected_to_0 {
            get {
                return ResourceManager.GetString("Connected_to_0", resourceCulture);
            }
        }
        
        internal static string Could_not_read_from_the_network {
            get {
                return ResourceManager.GetString("Could_not_read_from_the_network", resourceCulture);
            }
        }
        
        internal static string Received_data_is_not_an_Aaru_Remote_Packet {
            get {
                return ResourceManager.GetString("Received_data_is_not_an_Aaru_Remote_Packet", resourceCulture);
            }
        }
        
        internal static string Expected_Hello_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_Hello_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Unrecognized_packet_version {
            get {
                return ResourceManager.GetString("Unrecognized_packet_version", resourceCulture);
            }
        }
        
        internal static string Could_not_write_to_the_network {
            get {
                return ResourceManager.GetString("Could_not_write_to_the_network", resourceCulture);
            }
        }
        
        internal static string Remote_IsRoot_Expected_Am_I_Root_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Remote_IsRoot_Expected_Am_I_Root_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Remote_ListDevices_Expected_List_Devices_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Remote_ListDevices_Expected_List_Devices_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_SCSI_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_SCSI_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_ATA_CHS_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_ATA_CHS_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_ATA_LBA28_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_ATA_LBA28_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_ATA_LBA48_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_ATA_LBA48_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_SDHCI_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_SDHCI_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_Device_Type_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_Device_Type_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_USB_Data_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_USB_Data_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_FireWire_Data_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_FireWire_Data_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_PCMCIA_Data_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_PCMCIA_Data_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_multi_MMC_SD_command_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_multi_MMC_SD_command_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Expected_the_response_to_0_SD_MMC_commands_but_got_1_responses {
            get {
                return ResourceManager.GetString("Expected_the_response_to_0_SD_MMC_commands_but_got_1_responses", resourceCulture);
            }
        }
        
        internal static string Expected_NOP_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_NOP_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string ReOpen_error_closing_device {
            get {
                return ResourceManager.GetString("ReOpen_error_closing_device", resourceCulture);
            }
        }
        
        internal static string ReOpen_error_0_with_reason_1 {
            get {
                return ResourceManager.GetString("ReOpen_error_0_with_reason_1", resourceCulture);
            }
        }
        
        internal static string Expected_OS_Read_Response_Packet_got_packet_type_0 {
            get {
                return ResourceManager.GetString("Expected_OS_Read_Response_Packet_got_packet_type_0", resourceCulture);
            }
        }
        
        internal static string Remote_error_0_in_OS_Read {
            get {
                return ResourceManager.GetString("Remote_error_0_in_OS_Read", resourceCulture);
            }
        }
    }
}
