using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using Aaru.CommonTypes;
using Aaru.CommonTypes.AaruMetadata;
using Aaru.CommonTypes.Enums;
using Aaru.CommonTypes.Interfaces;
using Aaru.Core;
using FluentAssertions;
using FluentAssertions.Execution;
using NUnit.Framework;
using Directory = System.IO.Directory;
using Encoding = System.Text.Encoding;
using File = System.IO.File;
using Partition = Aaru.CommonTypes.Partition;

namespace Aaru.Tests.Filesystems;

[Parallelizable(ParallelScope.Self)]
public abstract class FilesystemTest(string fileSystemType)
{
    const string INFO_SUFFIX = ".info.json";

    static readonly object _initLock = new();

    internal static readonly JsonSerializerOptions InfoSerializerOptions = new()
    {
        Converters =
        {
            new JsonStringEnumConverter()
        },
        IncludeFields               = true,
        WriteIndented               = true,
        DefaultIgnoreCondition      = JsonIgnoreCondition.WhenWritingNull,
        PropertyNameCaseInsensitive = true
    };

    protected FilesystemTest() : this(null) {}

    public abstract string      DataFolder { get; }
    public abstract IFilesystem Plugin     { get; }
    public abstract bool        Partitions { get; }

    public abstract FileSystemTest[] Tests { get; }

    /// <summary>
    ///     In-code <see cref="Tests" /> plus any image in <see cref="DataFolder" /> that has a sidecar
    ///     {image}.info.json (generated by ReadOnlyFilesystemTest.Build), so new images need no code changes.
    /// </summary>
    protected FileSystemTest[] AllTests => field ??= LoadTests();

    [OneTimeSetUp]
    public void InitTest()
    {
        lock(_initLock) PluginBase.Init();
    }

    FileSystemTest[] LoadTests()
    {
        List<FileSystemTest> all = [.. Tests];

        if(!Directory.Exists(DataFolder)) return all.ToArray();

        HashSet<string> known = all.Select(static t => t.TestFile).ToHashSet(StringComparer.Ordinal);

        foreach(string infoPath in Directory.GetFiles(DataFolder, $"*{INFO_SUFFIX}")
                                            .OrderBy(static p => p, StringComparer.Ordinal))
        {
            string imageFile = Path.GetFileName(infoPath)[..^INFO_SUFFIX.Length];

            if(known.Contains(imageFile)) continue;

            using FileStream stream = File.OpenRead(infoPath);

            var test = JsonSerializer.Deserialize<FileSystemTest>(stream, InfoSerializerOptions);

            if(test is null) continue;

            test.TestFile     =   imageFile;
            test.FromInfoJson =   true;
            test.Encoding     ??= ResolveEncoding(test.EncodingName);

            all.Add(test);
        }

        return all.ToArray();
    }

    internal static Encoding ResolveEncoding(string name) =>
        string.IsNullOrEmpty(name) ? null : Claunia.Encoding.Encoding.GetEncoding(name);

    /// <summary>
    ///     Disposes an image deterministically so native resources are released on the test thread instead
    ///     of the finalizer. Requires libaaruformat newer than 1.0.0-beta.1 (its aaruf_close double-frees,
    ///     aborting the test host after the second image closed in a process; fixed upstream in bbb0403).
    /// </summary>
    internal static void DisposeImage(IBaseImage image) => (image as IDisposable)?.Dispose();


    [Test]
    public void Detect()
    {
        using(new AssertionScope())
        {
            foreach(FileSystemTest test in AllTests)
            {
                string testFile = Path.Combine(DataFolder, test.TestFile);

                bool exists = File.Exists(testFile);
                exists.Should().BeTrue(Localization._0_not_found, testFile);

                if(!exists) continue;

                IFilter inputFilter = PluginRegister.Singleton.GetFilter(testFile);

                inputFilter.Should().NotBeNull(Localization.Filter_0, testFile);

                IBaseImage detected = ImageFormat.Detect(inputFilter);

                (detected is IMediaImage).Should().BeTrue(Localization.Image_format_0, testFile);

                if(detected is not IMediaImage image) continue;

                try
                {
                    image.Open(inputFilter)
                         .Should()
                         .Be(ErrorNumber.NoError, string.Format(Localization.Cannot_open_image_for_0, testFile));

                    List<string> idPlugins;

                    if(Partitions)
                    {
                        List<Partition> partitionsList = Core.Partitions.GetAll(image);

                        partitionsList.Should().NotBeEmpty(Localization.No_partitions_found_for_0, testFile);

                        var found = false;

                        foreach(Partition p in partitionsList)
                        {
                            Core.Filesystems.Identify(image, out idPlugins, p, true);

                            if(idPlugins.Count == 0) continue;

                            if(!idPlugins.Contains(Plugin.Id.ToString())) continue;

                            found = true;

                            break;
                        }

                        found.Should().BeTrue(Localization.Filesystem_not_identified_for_0, testFile);
                    }
                    else
                    {
                        var wholePart = new Partition
                        {
                            Name   = "Whole device",
                            Length = image.Info.Sectors,
                            Size   = image.Info.Sectors * image.Info.SectorSize
                        };

                        Core.Filesystems.Identify(image, out idPlugins, wholePart, true);

                        idPlugins.Should().NotBeEmpty(Localization.No_filesystems_found_for_0, testFile);

                        idPlugins.Should()
                                 .Contain(Plugin.Id.ToString(),
                                          string.Format(Localization.Not_identified_for_0, testFile));
                    }
                }
                finally
                {
                    // Dispose deterministically so image finalizers never run native close code
                    // concurrently with other tests' native reads
                    DisposeImage(image);
                }
            }
        }
    }

    [Test]
    public void ImageInfo()
    {
        using(new AssertionScope())
        {
            foreach(FileSystemTest test in AllTests)
            {
                string testFile = Path.Combine(DataFolder, test.TestFile);

                bool exists = File.Exists(testFile);
                exists.Should().BeTrue(Localization._0_not_found, testFile);

                if(!exists) continue;

                IFilter inputFilter = PluginRegister.Singleton.GetFilter(testFile);

                inputFilter.Should().NotBeNull(Localization.Filter_0, testFile);

                IBaseImage detected = ImageFormat.Detect(inputFilter);

                (detected is IMediaImage).Should().BeTrue(Localization.Image_format_0, testFile);

                if(detected is not IMediaImage image) continue;

                try
                {
                    image.Open(inputFilter)
                         .Should()
                         .Be(ErrorNumber.NoError, string.Format(Localization.Cannot_open_image_for_0, testFile));

                    image.Info.MediaType.Should().Be(test.MediaType, testFile);
                    image.Info.Sectors.Should().Be(test.Sectors, testFile);
                    image.Info.SectorSize.Should().Be(test.SectorSize, testFile);
                }
                finally
                {
                    DisposeImage(image);
                }
            }
        }
    }

    [Test]
    public void Info()
    {
        using(new AssertionScope())
        {
            foreach(FileSystemTest test in AllTests)
            {
                string testFile  = Path.Combine(DataFolder, test.TestFile);
                var    found     = false;
                var    partition = new Partition();

                bool exists = File.Exists(testFile);
                exists.Should().BeTrue(Localization._0_not_found, testFile);

                if(!exists) continue;

                IFilter inputFilter = PluginRegister.Singleton.GetFilter(testFile);

                inputFilter.Should().NotBeNull(Localization.Filter_0, testFile);

                IBaseImage detected = ImageFormat.Detect(inputFilter);

                (detected is IMediaImage).Should().BeTrue(Localization.Image_format_0, testFile);

                if(detected is not IMediaImage image) continue;

                try
                {
                    image.Open(inputFilter)
                         .Should()
                         .Be(ErrorNumber.NoError, string.Format(Localization.Cannot_open_image_for_0, testFile));

                    List<string> idPlugins;

                    if(Partitions)
                    {
                        List<Partition> partitionsList = Core.Partitions.GetAll(image);

                        partitionsList.Should().NotBeEmpty(Localization.No_partitions_found_for_0, testFile);

                        // In reverse to skip boot partitions we're not interested in
                        for(int index = partitionsList.Count - 1; index >= 0; index--)
                        {
                            Core.Filesystems.Identify(image, out idPlugins, partitionsList[index], true);

                            if(idPlugins.Count == 0) continue;

                            if(!idPlugins.Contains(Plugin.Id.ToString())) continue;

                            found     = true;
                            partition = partitionsList[index];

                            break;
                        }
                    }
                    else
                    {
                        partition = new Partition
                        {
                            Name   = "Whole device",
                            Length = image.Info.Sectors,
                            Size   = image.Info.Sectors * image.Info.SectorSize
                        };

                        Core.Filesystems.Identify(image, out idPlugins, partition, true);

                        idPlugins.Should().NotBeEmpty(Localization.No_filesystems_found_for_0, testFile);

                        found = idPlugins.Contains(Plugin.Id.ToString());
                    }

                    found.Should().BeTrue(Localization.Filesystem_not_identified_for_0, testFile);

                    if(!found) continue;

                    object instance = Activator.CreateInstance(Plugin.GetType());

                    (instance is IFilesystem).Should()
                                             .BeTrue(Localization.Could_not_instantiate_filesystem_for_0, testFile);

                    if(instance is not IFilesystem fs) continue;

                    fs.GetInformation(image, partition, null, out _, out FileSystem fsMetadata);

                    if(test.ApplicationId != null)
                    {
                        fsMetadata.ApplicationIdentifier.Should()
                                  .Be(test.ApplicationId, string.Format(Localization.Application_ID_0, testFile));
                    }

                    fsMetadata.Bootable.Should().Be(test.Bootable, string.Format(Localization.Bootable_0, testFile));

                    fsMetadata.Clusters.Should()
                              .Be((ulong)test.Clusters, string.Format(Localization.Clusters_0, testFile));

                    fsMetadata.ClusterSize.Should()
                              .Be(test.ClusterSize, string.Format(Localization.Cluster_size_0, testFile));

                    if(test.SystemId != null)
                    {
                        fsMetadata.SystemIdentifier.Should()
                                  .Be(test.SystemId, string.Format(Localization.System_ID_0, testFile));
                    }

                    fsMetadata.Type.Should()
                              .Be(fileSystemType ?? test.Type, string.Format(Localization.Filesystem_type_0, testFile));

                    fsMetadata.VolumeName.Should()
                              .Be(test.VolumeName, string.Format(Localization.Volume_name_0, testFile));

                    fsMetadata.VolumeSerial.Should()
                              .Be(test.VolumeSerial, string.Format(Localization.Volume_serial_0, testFile));
                }
                finally
                {
                    DisposeImage(image);
                }
            }
        }
    }
}