//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.CommonTypes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aaru.CommonTypes.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is SyQuest, media has 1961069 blocks of 512 bytes, setting media type to SparQ..
        /// </summary>
        internal static string Drive_manufacturer_is_SyQuest_media_has_1961069_blocks_of_512_bytes_setting_media_type_to_SparQ {
            get {
                return ResourceManager.GetString("Drive_manufacturer_is_SyQuest_media_has_1961069_blocks_of_512_bytes_setting_media" +
                        "_type_to_SparQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception {0}.
        /// </summary>
        internal static string Exception_0 {
            get {
                return ResourceManager.GetString("Exception_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTIFY response is different than 512 bytes, not decoding..
        /// </summary>
        internal static string IDENTIFY_response_is_different_than_512_bytes_not_decoding {
            get {
                return ResourceManager.GetString("IDENTIFY_response_is_different_than_512_bytes_not_decoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INQUIRY response is {0} bytes, less than minimum of 36 bytes, decoded data can be incorrect, not decoding..
        /// </summary>
        internal static string INQUIRY_response_is_0_bytes_less_than_minimum_of_36_bytes {
            get {
                return ResourceManager.GetString("INQUIRY_response_is_0_bytes_less_than_minimum_of_36_bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INQUIRY response length ({0} bytes) is different than specified in length field ({1} bytes), decoded data can be incorrect, not decoding..
        /// </summary>
        internal static string INQUIRY_response_length_0_bytes_is_different_than_specified_in_length_field {
            get {
                return ResourceManager.GetString("INQUIRY_response_length_0_bytes_is_different_than_specified_in_length_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Acorn formatted 5¼&quot; double density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Acorn_MD1DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Acorn_MD1DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Acorn formatted 5¼&quot; double density floppy with 80 tracks..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Acorn_MD1DD_80 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Acorn_MD1DD_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Acorn formatted 5¼&quot; single density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Acorn_MD1SD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Acorn_MD1SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Acorn formatted 3½&quot; double density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Acorn_MF2DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Acorn_MF2DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Acorn formatted 3½&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Acorn_MF2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Acorn_MF2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Amiga formatted 3½&quot; double density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Amiga_MF2DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Amiga_MF2DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Amiga formatted 3½&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Amiga_MF2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Amiga_MF2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Apple DOS 3.2 formatted 5¼&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Apple_DOS32 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Apple_DOS32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Apple DOS 3.2 formatted 5¼&quot; double sided floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Apple_DOS32_DS {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Apple_DOS32_DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Apple DOS 3.3 formatted 5¼&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Apple_DOS33 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Apple_DOS33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Apple DOS 3.3 formatted 5¼&quot; double sided floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Apple_DOS33_DS {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Apple_DOS33_DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Apple formatted 3½&quot; double density single sided floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Apple_MF1DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Apple_MF1DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Apricot formatted 3½&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Apricot_MF2DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Apricot_MF2DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Atari formatted 5¼&quot; double density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Atari_MD1DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Atari_MD1DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Atari formatted 5¼&quot; single density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Atari_MD1SD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Atari_MD1SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is IOMEGA, media has {0} blocks of 256 bytes, setting media type to 10Mb Bernoulli Box..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Bernoulli10 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Bernoulli10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is IOMEGA, media has 294918 blocks of 512 bytes, setting media type to 150Mb Bernoulli Box II..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Bernoulli2_150 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Bernoulli2_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is IOMEGA, media has 87040 blocks of 512 bytes, setting media type to 44Mb Bernoulli Box II..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Bernoulli2_44 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Bernoulli2_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is IOMEGA, media has 175856 blocks of 512 bytes, setting media type to 90Mb Bernoulli Box II..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Bernoulli2_90 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Bernoulli2_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dlt&quot; setting media type to CompactTape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_CompactTape {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_CompactTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dlt&quot; setting media type to CompactTape II..
        /// </summary>
        internal static string SCSI_Media_Type_Description_CompactTapeII {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_CompactTapeII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dat&quot; setting media type to DAT72..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DAT72_dat {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DAT72_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to DDS..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DDS {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to DDS-2..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DDS2 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DDS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dat&quot; setting media type to DDS-2..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DDS2_dat {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DDS2_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to DDS-3..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DDS3 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DDS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dat&quot; setting media type to DDS-3..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DDS3_dat {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DDS3_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to DDS-4..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DDS4 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DDS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dat&quot; setting media type to DDS-4..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DDS4_alt {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DDS4_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to DEC RX02 floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DEC_RX02 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DEC_RX02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dlt&quot; setting media type to DLTtape III..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DLTtapeIII {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DLTtapeIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dlt&quot; setting media type to DLTtape IIIxt..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DLTtapeIIIxt {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DLTtapeIIIxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dlt&quot; setting media type to DLTtape IV..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DLTtapeIV {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DLTtapeIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Microsoft DMF formatted 3½&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_DMF_MF2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_DMF_MF2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-154 / ISO 10090 conforming 3½&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA154 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-183 / ISO 13481 conforming 5¼&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA183 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-184 / ISO 13549 conforming 5¼&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA184 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-195 / ISO 13842 conforming 5¼&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA195 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-201 / ISO 13963 conforming 3½&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA201 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-201 / ISO 13963 conforming 3½&quot; embossed magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA201_embossed {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA201_embossed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-223 conforming 3½&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA223 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-238 / ISO 15486 conforming 5¼&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA238 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-239 / ISO 15498 conforming 3½&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA239 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-260 / ISO 15898 conforming 356mm magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA260 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-280 / ISO 18093 conforming 5¼&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA280 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-317 / ISO 20162 conforming 300mm magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA317 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-322 / ISO 22092 conforming 5¼&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA322 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-54 formatted 8&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA54 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-56 formatted 5¼&quot; double density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA56 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-59 formatted 8&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA59 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-66 formatted 5¼&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA66 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-69 formatted 8&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA69 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-70 formatted 5¼&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA70 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-78 formatted 5¼&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA78 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ECMA-99 formatted 5¼&quot; floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ECMA99 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ECMA99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 106m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_106m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_106m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 112m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_112m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_112m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 125m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_125m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_125m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 150m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_150m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_150m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 15m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_15m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_15m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 160m Exatape XL..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_160m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_160m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 170m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_170m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_170m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 225m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_225m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_225m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 22m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_22m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_22m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 22m Exatape AME..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_22m_AME {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_22m_AME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 28m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_28m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_28m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 40m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_40m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_40m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 45m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_45m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_45m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 54m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_54m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_54m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 75m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_75m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_75m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 76m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_76m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_76m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;exb&quot; setting media type to 80m Exatape..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Exatape_80m {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Exatape_80m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is SyQuest, media has 262144 blocks of 512 bytes, setting media type to EZ135..
        /// </summary>
        internal static string SCSI_Media_Type_Description_EZ135 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_EZ135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is SyQuest, media has 450560 blocks of 512 bytes, setting media type to EZ230..
        /// </summary>
        internal static string SCSI_Media_Type_Description_EZ230 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_EZ230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive model is LS (SuperDisk), media has 65536 blocks of 512 bytes, setting media type to FD32MB..
        /// </summary>
        internal static string SCSI_Media_Type_Description_FD32MB {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_FD32MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to FDFORMAT formatted 5¼&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_FDFORMAT_MD2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_FDFORMAT_MD2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to FDFORMAT formatted 3½&quot; double density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_FDFORMAT_MF2DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_FDFORMAT_MF2DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to FDFORMAT formatted 3½&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_FDFORMAT_MF2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_FDFORMAT_MF2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Floptical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Floptical {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Floptical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to GigaMO 3½&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_GigaMO {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_GigaMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to GigaMO 2 3½&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_GigaMO2 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_GigaMO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media has 46956 blocks of 256 bytes, setting media type to 12Mb HyperFlex..
        /// </summary>
        internal static string SCSI_Media_Type_Description_HF12 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_HF12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media has 78936 blocks of 256 bytes, setting media type to 24Mb HyperFlex..
        /// </summary>
        internal static string SCSI_Media_Type_Description_HF24 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_HF24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive model is HiFD, media has 393380 blocks of 512 bytes, setting media type to HiFD..
        /// </summary>
        internal static string SCSI_Media_Type_Description_HiFD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_HiFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Sony HiMD..
        /// </summary>
        internal static string SCSI_Media_Type_Description_HiMD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_HiMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 8&quot; (23FD) floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_23FD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_23FD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 8&quot; (33FD) floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_33FD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_33FD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 8&quot; (43FD) floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_43FD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_43FD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 8&quot; (53FD) floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_53FD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_53FD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 5¼&quot; double density single sided floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MD1DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MD1DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 5¼&quot; double density single sided floppy (8 sectors)..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MD1DD_8 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MD1DD_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 5¼&quot; double density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MD2DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MD2DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 5¼&quot; double density floppy (8 sectors)..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MD2DD_8 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MD2DD_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 5¼&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MD2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MD2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 3½&quot; double density single sided floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MF1DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MF1DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 3½&quot; double density single sided floppy (8 sectors)..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MF1DD_8 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MF1DD_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 3½&quot; double density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MF2DD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MF2DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 3½&quot; double density floppy (8 sectors)..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MF2DD_8 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MF2DD_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 3½&quot; extra density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MF2ED {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MF2ED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to IBM formatted 3½&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM_MF2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM_MF2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to IBM 3490..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM3490 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM3490", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to IBM 3490E..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM3490E {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM3490E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is IBM, setting media type to IBM 3592..
        /// </summary>
        internal static string SCSI_Media_Type_Description_IBM3592 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_IBM3592", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ISO 10089 conforming 5¼&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ISO10089 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ISO10089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ISO 14517 conforming 5¼&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ISO14517 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ISO14517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ISO 15041 conforming 3½&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ISO15041 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ISO15041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to ISO 15286 conforming 5¼&quot; magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ISO15286 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ISO15286", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is IOMEGA, drive model is JAZ, media has 2091050 blocks of 512 bytes, setting media type to 1Gb JAZ..
        /// </summary>
        internal static string SCSI_Media_Type_Description_JAZ {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_JAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is IOMEGA, drive model is JAZ, media has 3915600 blocks of 512 bytes, setting media type to 2Gb JAZ..
        /// </summary>
        internal static string SCSI_Media_Type_Description_JAZ2 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_JAZ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive model is LS (SuperDisk), media has 2880 blocks of 512 bytes, setting media type to PC-98 formatted 3½&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LS_PC98_MF2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LS_PC98_MF2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive model is LS (SuperDisk), media has 246528 blocks of 512 bytes, setting media type to LS-120..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LS120 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LS120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive model is LS (SuperDisk), media has 469504 blocks of 512 bytes, setting media type to LS-240..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LS240 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LS240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to LTO..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LTO {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to LTO..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LTO_ult {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LTO_ult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to LTO-2..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LTO2 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LTO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to LTO-2..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LTO2_ult {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LTO2_ult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to LTO-3..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LTO3 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LTO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to LTO-4..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LTO4 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LTO4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to LTO-5..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LTO5 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LTO5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to LTO-6..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LTO6_ult {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LTO6_ult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to LTO-7..
        /// </summary>
        internal static string SCSI_Media_Type_Description_LTO7_ult {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_LTO7_ult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to 60 minute MiniDisc..
        /// </summary>
        internal static string SCSI_Media_Type_Description_MD60 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_MD60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI peripheral type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to 60 minute MiniDisc..
        /// </summary>
        internal static string SCSI_Media_Type_Description_MD60_MDDATA {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_MD60_MDDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to 74 minute MiniDisc..
        /// </summary>
        internal static string SCSI_Media_Type_Description_MD74 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_MD74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI peripheral type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to 74 minute MiniDisc..
        /// </summary>
        internal static string SCSI_Media_Type_Description_MD74_MDDATA {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_MD74_MDDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to 80 minute MiniDisc..
        /// </summary>
        internal static string SCSI_Media_Type_Description_MD80 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_MD80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI peripheral type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to 80 minute MiniDisc..
        /// </summary>
        internal static string SCSI_Media_Type_Description_MD80_MDDATA {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_MD80_MDDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI peripheral type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to MiniDisc for Data..
        /// </summary>
        internal static string SCSI_Media_Type_Description_MDDATA {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_MDDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to MetaFloppy formatted 5¼&quot; double density single sided floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_MetaFloppy {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_MetaFloppy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive model is Castlewood Orb, media has 4307184 blocks of 512 bytes, setting media type to Orb..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Orb {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Orb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to PC-98 formatted 5¼&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_PC98_MD2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_PC98_MD2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to PC-98 formatted 3½&quot; high density floppy (15 sectors)..
        /// </summary>
        internal static string SCSI_Media_Type_Description_PC98_MF2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_PC98_MF2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is IOMEGA, media has 78882 blocks of 512 bytes, setting media type to PocketZIP..
        /// </summary>
        internal static string SCSI_Media_Type_Description_PocketZIP {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_PocketZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to QIC-11..
        /// </summary>
        internal static string SCSI_Media_Type_Description_QIC11 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_QIC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to QIC-120..
        /// </summary>
        internal static string SCSI_Media_Type_Description_QIC120 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_QIC120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to QIC-150..
        /// </summary>
        internal static string SCSI_Media_Type_Description_QIC150 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_QIC150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to QIC-24..
        /// </summary>
        internal static string SCSI_Media_Type_Description_QIC24 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_QIC24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive model is RDX, media has {0} blocks of {1} bytes, setting media type to RDX320..
        /// </summary>
        internal static string SCSI_Media_Type_Description_RDX320 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_RDX320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to 120Gb REV..
        /// </summary>
        internal static string SCSI_Media_Type_Description_REV120 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_REV120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to 35Gb REV..
        /// </summary>
        internal static string SCSI_Media_Type_Description_REV35 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_REV35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to 70Gb REV..
        /// </summary>
        internal static string SCSI_Media_Type_Description_REV70 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_REV70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;sdz&quot; setting media type to Super AIT..
        /// </summary>
        internal static string SCSI_Media_Type_Description_SAIT {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_SAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dlt&quot; setting media type to SuperDLT..
        /// </summary>
        internal static string SCSI_Media_Type_Description_SDLT {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_SDLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dlt&quot; setting media type to SuperDLT 2..
        /// </summary>
        internal static string SCSI_Media_Type_Description_SDLT2 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_SDLT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to Sharp formatted 3½&quot; high density floppy..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Sharp_MF2HD {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Sharp_MF2HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is SyQuest, media has 390696 blocks of 512 bytes, setting media type to SQ2000..
        /// </summary>
        internal static string SCSI_Media_Type_Description_SQ2000 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_SQ2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is SyQuest, media has 215440 blocks of 512 bytes, setting media type to SQ310..
        /// </summary>
        internal static string SCSI_Media_Type_Description_SQ310 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_SQ310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is SyQuest, media has 524288 blocks of 512 bytes, setting media type to SQ327..
        /// </summary>
        internal static string SCSI_Media_Type_Description_SQ327 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_SQ327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is SyQuest, media has 86700 blocks of 512 bytes, setting media type to SQ400..
        /// </summary>
        internal static string SCSI_Media_Type_Description_SQ400 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_SQ400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is SyQuest, media has 173456 blocks of 512 bytes, setting media type to SQ800..
        /// </summary>
        internal static string SCSI_Media_Type_Description_SQ800 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_SQ800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is SyQuest, media has 2929800 blocks of 512 bytes, setting media type to SyJet..
        /// </summary>
        internal static string SCSI_Media_Type_Description_SyJet {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_SyJet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is StorageTek, setting media type to T10000A..
        /// </summary>
        internal static string SCSI_Media_Type_Description_T10000A {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_T10000A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is StorageTek, setting media type to T10000B..
        /// </summary>
        internal static string SCSI_Media_Type_Description_T10000B {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_T10000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is StorageTek, setting media type to T10000C..
        /// </summary>
        internal static string SCSI_Media_Type_Description_T10000C {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_T10000C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is StorageTek, setting media type to T10000D..
        /// </summary>
        internal static string SCSI_Media_Type_Description_T10000D {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_T10000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is StorageTek, setting media type to T9840A..
        /// </summary>
        internal static string SCSI_Media_Type_Description_T9840A {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_T9840A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is StorageTek, setting media type to T9840D..
        /// </summary>
        internal static string SCSI_Media_Type_Description_T9840D {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_T9840D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is StorageTek, setting media type to T9940A..
        /// </summary>
        internal static string SCSI_Media_Type_Description_T9940A {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_T9940A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is StorageTek, setting media type to T9940B..
        /// </summary>
        internal static string SCSI_Media_Type_Description_T9940B {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_T9940B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive manufacturer is StorageTek, setting media type to T9840C..
        /// </summary>
        internal static string SCSI_Media_Type_Description_T9940C {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_T9940C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to Travan 4..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Travan4 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Travan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, setting media type to Travan 5..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Travan5 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Travan5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;stt&quot; setting media type to Travan 5..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Travan5_stt {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Travan5_stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;stt&quot; setting media type to Travan 7..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Travan7 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Travan7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to UDO..
        /// </summary>
        internal static string SCSI_Media_Type_Description_UDO {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_UDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to UDO2..
        /// </summary>
        internal static string SCSI_Media_Type_Description_UDO2 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_UDO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to unknown..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Unknown {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to unknown magneto-optical..
        /// </summary>
        internal static string SCSI_Media_Type_Description_Unknown_MO {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_Unknown_MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;dlt&quot; setting media type to VStape I..
        /// </summary>
        internal static string SCSI_Media_Type_Description_VStape {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_VStape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;vxa&quot; setting media type to VXA..
        /// </summary>
        internal static string SCSI_Media_Type_Description_VXA {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_VXA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;vxa&quot; setting media type to VXA 2..
        /// </summary>
        internal static string SCSI_Media_Type_Description_VXA2 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_VXA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;vxa&quot; setting media type to VXA 3..
        /// </summary>
        internal static string SCSI_Media_Type_Description_VXA3 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_VXA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to WORM LTO-3..
        /// </summary>
        internal static string SCSI_Media_Type_Description_WORM_LTO3 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_WORM_LTO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to WORM LTO-4..
        /// </summary>
        internal static string SCSI_Media_Type_Description_WORM_LTO4 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_WORM_LTO4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to WORM LTO-5..
        /// </summary>
        internal static string SCSI_Media_Type_Description_WORM_LTO5 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_WORM_LTO5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to WORM LTO-6..
        /// </summary>
        internal static string SCSI_Media_Type_Description_WORM_LTO6_ult {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_WORM_LTO6_ult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive model starts with &quot;ult&quot; setting media type to WORM LTO-7..
        /// </summary>
        internal static string SCSI_Media_Type_Description_WORM_LTO7_ult {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_WORM_LTO7_ult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to WORM UDO2..
        /// </summary>
        internal static string SCSI_Media_Type_Description_WORM_UDO2 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_WORM_UDO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI peripheral type is {0:X2}h, setting media type to host managed zoned block device..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ZBC_Host_Managed {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ZBC_Host_Managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is IOMEGA, drive model is ZIP, media has 196608 blocks of 512 bytes, setting media type to 100Mb ZIP..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ZIP100 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ZIP100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive manufacturer is IOMEGA, drive model is ZIP, media has 489532 blocks of 512 bytes, setting media type to 250Mb ZIP..
        /// </summary>
        internal static string SCSI_Media_Type_Description_ZIP250 {
            get {
                return ResourceManager.GetString("SCSI_Media_Type_Description_ZIP250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h and device is USB, setting media type to Flash Drive..
        /// </summary>
        internal static string SCSI_medium_type_is_0_and_device_is_USB_setting_media_type_to_Flash_Drive {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_and_device_is_USB_setting_media_type_to_Flash_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive starts with &quot;ult&quot;, setting media type to LTO-2..
        /// </summary>
        internal static string SCSI_medium_type_is_0_density_code_is_1_drive_starts_with_ult_setting_media_type_to_LTO2 {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_density_code_is_1_drive_starts_with_ult_setting_media_type_" +
                        "to_LTO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive starts with &quot;ult&quot;, setting media type to LTO-3..
        /// </summary>
        internal static string SCSI_medium_type_is_0_density_code_is_1_drive_starts_with_ult_setting_media_type_to_LTO3 {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_density_code_is_1_drive_starts_with_ult_setting_media_type_" +
                        "to_LTO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive starts with &quot;ult&quot;, setting media type to LTO-4..
        /// </summary>
        internal static string SCSI_medium_type_is_0_density_code_is_1_drive_starts_with_ult_setting_media_type_to_LTO4 {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_density_code_is_1_drive_starts_with_ult_setting_media_type_" +
                        "to_LTO4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, density code is {1:X2}h, drive starts with &quot;ult&quot;, setting media type to LTO-5..
        /// </summary>
        internal static string SCSI_medium_type_is_0_density_code_is_1_drive_starts_with_ult_setting_media_type_to_LTO5 {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_density_code_is_1_drive_starts_with_ult_setting_media_type_" +
                        "to_LTO5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to PD-650..
        /// </summary>
        internal static string SCSI_medium_type_is_0_media_has_1_blocks_of_2_bytes_setting_media_type_to_PD_650 {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_media_has_1_blocks_of_2_bytes_setting_media_type_to_PD_650", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, media has {1} blocks of {2} bytes, setting media type to WORM PD-650..
        /// </summary>
        internal static string SCSI_medium_type_is_0_media_has_1_blocks_of_2_bytes_setting_media_type_to_WORM_PD_650 {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_media_has_1_blocks_of_2_bytes_setting_media_type_to_WORM_PD" +
                        "_650", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, setting media type to CD+..
        /// </summary>
        internal static string SCSI_medium_type_is_0_setting_media_type_to_CD_Plus {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_setting_media_type_to_CD_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, setting media type to CD-ROM..
        /// </summary>
        internal static string SCSI_medium_type_is_0_setting_media_type_to_CD_ROM {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_setting_media_type_to_CD_ROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, setting media type to CD-R..
        /// </summary>
        internal static string SCSI_medium_type_is_0_setting_media_type_to_CDR {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_setting_media_type_to_CDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, setting media type to CD-RW..
        /// </summary>
        internal static string SCSI_medium_type_is_0_setting_media_type_to_CDRW {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_setting_media_type_to_CDRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, setting media type to Compact Disc..
        /// </summary>
        internal static string SCSI_medium_type_is_0_setting_media_type_to_Compact_Disc {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_setting_media_type_to_Compact_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, setting media type to Compact Disc Digital Audio..
        /// </summary>
        internal static string SCSI_medium_type_is_0_setting_media_type_to_Compact_Disc_Digital_Audio {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_setting_media_type_to_Compact_Disc_Digital_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, setting media type to Photo CD..
        /// </summary>
        internal static string SCSI_medium_type_is_0_setting_media_type_to_Photo_CD {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_setting_media_type_to_Photo_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI medium type is {0:X2}h, setting media type to unknown magneto-optical..
        /// </summary>
        internal static string SCSI_medium_type_is_0_setting_media_type_to_unknown_magneto_optical {
            get {
                return ResourceManager.GetString("SCSI_medium_type_is_0_setting_media_type_to_unknown_magneto_optical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception calling uname: {0}.
        /// </summary>
        internal static string Unhandled_exception_calling_uname_0 {
            get {
                return ResourceManager.GetString("Unhandled_exception_calling_uname_0", resourceCulture);
            }
        }
    }
}
