//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.Checksums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aaru.Checksums.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adler-32.
        /// </summary>
        internal static string Adler32_Name {
            get {
                return ResourceManager.GetString("Adler32_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion failed.
        /// </summary>
        internal static string Assertion_failed {
            get {
                return ResourceManager.GetString("Assertion_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD-Text Pack 4 CRC 0x{0:X4}, expected 0x{1:X4}.
        /// </summary>
        internal static string CD_Text_Pack_four_CRC_0_expected_1 {
            get {
                return ResourceManager.GetString("CD_Text_Pack_four_CRC_0_expected_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD-Text Pack 1 CRC 0x{0:X4}, expected 0x{1:X4}.
        /// </summary>
        internal static string CD_Text_Pack_one_CRC_0_expected_1 {
            get {
                return ResourceManager.GetString("CD_Text_Pack_one_CRC_0_expected_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD-Text Pack 3 CRC 0x{0:X4}, expected 0x{1:X4}.
        /// </summary>
        internal static string CD_Text_Pack_three_CRC_0_expected_1 {
            get {
                return ResourceManager.GetString("CD_Text_Pack_three_CRC_0_expected_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD-Text Pack 2 CRC 0x{0:X4}, expected 0x{1:X4}.
        /// </summary>
        internal static string CD_Text_Pack_two_CRC_0_expected_1 {
            get {
                return ResourceManager.GetString("CD_Text_Pack_two_CRC_0_expected_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC-16 (CCITT).
        /// </summary>
        internal static string CRC16_CCITT_Name {
            get {
                return ResourceManager.GetString("CRC16_CCITT_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC-16 (IBM).
        /// </summary>
        internal static string CRC16_IBM_Name {
            get {
                return ResourceManager.GetString("CRC16_IBM_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC-32.
        /// </summary>
        internal static string CRC32_Name {
            get {
                return ResourceManager.GetString("CRC32_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC-64 (ECMA).
        /// </summary>
        internal static string CRC64_ECMA_Name {
            get {
                return ResourceManager.GetString("CRC64_ECMA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic CDTP2 0x{0:X4}, Calc CDTP2 0x{1:X4}.
        /// </summary>
        internal static string Cyclic_CDTP2_0_Calc_CDTP2_1 {
            get {
                return ResourceManager.GetString("Cyclic_CDTP2_0_Calc_CDTP2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic CDTP3 0x{0:X4}, Calc CDTP3 0x{1:X4}.
        /// </summary>
        internal static string Cyclic_CDTP3_0_Calc_CDTP3_1 {
            get {
                return ResourceManager.GetString("Cyclic_CDTP3_0_Calc_CDTP3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic CDTP4 0x{0:X4}, Calc CDTP4 0x{1:X4}.
        /// </summary>
        internal static string Cyclic_CDTP4_0_Calc_CDTP4_1 {
            get {
                return ResourceManager.GetString("Cyclic_CDTP4_0_Calc_CDTP4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected CD+EG Pack in subchannel.
        /// </summary>
        internal static string Detected_CD_EG_Pack_in_subchannel {
            get {
                return ResourceManager.GetString("Detected_CD_EG_Pack_in_subchannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected CD+G Pack in subchannel.
        /// </summary>
        internal static string Detected_CD_G_Pack_in_subchannel {
            get {
                return ResourceManager.GetString("Detected_CD_G_Pack_in_subchannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected CD+MIDI Pack in subchannel.
        /// </summary>
        internal static string Detected_CD_MIDI_Pack_in_subchannel {
            get {
                return ResourceManager.GetString("Detected_CD_MIDI_Pack_in_subchannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected CD-TEXT Pack in subchannel.
        /// </summary>
        internal static string Detected_CD_TEXT_Pack_in_subchannel {
            get {
                return ResourceManager.GetString("Detected_CD_TEXT_Pack_in_subchannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Line Graphics Pack in subchannel.
        /// </summary>
        internal static string Detected_Line_Graphics_Pack_in_subchannel {
            get {
                return ResourceManager.GetString("Detected_Line_Graphics_Pack_in_subchannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected unknown Pack type in subchannel: mode {0}, item {1}.
        /// </summary>
        internal static string Detected_unknown_Pack_type_in_subchannel_mode_0_item_1 {
            get {
                return ResourceManager.GetString("Detected_unknown_Pack_type_in_subchannel_mode_0_item_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected User Pack in subchannel.
        /// </summary>
        internal static string Detected_User_Pack_in_subchannel {
            get {
                return ResourceManager.GetString("Detected_User_Pack_in_subchannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Zero Pack in subchannel.
        /// </summary>
        internal static string Detected_Zero_Pack_in_subchannel {
            get {
                return ResourceManager.GetString("Detected_Zero_Pack_in_subchannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// Erasure positions as determined by roots of Eras Loc Poly:
        ///.
        /// </summary>
        internal static string Erasure_positions_as_determined_by_roots_of_Eras_Loc_Poly {
            get {
                return ResourceManager.GetString("Erasure_positions_as_determined_by_roots_of_Eras_Loc_Poly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// ERROR: denominator = 0
        ///.
        /// </summary>
        internal static string ERROR_denominator_equals_zero {
            get {
                return ResourceManager.GetString("ERROR_denominator_equals_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// Final error positions:	.
        /// </summary>
        internal static string Final_error_positions {
            get {
                return ResourceManager.GetString("Final_error_positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fletcher-16.
        /// </summary>
        internal static string Fletcher16_Name {
            get {
                return ResourceManager.GetString("Fletcher16_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fletcher-32.
        /// </summary>
        internal static string Fletcher32_Name {
            get {
                return ResourceManager.GetString("Fletcher32_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// lambda(x) is WRONG
        ///.
        /// </summary>
        internal static string lambda_is_wrong {
            get {
                return ResourceManager.GetString("lambda_is_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m must be between 2 and 16 inclusive.
        /// </summary>
        internal static string m_must_be_between_2_and_16_inclusive {
            get {
                return ResourceManager.GetString("m_must_be_between_2_and_16_inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5.
        /// </summary>
        internal static string MD5_Name {
            get {
                return ResourceManager.GetString("MD5_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented..
        /// </summary>
        internal static string Not_yet_implemented {
            get {
                return ResourceManager.GetString("Not_yet_implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q subchannel CRC 0x{0:X4}, expected 0x{1:X4}.
        /// </summary>
        internal static string Q_subchannel_CRC_0_expected_1 {
            get {
                return ResourceManager.GetString("Q_subchannel_CRC_0_expected_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1.
        /// </summary>
        internal static string SHA1_Name {
            get {
                return ResourceManager.GetString("SHA1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA256.
        /// </summary>
        internal static string SHA256_Name {
            get {
                return ResourceManager.GetString("SHA256_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA384.
        /// </summary>
        internal static string SHA384_Name {
            get {
                return ResourceManager.GetString("SHA384_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA512.
        /// </summary>
        internal static string SHA512_Name {
            get {
                return ResourceManager.GetString("SHA512_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpamSum does not have a binary representation..
        /// </summary>
        internal static string SpamSum_does_not_have_a_binary_representation {
            get {
                return ResourceManager.GetString("SpamSum_does_not_have_a_binary_representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpamSum.
        /// </summary>
        internal static string SpamSum_Name {
            get {
                return ResourceManager.GetString("SpamSum_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input exceeds data types..
        /// </summary>
        internal static string The_input_exceeds_data_types {
            get {
                return ResourceManager.GetString("The_input_exceeds_data_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to calculate RS without initializing!.
        /// </summary>
        internal static string Trying_to_calculate_RS_without_initializing {
            get {
                return ResourceManager.GetString("Trying_to_calculate_RS_without_initializing", resourceCulture);
            }
        }
    }
}
