//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.Partitions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aaru.Partitions.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Acorn_Name {
            get {
                return ResourceManager.GetString("Acorn_Name", resourceCulture);
            }
        }
        
        internal static string AppleMap_Name {
            get {
                return ResourceManager.GetString("AppleMap_Name", resourceCulture);
            }
        }
        
        internal static string Found_misaligned_entry {
            get {
                return ResourceManager.GetString("Found_misaligned_entry", resourceCulture);
            }
        }
        
        internal static string Found_aligned_entry {
            get {
                return ResourceManager.GetString("Found_aligned_entry", resourceCulture);
            }
        }
        
        internal static string Partition_flags {
            get {
                return ResourceManager.GetString("Partition_flags", resourceCulture);
            }
        }
        
        internal static string Partition_is_valid {
            get {
                return ResourceManager.GetString("Partition_is_valid", resourceCulture);
            }
        }
        
        internal static string Partition_entry_is_allocated {
            get {
                return ResourceManager.GetString("Partition_entry_is_allocated", resourceCulture);
            }
        }
        
        internal static string Partition_is_in_use {
            get {
                return ResourceManager.GetString("Partition_is_in_use", resourceCulture);
            }
        }
        
        internal static string Partition_is_bootable {
            get {
                return ResourceManager.GetString("Partition_is_bootable", resourceCulture);
            }
        }
        
        internal static string Partition_is_readable {
            get {
                return ResourceManager.GetString("Partition_is_readable", resourceCulture);
            }
        }
        
        internal static string Partition_is_writable {
            get {
                return ResourceManager.GetString("Partition_is_writable", resourceCulture);
            }
        }
        
        internal static string First_boot_sector_0 {
            get {
                return ResourceManager.GetString("First_boot_sector_0", resourceCulture);
            }
        }
        
        internal static string Boot_is_0_bytes {
            get {
                return ResourceManager.GetString("Boot_is_0_bytes", resourceCulture);
            }
        }
        
        internal static string Boot_load_address_0_X8 {
            get {
                return ResourceManager.GetString("Boot_load_address_0_X8", resourceCulture);
            }
        }
        
        internal static string Boot_entry_point_0_X8 {
            get {
                return ResourceManager.GetString("Boot_entry_point_0_X8", resourceCulture);
            }
        }
        
        internal static string Boot_code_checksum_0_X8 {
            get {
                return ResourceManager.GetString("Boot_code_checksum_0_X8", resourceCulture);
            }
        }
        
        internal static string Processor_0 {
            get {
                return ResourceManager.GetString("Processor_0", resourceCulture);
            }
        }
        
        internal static string Partition_boot_code_is_position_independent {
            get {
                return ResourceManager.GetString("Partition_boot_code_is_position_independent", resourceCulture);
            }
        }
        
        internal static string Cutting_last_partition_end_0_to_media_size_1 {
            get {
                return ResourceManager.GetString("Cutting_last_partition_end_0_to_media_size_1", resourceCulture);
            }
        }
        
        internal static string Not_adding_partition_because_start_0_is_outside_media_size_1 {
            get {
                return ResourceManager.GetString("Not_adding_partition_because_start_0_is_outside_media_size_1", resourceCulture);
            }
        }
        
        internal static string Apricot_Name {
            get {
                return ResourceManager.GetString("Apricot_Name", resourceCulture);
            }
        }
        
        internal static string Non_bootable {
            get {
                return ResourceManager.GetString("Non_bootable", resourceCulture);
            }
        }
        
        internal static string Apricot_XI_RAM_BIOS {
            get {
                return ResourceManager.GetString("Apricot_XI_RAM_BIOS", resourceCulture);
            }
        }
        
        internal static string Generic_ROM_BIOS {
            get {
                return ResourceManager.GetString("Generic_ROM_BIOS", resourceCulture);
            }
        }
        
        internal static string Apricot_XI_ROM_BIOS {
            get {
                return ResourceManager.GetString("Apricot_XI_ROM_BIOS", resourceCulture);
            }
        }
        
        internal static string Apricot_Portable_ROM_BIOS {
            get {
                return ResourceManager.GetString("Apricot_Portable_ROM_BIOS", resourceCulture);
            }
        }
        
        internal static string Apricot_F1_ROM_BIOS {
            get {
                return ResourceManager.GetString("Apricot_F1_ROM_BIOS", resourceCulture);
            }
        }
        
        internal static string MF1DD_70_track {
            get {
                return ResourceManager.GetString("MF1DD_70_track", resourceCulture);
            }
        }
        
        internal static string Invalid_operating_system {
            get {
                return ResourceManager.GetString("Invalid_operating_system", resourceCulture);
            }
        }
        
        internal static string None_parity {
            get {
                return ResourceManager.GetString("None_parity", resourceCulture);
            }
        }
        
        internal static string Odd_parity {
            get {
                return ResourceManager.GetString("Odd_parity", resourceCulture);
            }
        }
        
        internal static string Even_parity {
            get {
                return ResourceManager.GetString("Even_parity", resourceCulture);
            }
        }
        
        internal static string Mark_parity {
            get {
                return ResourceManager.GetString("Mark_parity", resourceCulture);
            }
        }
        
        internal static string Space_parity {
            get {
                return ResourceManager.GetString("Space_parity", resourceCulture);
            }
        }
        
        internal static string Parallel_print_device {
            get {
                return ResourceManager.GetString("Parallel_print_device", resourceCulture);
            }
        }
        
        internal static string Serial_print_device {
            get {
                return ResourceManager.GetString("Serial_print_device", resourceCulture);
            }
        }
        
        internal static string Unknown_operating_system {
            get {
                return ResourceManager.GetString("Unknown_operating_system", resourceCulture);
            }
        }
        
        internal static string Unknown_boot_type {
            get {
                return ResourceManager.GetString("Unknown_boot_type", resourceCulture);
            }
        }
        
        internal static string Unknown_disk_type {
            get {
                return ResourceManager.GetString("Unknown_disk_type", resourceCulture);
            }
        }
        
        internal static string Unknown_print_device {
            get {
                return ResourceManager.GetString("Unknown_print_device", resourceCulture);
            }
        }
        
        internal static string Unknown_parity_type {
            get {
                return ResourceManager.GetString("Unknown_parity_type", resourceCulture);
            }
        }
        
        internal static string AtariPartitions_Name {
            get {
                return ResourceManager.GetString("AtariPartitions_Name", resourceCulture);
            }
        }
        
        internal static string Boot_code_SHA1_0 {
            get {
                return ResourceManager.GetString("Boot_code_SHA1_0", resourceCulture);
            }
        }
        
        internal static string WARNING_End_of_partition_goes_beyond_device_size {
            get {
                return ResourceManager.GetString("WARNING_End_of_partition_goes_beyond_device_size", resourceCulture);
            }
        }
        
        internal static string Atari_GEMDOS_partition {
            get {
                return ResourceManager.GetString("Atari_GEMDOS_partition", resourceCulture);
            }
        }
        
        internal static string Atari_GEMDOS_partition_bigger_than_32_MiB {
            get {
                return ResourceManager.GetString("Atari_GEMDOS_partition_bigger_than_32_MiB", resourceCulture);
            }
        }
        
        internal static string Linux_partition {
            get {
                return ResourceManager.GetString("Linux_partition", resourceCulture);
            }
        }
        
        internal static string Swap_partition {
            get {
                return ResourceManager.GetString("Swap_partition", resourceCulture);
            }
        }
        
        internal static string RAW_partition {
            get {
                return ResourceManager.GetString("RAW_partition", resourceCulture);
            }
        }
        
        internal static string NetBSD_partition {
            get {
                return ResourceManager.GetString("NetBSD_partition", resourceCulture);
            }
        }
        
        internal static string NetBSD_swap_partition {
            get {
                return ResourceManager.GetString("NetBSD_swap_partition", resourceCulture);
            }
        }
        
        internal static string Atari_UNIX_partition {
            get {
                return ResourceManager.GetString("Atari_UNIX_partition", resourceCulture);
            }
        }
        
        internal static string Macintosh_partition {
            get {
                return ResourceManager.GetString("Macintosh_partition", resourceCulture);
            }
        }
        
        internal static string MINIX_partition {
            get {
                return ResourceManager.GetString("MINIX_partition", resourceCulture);
            }
        }
        
        internal static string Unknown_partition_type {
            get {
                return ResourceManager.GetString("Unknown_partition_type", resourceCulture);
            }
        }
        
        internal static string BSD_Name {
            get {
                return ResourceManager.GetString("BSD_Name", resourceCulture);
            }
        }
        
        internal static string BSD_GetInformation_dl_magic_on_sector_0_at_offset_1_equals_2_X8_expected_3_X8 {
            get {
                return ResourceManager.GetString("BSD_GetInformation_dl_magic_on_sector_0_at_offset_1_equals_2_X8_expected_3_X8", resourceCulture);
            }
        }
        
        internal static string BSD_GetInformation_Adding_it {
            get {
                return ResourceManager.GetString("BSD_GetInformation_Adding_it", resourceCulture);
            }
        }
        
        internal static string Unused_entry {
            get {
                return ResourceManager.GetString("Unused_entry", resourceCulture);
            }
        }
        
        internal static string UNIX_6th_Edition {
            get {
                return ResourceManager.GetString("UNIX_6th_Edition", resourceCulture);
            }
        }
        
        internal static string UNIX_7th_Edition {
            get {
                return ResourceManager.GetString("UNIX_7th_Edition", resourceCulture);
            }
        }
        
        internal static string UNIX_System_V {
            get {
                return ResourceManager.GetString("UNIX_System_V", resourceCulture);
            }
        }
        
        internal static string UNIX_7th_Edition_with_1K_blocks {
            get {
                return ResourceManager.GetString("UNIX_7th_Edition_with_1K_blocks", resourceCulture);
            }
        }
        
        internal static string UNIX_8th_Edition_with_4K_blocks {
            get {
                return ResourceManager.GetString("UNIX_8th_Edition_with_4K_blocks", resourceCulture);
            }
        }
        
        internal static string _4_2_BSD_Fast_File_System {
            get {
                return ResourceManager.GetString("_4_2_BSD_Fast_File_System", resourceCulture);
            }
        }
        
        internal static string _4_4_LFS {
            get {
                return ResourceManager.GetString("_4_4_LFS", resourceCulture);
            }
        }
        
        internal static string HPFS {
            get {
                return ResourceManager.GetString("HPFS", resourceCulture);
            }
        }
        
        internal static string ISO9660 {
            get {
                return ResourceManager.GetString("ISO9660", resourceCulture);
            }
        }
        
        internal static string Boot {
            get {
                return ResourceManager.GetString("Boot", resourceCulture);
            }
        }
        
        internal static string Amiga_FFS {
            get {
                return ResourceManager.GetString("Amiga_FFS", resourceCulture);
            }
        }
        
        internal static string Apple_HFS {
            get {
                return ResourceManager.GetString("Apple_HFS", resourceCulture);
            }
        }
        
        internal static string Digital_Advanced_File_System {
            get {
                return ResourceManager.GetString("Digital_Advanced_File_System", resourceCulture);
            }
        }
        
        internal static string Digital_LSM_Public_Region {
            get {
                return ResourceManager.GetString("Digital_LSM_Public_Region", resourceCulture);
            }
        }
        
        internal static string Digital_LSM_Private_Region {
            get {
                return ResourceManager.GetString("Digital_LSM_Private_Region", resourceCulture);
            }
        }
        
        internal static string Digital_LSM_Simple_Disk {
            get {
                return ResourceManager.GetString("Digital_LSM_Simple_Disk", resourceCulture);
            }
        }
        
        internal static string Concatenated_disk {
            get {
                return ResourceManager.GetString("Concatenated_disk", resourceCulture);
            }
        }
        
        internal static string IBM_JFS2 {
            get {
                return ResourceManager.GetString("IBM_JFS2", resourceCulture);
            }
        }
        
        internal static string Hammer {
            get {
                return ResourceManager.GetString("Hammer", resourceCulture);
            }
        }
        
        internal static string Hammer2 {
            get {
                return ResourceManager.GetString("Hammer2", resourceCulture);
            }
        }
        
        internal static string UDF {
            get {
                return ResourceManager.GetString("UDF", resourceCulture);
            }
        }
        
        internal static string EFS {
            get {
                return ResourceManager.GetString("EFS", resourceCulture);
            }
        }
        
        internal static string ZFS {
            get {
                return ResourceManager.GetString("ZFS", resourceCulture);
            }
        }
        
        internal static string FreeBSD_nandfs {
            get {
                return ResourceManager.GetString("FreeBSD_nandfs", resourceCulture);
            }
        }
        
        internal static string FAT {
            get {
                return ResourceManager.GetString("FAT", resourceCulture);
            }
        }
        
        internal static string Other_or_unknown {
            get {
                return ResourceManager.GetString("Other_or_unknown", resourceCulture);
            }
        }
        
        internal static string DEC_Name {
            get {
                return ResourceManager.GetString("DEC_Name", resourceCulture);
            }
        }
        
        internal static string DragonFlyBSD_Name {
            get {
                return ResourceManager.GetString("DragonFlyBSD_Name", resourceCulture);
            }
        }
        
        internal static string GuidPartitionTable_Name {
            get {
                return ResourceManager.GetString("GuidPartitionTable_Name", resourceCulture);
            }
        }
        
        internal static string Found_unaligned_signature {
            get {
                return ResourceManager.GetString("Found_unaligned_signature", resourceCulture);
            }
        }
        
        internal static string MBR_scheme {
            get {
                return ResourceManager.GetString("MBR_scheme", resourceCulture);
            }
        }
        
        internal static string EFI_System {
            get {
                return ResourceManager.GetString("EFI_System", resourceCulture);
            }
        }
        
        internal static string BIOS_Boot {
            get {
                return ResourceManager.GetString("BIOS_Boot", resourceCulture);
            }
        }
        
        internal static string Intel_Fast_Flash_iFFS {
            get {
                return ResourceManager.GetString("Intel_Fast_Flash_iFFS", resourceCulture);
            }
        }
        
        internal static string Sony_boot {
            get {
                return ResourceManager.GetString("Sony_boot", resourceCulture);
            }
        }
        
        internal static string Lenovo_boot {
            get {
                return ResourceManager.GetString("Lenovo_boot", resourceCulture);
            }
        }
        
        internal static string Microsoft_Reserved_MSR {
            get {
                return ResourceManager.GetString("Microsoft_Reserved_MSR", resourceCulture);
            }
        }
        
        internal static string Microsoft_Basic_data {
            get {
                return ResourceManager.GetString("Microsoft_Basic_data", resourceCulture);
            }
        }
        
        internal static string Logical_Disk_Manager_LDM_metadata {
            get {
                return ResourceManager.GetString("Logical_Disk_Manager_LDM_metadata", resourceCulture);
            }
        }
        
        internal static string Logical_Disk_Manager_data {
            get {
                return ResourceManager.GetString("Logical_Disk_Manager_data", resourceCulture);
            }
        }
        
        internal static string Windows_Recovery_Environment {
            get {
                return ResourceManager.GetString("Windows_Recovery_Environment", resourceCulture);
            }
        }
        
        internal static string IBM_General_Parallel_File_System_GPFS {
            get {
                return ResourceManager.GetString("IBM_General_Parallel_File_System_GPFS", resourceCulture);
            }
        }
        
        internal static string Windows_Storage_Spaces {
            get {
                return ResourceManager.GetString("Windows_Storage_Spaces", resourceCulture);
            }
        }
        
        internal static string HP_UX_Data {
            get {
                return ResourceManager.GetString("HP_UX_Data", resourceCulture);
            }
        }
        
        internal static string HP_UX_Service {
            get {
                return ResourceManager.GetString("HP_UX_Service", resourceCulture);
            }
        }
        
        internal static string Linux_filesystem {
            get {
                return ResourceManager.GetString("Linux_filesystem", resourceCulture);
            }
        }
        
        internal static string Linux_RAID {
            get {
                return ResourceManager.GetString("Linux_RAID", resourceCulture);
            }
        }
        
        internal static string Linux_Root_x86 {
            get {
                return ResourceManager.GetString("Linux_Root_x86", resourceCulture);
            }
        }
        
        internal static string Linux_Root_x86_64 {
            get {
                return ResourceManager.GetString("Linux_Root_x86_64", resourceCulture);
            }
        }
        
        internal static string Linux_Root_32_bit_ARM {
            get {
                return ResourceManager.GetString("Linux_Root_32_bit_ARM", resourceCulture);
            }
        }
        
        internal static string Linux_Root_AArch64 {
            get {
                return ResourceManager.GetString("Linux_Root_AArch64", resourceCulture);
            }
        }
        
        internal static string Logical_Volume_Manager_LVM {
            get {
                return ResourceManager.GetString("Logical_Volume_Manager_LVM", resourceCulture);
            }
        }
        
        internal static string Linux_home {
            get {
                return ResourceManager.GetString("Linux_home", resourceCulture);
            }
        }
        
        internal static string Linux_srv {
            get {
                return ResourceManager.GetString("Linux_srv", resourceCulture);
            }
        }
        
        internal static string Plain_dm_crypt {
            get {
                return ResourceManager.GetString("Plain_dm_crypt", resourceCulture);
            }
        }
        
        internal static string LUKS {
            get {
                return ResourceManager.GetString("LUKS", resourceCulture);
            }
        }
        
        internal static string Linux_Reserved {
            get {
                return ResourceManager.GetString("Linux_Reserved", resourceCulture);
            }
        }
        
        internal static string FreeBSD_Boot {
            get {
                return ResourceManager.GetString("FreeBSD_Boot", resourceCulture);
            }
        }
        
        internal static string FreeBSD_Data {
            get {
                return ResourceManager.GetString("FreeBSD_Data", resourceCulture);
            }
        }
        
        internal static string FreeBSD_UFS {
            get {
                return ResourceManager.GetString("FreeBSD_UFS", resourceCulture);
            }
        }
        
        internal static string FreeBSD_UFS2 {
            get {
                return ResourceManager.GetString("FreeBSD_UFS2", resourceCulture);
            }
        }
        
        internal static string FreeBSD_Vinum {
            get {
                return ResourceManager.GetString("FreeBSD_Vinum", resourceCulture);
            }
        }
        
        internal static string FreeBSD_ZFS {
            get {
                return ResourceManager.GetString("FreeBSD_ZFS", resourceCulture);
            }
        }
        
        internal static string Apple_UFS {
            get {
                return ResourceManager.GetString("Apple_UFS", resourceCulture);
            }
        }
        
        internal static string Apple_RAID {
            get {
                return ResourceManager.GetString("Apple_RAID", resourceCulture);
            }
        }
        
        internal static string Apple_RAID_offline {
            get {
                return ResourceManager.GetString("Apple_RAID_offline", resourceCulture);
            }
        }
        
        internal static string Apple_Boot {
            get {
                return ResourceManager.GetString("Apple_Boot", resourceCulture);
            }
        }
        
        internal static string Apple_Label {
            get {
                return ResourceManager.GetString("Apple_Label", resourceCulture);
            }
        }
        
        internal static string Apple_TV_Recovery {
            get {
                return ResourceManager.GetString("Apple_TV_Recovery", resourceCulture);
            }
        }
        
        internal static string Apple_Core_Storage {
            get {
                return ResourceManager.GetString("Apple_Core_Storage", resourceCulture);
            }
        }
        
        internal static string Solaris_Root {
            get {
                return ResourceManager.GetString("Solaris_Root", resourceCulture);
            }
        }
        
        internal static string Solaris_Swap {
            get {
                return ResourceManager.GetString("Solaris_Swap", resourceCulture);
            }
        }
        
        internal static string Solaris_Backup {
            get {
                return ResourceManager.GetString("Solaris_Backup", resourceCulture);
            }
        }
        
        internal static string Solaris_usr_or_Apple_ZFS {
            get {
                return ResourceManager.GetString("Solaris_usr_or_Apple_ZFS", resourceCulture);
            }
        }
        
        internal static string Solaris_var {
            get {
                return ResourceManager.GetString("Solaris_var", resourceCulture);
            }
        }
        
        internal static string Solaris_home {
            get {
                return ResourceManager.GetString("Solaris_home", resourceCulture);
            }
        }
        
        internal static string Solaris_Alternate_sector {
            get {
                return ResourceManager.GetString("Solaris_Alternate_sector", resourceCulture);
            }
        }
        
        internal static string Solaris_Reserved {
            get {
                return ResourceManager.GetString("Solaris_Reserved", resourceCulture);
            }
        }
        
        internal static string NetBSD_Swap {
            get {
                return ResourceManager.GetString("NetBSD_Swap", resourceCulture);
            }
        }
        
        internal static string NetBSD_FFS {
            get {
                return ResourceManager.GetString("NetBSD_FFS", resourceCulture);
            }
        }
        
        internal static string NetBSD_LFS {
            get {
                return ResourceManager.GetString("NetBSD_LFS", resourceCulture);
            }
        }
        
        internal static string NetBSD_RAID {
            get {
                return ResourceManager.GetString("NetBSD_RAID", resourceCulture);
            }
        }
        
        internal static string NetBSD_Concatenated {
            get {
                return ResourceManager.GetString("NetBSD_Concatenated", resourceCulture);
            }
        }
        
        internal static string NetBSD_Encrypted {
            get {
                return ResourceManager.GetString("NetBSD_Encrypted", resourceCulture);
            }
        }
        
        internal static string ChromeOS_kernel {
            get {
                return ResourceManager.GetString("ChromeOS_kernel", resourceCulture);
            }
        }
        
        internal static string ChromeOS_rootfs {
            get {
                return ResourceManager.GetString("ChromeOS_rootfs", resourceCulture);
            }
        }
        
        internal static string ChromeOS_future_use {
            get {
                return ResourceManager.GetString("ChromeOS_future_use", resourceCulture);
            }
        }
        
        internal static string Haiku_BFS {
            get {
                return ResourceManager.GetString("Haiku_BFS", resourceCulture);
            }
        }
        
        internal static string MidnightBSD_Boot {
            get {
                return ResourceManager.GetString("MidnightBSD_Boot", resourceCulture);
            }
        }
        
        internal static string MidnightBSD_Data {
            get {
                return ResourceManager.GetString("MidnightBSD_Data", resourceCulture);
            }
        }
        
        internal static string MidnightBSD_Swap {
            get {
                return ResourceManager.GetString("MidnightBSD_Swap", resourceCulture);
            }
        }
        
        internal static string MidnightBSD_UFS {
            get {
                return ResourceManager.GetString("MidnightBSD_UFS", resourceCulture);
            }
        }
        
        internal static string MidnightBSD_Vinum {
            get {
                return ResourceManager.GetString("MidnightBSD_Vinum", resourceCulture);
            }
        }
        
        internal static string MidnightBSD_ZFS {
            get {
                return ResourceManager.GetString("MidnightBSD_ZFS", resourceCulture);
            }
        }
        
        internal static string Ceph_Journal {
            get {
                return ResourceManager.GetString("Ceph_Journal", resourceCulture);
            }
        }
        
        internal static string Ceph_dm_crypt_Encrypted_Journal {
            get {
                return ResourceManager.GetString("Ceph_dm_crypt_Encrypted_Journal", resourceCulture);
            }
        }
        
        internal static string Ceph_OSD {
            get {
                return ResourceManager.GetString("Ceph_OSD", resourceCulture);
            }
        }
        
        internal static string Ceph_dm_crypt_OSD {
            get {
                return ResourceManager.GetString("Ceph_dm_crypt_OSD", resourceCulture);
            }
        }
        
        internal static string Ceph_disk_in_creation {
            get {
                return ResourceManager.GetString("Ceph_disk_in_creation", resourceCulture);
            }
        }
        
        internal static string Ceph_dm_crypt_disk_in_creation {
            get {
                return ResourceManager.GetString("Ceph_dm_crypt_disk_in_creation", resourceCulture);
            }
        }
        
        internal static string OpenBSD_Data {
            get {
                return ResourceManager.GetString("OpenBSD_Data", resourceCulture);
            }
        }
        
        internal static string QNX_Power_safe_QNX6 {
            get {
                return ResourceManager.GetString("QNX_Power_safe_QNX6", resourceCulture);
            }
        }
        
        internal static string Plan_9 {
            get {
                return ResourceManager.GetString("Plan_9", resourceCulture);
            }
        }
        
        internal static string VMware_vmkcore_coredump {
            get {
                return ResourceManager.GetString("VMware_vmkcore_coredump", resourceCulture);
            }
        }
        
        internal static string VMware_VMFS {
            get {
                return ResourceManager.GetString("VMware_VMFS", resourceCulture);
            }
        }
        
        internal static string VMware_Reserved {
            get {
                return ResourceManager.GetString("VMware_Reserved", resourceCulture);
            }
        }
        
        internal static string ONIE_boot {
            get {
                return ResourceManager.GetString("ONIE_boot", resourceCulture);
            }
        }
        
        internal static string ONIE_config {
            get {
                return ResourceManager.GetString("ONIE_config", resourceCulture);
            }
        }
        
        internal static string PowerPC_PReP_boot {
            get {
                return ResourceManager.GetString("PowerPC_PReP_boot", resourceCulture);
            }
        }
        
        internal static string Acronis_Secure_Zone {
            get {
                return ResourceManager.GetString("Acronis_Secure_Zone", resourceCulture);
            }
        }
        
        internal static string Apple_File_System {
            get {
                return ResourceManager.GetString("Apple_File_System", resourceCulture);
            }
        }
        
        internal static string DragonflyBSD_Label {
            get {
                return ResourceManager.GetString("DragonflyBSD_Label", resourceCulture);
            }
        }
        
        internal static string DragonflyBSD_Swap {
            get {
                return ResourceManager.GetString("DragonflyBSD_Swap", resourceCulture);
            }
        }
        
        internal static string DragonflyBSD_UFS {
            get {
                return ResourceManager.GetString("DragonflyBSD_UFS", resourceCulture);
            }
        }
        
        internal static string DragonflyBSD_Vinum {
            get {
                return ResourceManager.GetString("DragonflyBSD_Vinum", resourceCulture);
            }
        }
        
        internal static string DragonflyBSD_CCD {
            get {
                return ResourceManager.GetString("DragonflyBSD_CCD", resourceCulture);
            }
        }
        
        internal static string DragonflyBSD_Legacy {
            get {
                return ResourceManager.GetString("DragonflyBSD_Legacy", resourceCulture);
            }
        }
        
        internal static string DragonflyBSD_Hammer {
            get {
                return ResourceManager.GetString("DragonflyBSD_Hammer", resourceCulture);
            }
        }
        
        internal static string DragonflyBSD_Hammer2 {
            get {
                return ResourceManager.GetString("DragonflyBSD_Hammer2", resourceCulture);
            }
        }
        
        internal static string Human68K_Name {
            get {
                return ResourceManager.GetString("Human68K_Name", resourceCulture);
            }
        }
        
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        internal static string FAT12 {
            get {
                return ResourceManager.GetString("FAT12", resourceCulture);
            }
        }
        
        internal static string XENIX_root {
            get {
                return ResourceManager.GetString("XENIX_root", resourceCulture);
            }
        }
        
        internal static string XENIX_usr {
            get {
                return ResourceManager.GetString("XENIX_usr", resourceCulture);
            }
        }
        
        internal static string FAT16_32_MiB {
            get {
                return ResourceManager.GetString("FAT16_32_MiB", resourceCulture);
            }
        }
        
        internal static string Extended {
            get {
                return ResourceManager.GetString("Extended", resourceCulture);
            }
        }
        
        internal static string FAT16 {
            get {
                return ResourceManager.GetString("FAT16", resourceCulture);
            }
        }
        
        internal static string IFS_HPFS_NTFS {
            get {
                return ResourceManager.GetString("IFS_HPFS_NTFS", resourceCulture);
            }
        }
        
        internal static string AIX_boot_OS2_Commodore_DOS {
            get {
                return ResourceManager.GetString("AIX_boot_OS2_Commodore_DOS", resourceCulture);
            }
        }
        
        internal static string AIX_data_Coherent_QNX {
            get {
                return ResourceManager.GetString("AIX_data_Coherent_QNX", resourceCulture);
            }
        }
        
        internal static string Coherent_swap_OPUS_OS_2_Boot_Manager {
            get {
                return ResourceManager.GetString("Coherent_swap_OPUS_OS_2_Boot_Manager", resourceCulture);
            }
        }
        
        internal static string FAT32 {
            get {
                return ResourceManager.GetString("FAT32", resourceCulture);
            }
        }
        
        internal static string FAT32_LBA {
            get {
                return ResourceManager.GetString("FAT32_LBA", resourceCulture);
            }
        }
        
        internal static string FAT16_LBA {
            get {
                return ResourceManager.GetString("FAT16_LBA", resourceCulture);
            }
        }
        
        internal static string Extended_LBA {
            get {
                return ResourceManager.GetString("Extended_LBA", resourceCulture);
            }
        }
        
        internal static string OPUS {
            get {
                return ResourceManager.GetString("OPUS", resourceCulture);
            }
        }
        
        internal static string Hidden_FAT12 {
            get {
                return ResourceManager.GetString("Hidden_FAT12", resourceCulture);
            }
        }
        
        internal static string Compaq_diagnostics_recovery_partition {
            get {
                return ResourceManager.GetString("Compaq_diagnostics_recovery_partition", resourceCulture);
            }
        }
        
        internal static string Hidden_FAT16_32_MiB_AST_DOS {
            get {
                return ResourceManager.GetString("Hidden_FAT16_32_MiB_AST_DOS", resourceCulture);
            }
        }
        
        internal static string Hidden_FAT16 {
            get {
                return ResourceManager.GetString("Hidden_FAT16", resourceCulture);
            }
        }
        
        internal static string Hidden_IFS_HPFS_NTFS {
            get {
                return ResourceManager.GetString("Hidden_IFS_HPFS_NTFS", resourceCulture);
            }
        }
        
        internal static string AST_Windows_swap {
            get {
                return ResourceManager.GetString("AST_Windows_swap", resourceCulture);
            }
        }
        
        internal static string Willowtech_Photon_coS {
            get {
                return ResourceManager.GetString("Willowtech_Photon_coS", resourceCulture);
            }
        }
        
        internal static string Hidden_FAT32 {
            get {
                return ResourceManager.GetString("Hidden_FAT32", resourceCulture);
            }
        }
        
        internal static string Hidden_FAT32_LBA {
            get {
                return ResourceManager.GetString("Hidden_FAT32_LBA", resourceCulture);
            }
        }
        
        internal static string Hidden_FAT16_LBA {
            get {
                return ResourceManager.GetString("Hidden_FAT16_LBA", resourceCulture);
            }
        }
        
        internal static string Willowsoft_Overture_File_System {
            get {
                return ResourceManager.GetString("Willowsoft_Overture_File_System", resourceCulture);
            }
        }
        
        internal static string Oxygen_FSo2 {
            get {
                return ResourceManager.GetString("Oxygen_FSo2", resourceCulture);
            }
        }
        
        internal static string Oxygen_Extended {
            get {
                return ResourceManager.GetString("Oxygen_Extended", resourceCulture);
            }
        }
        
        internal static string SpeedStor_reserved {
            get {
                return ResourceManager.GetString("SpeedStor_reserved", resourceCulture);
            }
        }
        
        internal static string NEC_DOS {
            get {
                return ResourceManager.GetString("NEC_DOS", resourceCulture);
            }
        }
        
        internal static string Hidden_NTFS {
            get {
                return ResourceManager.GetString("Hidden_NTFS", resourceCulture);
            }
        }
        
        internal static string Theos {
            get {
                return ResourceManager.GetString("Theos", resourceCulture);
            }
        }
        
        internal static string Partition_Magic {
            get {
                return ResourceManager.GetString("Partition_Magic", resourceCulture);
            }
        }
        
        internal static string Hidden_NetWare {
            get {
                return ResourceManager.GetString("Hidden_NetWare", resourceCulture);
            }
        }
        
        internal static string VENIX_80286 {
            get {
                return ResourceManager.GetString("VENIX_80286", resourceCulture);
            }
        }
        
        internal static string PReP_Boot {
            get {
                return ResourceManager.GetString("PReP_Boot", resourceCulture);
            }
        }
        
        internal static string Secure_File_System {
            get {
                return ResourceManager.GetString("Secure_File_System", resourceCulture);
            }
        }
        
        internal static string PTS_DOS {
            get {
                return ResourceManager.GetString("PTS_DOS", resourceCulture);
            }
        }
        
        internal static string Priam_EUMEL_Elan {
            get {
                return ResourceManager.GetString("Priam_EUMEL_Elan", resourceCulture);
            }
        }
        
        internal static string EUMEL_Elan {
            get {
                return ResourceManager.GetString("EUMEL_Elan", resourceCulture);
            }
        }
        
        internal static string ALFS_THIN_lightweight_filesystem_for_DOS {
            get {
                return ResourceManager.GetString("ALFS_THIN_lightweight_filesystem_for_DOS", resourceCulture);
            }
        }
        
        internal static string QNX_4 {
            get {
                return ResourceManager.GetString("QNX_4", resourceCulture);
            }
        }
        
        internal static string QNX_4_Oberon {
            get {
                return ResourceManager.GetString("QNX_4_Oberon", resourceCulture);
            }
        }
        
        internal static string Ontrack_DM_RO_FAT {
            get {
                return ResourceManager.GetString("Ontrack_DM_RO_FAT", resourceCulture);
            }
        }
        
        internal static string Ontrack_DM_RW_FAT {
            get {
                return ResourceManager.GetString("Ontrack_DM_RW_FAT", resourceCulture);
            }
        }
        
        internal static string CPM_Microport_UNIX {
            get {
                return ResourceManager.GetString("CPM_Microport_UNIX", resourceCulture);
            }
        }
        
        internal static string Ontrack_DM_6 {
            get {
                return ResourceManager.GetString("Ontrack_DM_6", resourceCulture);
            }
        }
        
        internal static string EZ_Drive {
            get {
                return ResourceManager.GetString("EZ_Drive", resourceCulture);
            }
        }
        
        internal static string Golden_Bow_VFeature {
            get {
                return ResourceManager.GetString("Golden_Bow_VFeature", resourceCulture);
            }
        }
        
        internal static string Priam_EDISK {
            get {
                return ResourceManager.GetString("Priam_EDISK", resourceCulture);
            }
        }
        
        internal static string SpeedStor {
            get {
                return ResourceManager.GetString("SpeedStor", resourceCulture);
            }
        }
        
        internal static string GNU_Hurd_System_V_386ix {
            get {
                return ResourceManager.GetString("GNU_Hurd_System_V_386ix", resourceCulture);
            }
        }
        
        internal static string NetWare_286 {
            get {
                return ResourceManager.GetString("NetWare_286", resourceCulture);
            }
        }
        
        internal static string NetWare {
            get {
                return ResourceManager.GetString("NetWare", resourceCulture);
            }
        }
        
        internal static string NetWare_386 {
            get {
                return ResourceManager.GetString("NetWare_386", resourceCulture);
            }
        }
        
        internal static string NetWare_NSS {
            get {
                return ResourceManager.GetString("NetWare_NSS", resourceCulture);
            }
        }
        
        internal static string DiskSecure_Multi_Boot {
            get {
                return ResourceManager.GetString("DiskSecure_Multi_Boot", resourceCulture);
            }
        }
        
        internal static string IBM_PC_IX {
            get {
                return ResourceManager.GetString("IBM_PC_IX", resourceCulture);
            }
        }
        
        internal static string Old_MINIX {
            get {
                return ResourceManager.GetString("Old_MINIX", resourceCulture);
            }
        }
        
        internal static string MINIX_Old_Linux {
            get {
                return ResourceManager.GetString("MINIX_Old_Linux", resourceCulture);
            }
        }
        
        internal static string Linux_swap_Solaris {
            get {
                return ResourceManager.GetString("Linux_swap_Solaris", resourceCulture);
            }
        }
        
        internal static string Linux {
            get {
                return ResourceManager.GetString("Linux", resourceCulture);
            }
        }
        
        internal static string Hidden_by_OS2_APM_hibernation {
            get {
                return ResourceManager.GetString("Hidden_by_OS2_APM_hibernation", resourceCulture);
            }
        }
        
        internal static string Linux_extended {
            get {
                return ResourceManager.GetString("Linux_extended", resourceCulture);
            }
        }
        
        internal static string NT_Stripe_Set {
            get {
                return ResourceManager.GetString("NT_Stripe_Set", resourceCulture);
            }
        }
        
        internal static string Linux_Plaintext {
            get {
                return ResourceManager.GetString("Linux_Plaintext", resourceCulture);
            }
        }
        
        internal static string Linux_LVM {
            get {
                return ResourceManager.GetString("Linux_LVM", resourceCulture);
            }
        }
        
        internal static string Amoeba_Hidden_Linux {
            get {
                return ResourceManager.GetString("Amoeba_Hidden_Linux", resourceCulture);
            }
        }
        
        internal static string Amoeba_bad_blocks {
            get {
                return ResourceManager.GetString("Amoeba_bad_blocks", resourceCulture);
            }
        }
        
        internal static string Mylex_EISA_SCSI {
            get {
                return ResourceManager.GetString("Mylex_EISA_SCSI", resourceCulture);
            }
        }
        
        internal static string BSD_OS {
            get {
                return ResourceManager.GetString("BSD_OS", resourceCulture);
            }
        }
        
        internal static string Hibernation {
            get {
                return ResourceManager.GetString("Hibernation", resourceCulture);
            }
        }
        
        internal static string HP_Volume_Expansion {
            get {
                return ResourceManager.GetString("HP_Volume_Expansion", resourceCulture);
            }
        }
        
        internal static string FreeBSD {
            get {
                return ResourceManager.GetString("FreeBSD", resourceCulture);
            }
        }
        
        internal static string OpenBSD {
            get {
                return ResourceManager.GetString("OpenBSD", resourceCulture);
            }
        }
        
        internal static string NeXTStep {
            get {
                return ResourceManager.GetString("NeXTStep", resourceCulture);
            }
        }
        
        internal static string NetBSD {
            get {
                return ResourceManager.GetString("NetBSD", resourceCulture);
            }
        }
        
        internal static string Olivetti_DOS_FAT12 {
            get {
                return ResourceManager.GetString("Olivetti_DOS_FAT12", resourceCulture);
            }
        }
        
        internal static string BootStar {
            get {
                return ResourceManager.GetString("BootStar", resourceCulture);
            }
        }
        
        internal static string BSDi {
            get {
                return ResourceManager.GetString("BSDi", resourceCulture);
            }
        }
        
        internal static string PTS_BootWizard {
            get {
                return ResourceManager.GetString("PTS_BootWizard", resourceCulture);
            }
        }
        
        internal static string Solaris_boot {
            get {
                return ResourceManager.GetString("Solaris_boot", resourceCulture);
            }
        }
        
        internal static string Solaris {
            get {
                return ResourceManager.GetString("Solaris", resourceCulture);
            }
        }
        
        internal static string Novell_DOS_DR_DOS_secured {
            get {
                return ResourceManager.GetString("Novell_DOS_DR_DOS_secured", resourceCulture);
            }
        }
        
        internal static string DR_DOS_secured_FAT12 {
            get {
                return ResourceManager.GetString("DR_DOS_secured_FAT12", resourceCulture);
            }
        }
        
        internal static string DR_DOS_reserved {
            get {
                return ResourceManager.GetString("DR_DOS_reserved", resourceCulture);
            }
        }
        
        internal static string DR_DOS_secured_FAT16_32_MiB {
            get {
                return ResourceManager.GetString("DR_DOS_secured_FAT16_32_MiB", resourceCulture);
            }
        }
        
        internal static string DR_DOS_secured_FAT16 {
            get {
                return ResourceManager.GetString("DR_DOS_secured_FAT16", resourceCulture);
            }
        }
        
        internal static string Syrinx {
            get {
                return ResourceManager.GetString("Syrinx", resourceCulture);
            }
        }
        
        internal static string DR_DOS_secured_FAT32_LBA {
            get {
                return ResourceManager.GetString("DR_DOS_secured_FAT32_LBA", resourceCulture);
            }
        }
        
        internal static string DR_DOS_secured_FAT16_LBA {
            get {
                return ResourceManager.GetString("DR_DOS_secured_FAT16_LBA", resourceCulture);
            }
        }
        
        internal static string DR_DOS_secured_FAT32 {
            get {
                return ResourceManager.GetString("DR_DOS_secured_FAT32", resourceCulture);
            }
        }
        
        internal static string DR_DOS_secured_extended_LBA {
            get {
                return ResourceManager.GetString("DR_DOS_secured_extended_LBA", resourceCulture);
            }
        }
        
        internal static string Multiuser_DOS_secured_FAT12 {
            get {
                return ResourceManager.GetString("Multiuser_DOS_secured_FAT12", resourceCulture);
            }
        }
        
        internal static string Multiuser_DOS_secured_FAT16_32_MiB {
            get {
                return ResourceManager.GetString("Multiuser_DOS_secured_FAT16_32_MiB", resourceCulture);
            }
        }
        
        internal static string Multiuser_DOS_secured_extended {
            get {
                return ResourceManager.GetString("Multiuser_DOS_secured_extended", resourceCulture);
            }
        }
        
        internal static string Multiuser_DOS_secured_FAT16 {
            get {
                return ResourceManager.GetString("Multiuser_DOS_secured_FAT16", resourceCulture);
            }
        }
        
        internal static string CPM {
            get {
                return ResourceManager.GetString("CPM", resourceCulture);
            }
        }
        
        internal static string Filesystem_less_data {
            get {
                return ResourceManager.GetString("Filesystem_less_data", resourceCulture);
            }
        }
        
        internal static string CPM_CCPM_CTOS {
            get {
                return ResourceManager.GetString("CPM_CCPM_CTOS", resourceCulture);
            }
        }
        
        internal static string Dell_partition {
            get {
                return ResourceManager.GetString("Dell_partition", resourceCulture);
            }
        }
        
        internal static string BootIt_EMBRM {
            get {
                return ResourceManager.GetString("BootIt_EMBRM", resourceCulture);
            }
        }
        
        internal static string DOS_read_only {
            get {
                return ResourceManager.GetString("DOS_read_only", resourceCulture);
            }
        }
        
        internal static string Tandy_DOS {
            get {
                return ResourceManager.GetString("Tandy_DOS", resourceCulture);
            }
        }
        
        internal static string BeOS {
            get {
                return ResourceManager.GetString("BeOS", resourceCulture);
            }
        }
        
        internal static string Sprytx {
            get {
                return ResourceManager.GetString("Sprytx", resourceCulture);
            }
        }
        
        internal static string Guid_Partition_Table {
            get {
                return ResourceManager.GetString("Guid_Partition_Table", resourceCulture);
            }
        }
        
        internal static string EFI_system_partition {
            get {
                return ResourceManager.GetString("EFI_system_partition", resourceCulture);
            }
        }
        
        internal static string Linux_boot {
            get {
                return ResourceManager.GetString("Linux_boot", resourceCulture);
            }
        }
        
        internal static string DOS_3_3_secondary_Unisys_DOS {
            get {
                return ResourceManager.GetString("DOS_3_3_secondary_Unisys_DOS", resourceCulture);
            }
        }
        
        internal static string Prologue {
            get {
                return ResourceManager.GetString("Prologue", resourceCulture);
            }
        }
        
        internal static string VMWare_VMKCORE {
            get {
                return ResourceManager.GetString("VMWare_VMKCORE", resourceCulture);
            }
        }
        
        internal static string Linux_RAID_FreeDOS {
            get {
                return ResourceManager.GetString("Linux_RAID_FreeDOS", resourceCulture);
            }
        }
        
        internal static string SpeedStor_LANStep_PS2_IML {
            get {
                return ResourceManager.GetString("SpeedStor_LANStep_PS2_IML", resourceCulture);
            }
        }
        
        internal static string Xenix_bad_block {
            get {
                return ResourceManager.GetString("Xenix_bad_block", resourceCulture);
            }
        }
        
        internal static string MBR_Name {
            get {
                return ResourceManager.GetString("MBR_Name", resourceCulture);
            }
        }
        
        internal static string MINIX {
            get {
                return ResourceManager.GetString("MINIX", resourceCulture);
            }
        }
        
        internal static string NeXTDisklabel_Name {
            get {
                return ResourceManager.GetString("NeXTDisklabel_Name", resourceCulture);
            }
        }
        
        internal static string Partition_bigger_than_device_reducing {
            get {
                return ResourceManager.GetString("Partition_bigger_than_device_reducing", resourceCulture);
            }
        }
        
        internal static string _0_bytes_per_block {
            get {
                return ResourceManager.GetString("_0_bytes_per_block", resourceCulture);
            }
        }
        
        internal static string _0_bytes_per_fragment {
            get {
                return ResourceManager.GetString("_0_bytes_per_fragment", resourceCulture);
            }
        }
        
        internal static string Space_optimized {
            get {
                return ResourceManager.GetString("Space_optimized", resourceCulture);
            }
        }
        
        internal static string Time_optimized {
            get {
                return ResourceManager.GetString("Time_optimized", resourceCulture);
            }
        }
        
        internal static string Unknown_optimization_0_X2 {
            get {
                return ResourceManager.GetString("Unknown_optimization_0_X2", resourceCulture);
            }
        }
        
        internal static string _0_cylinders_per_group {
            get {
                return ResourceManager.GetString("_0_cylinders_per_group", resourceCulture);
            }
        }
        
        internal static string _0_bytes_per_inode {
            get {
                return ResourceManager.GetString("_0_bytes_per_inode", resourceCulture);
            }
        }
        
        internal static string _0_of_space_must_be_free_at_minimum {
            get {
                return ResourceManager.GetString("_0_of_space_must_be_free_at_minimum", resourceCulture);
            }
        }
        
        internal static string Filesystem_should_be_formatted_at_start {
            get {
                return ResourceManager.GetString("Filesystem_should_be_formatted_at_start", resourceCulture);
            }
        }
        
        internal static string Filesystem_should_be_automatically_mounted {
            get {
                return ResourceManager.GetString("Filesystem_should_be_automatically_mounted", resourceCulture);
            }
        }
        
        internal static string PC98_Name {
            get {
                return ResourceManager.GetString("PC98_Name", resourceCulture);
            }
        }
        
        internal static string PC_UX {
            get {
                return ResourceManager.GetString("PC_UX", resourceCulture);
            }
        }
        
        internal static string N88_BASIC_86 {
            get {
                return ResourceManager.GetString("N88_BASIC_86", resourceCulture);
            }
        }
        
        internal static string Windows_Volume_Set {
            get {
                return ResourceManager.GetString("Windows_Volume_Set", resourceCulture);
            }
        }
        
        internal static string Plan9_Name {
            get {
                return ResourceManager.GetString("Plan9_Name", resourceCulture);
            }
        }
        
        internal static string AmigaRigidDiskBlock_Name {
            get {
                return ResourceManager.GetString("AmigaRigidDiskBlock_Name", resourceCulture);
            }
        }
        
        internal static string Possible_magic_at_block_0_is_1_X8 {
            get {
                return ResourceManager.GetString("Possible_magic_at_block_0_is_1_X8", resourceCulture);
            }
        }
        
        internal static string Found_RDB_magic_at_block_0 {
            get {
                return ResourceManager.GetString("Found_RDB_magic_at_block_0", resourceCulture);
            }
        }
        
        internal static string Going_to_block_0_in_search_of_a_BadBlock_block {
            get {
                return ResourceManager.GetString("Going_to_block_0_in_search_of_a_BadBlock_block", resourceCulture);
            }
        }
        
        internal static string Found_BadBlock_block {
            get {
                return ResourceManager.GetString("Found_BadBlock_block", resourceCulture);
            }
        }
        
        internal static string Bad_block_at_0_replaced_with_good_block_at_1 {
            get {
                return ResourceManager.GetString("Bad_block_at_0_replaced_with_good_block_at_1", resourceCulture);
            }
        }
        
        internal static string Going_to_block_0_in_search_of_a_PartitionEntry_block {
            get {
                return ResourceManager.GetString("Going_to_block_0_in_search_of_a_PartitionEntry_block", resourceCulture);
            }
        }
        
        internal static string Found_PartitionEntry_block {
            get {
                return ResourceManager.GetString("Found_PartitionEntry_block", resourceCulture);
            }
        }
        
        internal static string Going_to_block_0_in_search_of_a_FileSystemHeader_block {
            get {
                return ResourceManager.GetString("Going_to_block_0_in_search_of_a_FileSystemHeader_block", resourceCulture);
            }
        }
        
        internal static string Found_FileSystemHeader_block {
            get {
                return ResourceManager.GetString("Found_FileSystemHeader_block", resourceCulture);
            }
        }
        
        internal static string Going_to_block_0_in_search_of_a_LoadSegment_block {
            get {
                return ResourceManager.GetString("Going_to_block_0_in_search_of_a_LoadSegment_block", resourceCulture);
            }
        }
        
        internal static string Found_LoadSegment_block {
            get {
                return ResourceManager.GetString("Found_LoadSegment_block", resourceCulture);
            }
        }
        
        internal static string LoadSegment_data_SHA1_0 {
            get {
                return ResourceManager.GetString("LoadSegment_data_SHA1_0", resourceCulture);
            }
        }
        
        internal static string Amiga_Original_File_System {
            get {
                return ResourceManager.GetString("Amiga_Original_File_System", resourceCulture);
            }
        }
        
        internal static string Amiga_Fast_File_System {
            get {
                return ResourceManager.GetString("Amiga_Fast_File_System", resourceCulture);
            }
        }
        
        internal static string Amiga_Original_File_System_with_international_characters {
            get {
                return ResourceManager.GetString("Amiga_Original_File_System_with_international_characters", resourceCulture);
            }
        }
        
        internal static string Amiga_Fast_File_System_with_international_characters {
            get {
                return ResourceManager.GetString("Amiga_Fast_File_System_with_international_characters", resourceCulture);
            }
        }
        
        internal static string Amiga_Original_File_System_with_directory_cache {
            get {
                return ResourceManager.GetString("Amiga_Original_File_System_with_directory_cache", resourceCulture);
            }
        }
        
        internal static string Amiga_Fast_File_System_with_directory_cache {
            get {
                return ResourceManager.GetString("Amiga_Fast_File_System_with_directory_cache", resourceCulture);
            }
        }
        
        internal static string Amiga_Original_File_System_with_long_filenames {
            get {
                return ResourceManager.GetString("Amiga_Original_File_System_with_long_filenames", resourceCulture);
            }
        }
        
        internal static string Amiga_Fast_File_System_with_long_filenames {
            get {
                return ResourceManager.GetString("Amiga_Fast_File_System_with_long_filenames", resourceCulture);
            }
        }
        
        internal static string Amiga_UNIX_System_V_filesystem {
            get {
                return ResourceManager.GetString("Amiga_UNIX_System_V_filesystem", resourceCulture);
            }
        }
        
        internal static string Amiga_UNIX_boot_filesystem {
            get {
                return ResourceManager.GetString("Amiga_UNIX_boot_filesystem", resourceCulture);
            }
        }
        
        internal static string Amiga_UNIX_BSD_filesystem {
            get {
                return ResourceManager.GetString("Amiga_UNIX_BSD_filesystem", resourceCulture);
            }
        }
        
        internal static string Amiga_UNIX_Reserved_partition__swap_ {
            get {
                return ResourceManager.GetString("Amiga_UNIX_Reserved_partition__swap_", resourceCulture);
            }
        }
        
        internal static string ProfessionalFileSystem {
            get {
                return ResourceManager.GetString("ProfessionalFileSystem", resourceCulture);
            }
        }
        
        internal static string SmartFileSystem_v1 {
            get {
                return ResourceManager.GetString("SmartFileSystem_v1", resourceCulture);
            }
        }
        
        internal static string SmartFileSystem_v2 {
            get {
                return ResourceManager.GetString("SmartFileSystem_v2", resourceCulture);
            }
        }
        
        internal static string JXFS {
            get {
                return ResourceManager.GetString("JXFS", resourceCulture);
            }
        }
        
        internal static string FAT_as_set_by_CrossDOS {
            get {
                return ResourceManager.GetString("FAT_as_set_by_CrossDOS", resourceCulture);
            }
        }
        
        internal static string HFS_as_set_by_CrossMac {
            get {
                return ResourceManager.GetString("HFS_as_set_by_CrossMac", resourceCulture);
            }
        }
        
        internal static string _4_2_UFS_for_BFFS {
            get {
                return ResourceManager.GetString("_4_2_UFS_for_BFFS", resourceCulture);
            }
        }
        
        internal static string Amiga_Original_File_System_with_multi_user_patches {
            get {
                return ResourceManager.GetString("Amiga_Original_File_System_with_multi_user_patches", resourceCulture);
            }
        }
        
        internal static string Amiga_Fast_File_System_with_multi_user_patches {
            get {
                return ResourceManager.GetString("Amiga_Fast_File_System_with_multi_user_patches", resourceCulture);
            }
        }
        
        internal static string Amiga_Original_File_System_with_international_characters_and_multi_user_patches {
            get {
                return ResourceManager.GetString("Amiga_Original_File_System_with_international_characters_and_multi_user_patches", resourceCulture);
            }
        }
        
        internal static string Amiga_Fast_File_System_with_international_characters_and_multi_user_patches {
            get {
                return ResourceManager.GetString("Amiga_Fast_File_System_with_international_characters_and_multi_user_patches", resourceCulture);
            }
        }
        
        internal static string Amiga_Original_File_System_with_directory_cache_and_multi_user_patches {
            get {
                return ResourceManager.GetString("Amiga_Original_File_System_with_directory_cache_and_multi_user_patches", resourceCulture);
            }
        }
        
        internal static string Amiga_Fast_File_System_with_directory_cache_and_multi_user_patches {
            get {
                return ResourceManager.GetString("Amiga_Fast_File_System_with_directory_cache_and_multi_user_patches", resourceCulture);
            }
        }
        
        internal static string BSD_unused {
            get {
                return ResourceManager.GetString("BSD_unused", resourceCulture);
            }
        }
        
        internal static string BSD_swap {
            get {
                return ResourceManager.GetString("BSD_swap", resourceCulture);
            }
        }
        
        internal static string BSD_4_2_FFS {
            get {
                return ResourceManager.GetString("BSD_4_2_FFS", resourceCulture);
            }
        }
        
        internal static string BSD_4_4_LFS {
            get {
                return ResourceManager.GetString("BSD_4_4_LFS", resourceCulture);
            }
        }
        
        internal static string NetBSD_unused_root_partition {
            get {
                return ResourceManager.GetString("NetBSD_unused_root_partition", resourceCulture);
            }
        }
        
        internal static string NetBSD_4_2_FFS_root_partition {
            get {
                return ResourceManager.GetString("NetBSD_4_2_FFS_root_partition", resourceCulture);
            }
        }
        
        internal static string NetBSD_4_4_LFS_root_partition {
            get {
                return ResourceManager.GetString("NetBSD_4_4_LFS_root_partition", resourceCulture);
            }
        }
        
        internal static string NetBSD_unused_user_partition {
            get {
                return ResourceManager.GetString("NetBSD_unused_user_partition", resourceCulture);
            }
        }
        
        internal static string NetBSD_4_2_FFS_user_partition {
            get {
                return ResourceManager.GetString("NetBSD_4_2_FFS_user_partition", resourceCulture);
            }
        }
        
        internal static string NetBSD_4_4_LFS_user_partition {
            get {
                return ResourceManager.GetString("NetBSD_4_4_LFS_user_partition", resourceCulture);
            }
        }
        
        internal static string Linux_filesystem_partition {
            get {
                return ResourceManager.GetString("Linux_filesystem_partition", resourceCulture);
            }
        }
        
        internal static string Linux_swap_partition {
            get {
                return ResourceManager.GetString("Linux_swap_partition", resourceCulture);
            }
        }
        
        internal static string RaidFrame_partition {
            get {
                return ResourceManager.GetString("RaidFrame_partition", resourceCulture);
            }
        }
        
        internal static string Unknown_Amiga_DOS_filesystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_Amiga_DOS_filesystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_Amiga_UNIX_filesystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_Amiga_UNIX_filesystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_ProfessionalFileSystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_ProfessionalFileSystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_SmartFileSystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_SmartFileSystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_Amiga_DOS_multi_user_filesystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_Amiga_DOS_multi_user_filesystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_BSD_filesystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_BSD_filesystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_NetBSD_root_filesystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_NetBSD_root_filesystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_NetBSD_user_filesystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_NetBSD_user_filesystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_NetBSD_swap_filesystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_NetBSD_swap_filesystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_Linux_filesystem_type_0 {
            get {
                return ResourceManager.GetString("Unknown_Linux_filesystem_type_0", resourceCulture);
            }
        }
        
        internal static string Unknown_partition_type_0 {
            get {
                return ResourceManager.GetString("Unknown_partition_type_0", resourceCulture);
            }
        }
        
        internal static string RioKarma_Name {
            get {
                return ResourceManager.GetString("RioKarma_Name", resourceCulture);
            }
        }
        
        internal static string Rio_Karma {
            get {
                return ResourceManager.GetString("Rio_Karma", resourceCulture);
            }
        }
        
        internal static string SGI_Name {
            get {
                return ResourceManager.GetString("SGI_Name", resourceCulture);
            }
        }
        
        internal static string dvh_magic_equals_0_X8_should_be_1_X8 {
            get {
                return ResourceManager.GetString("dvh_magic_equals_0_X8_should_be_1_X8", resourceCulture);
            }
        }
        
        internal static string Volume_header {
            get {
                return ResourceManager.GetString("Volume_header", resourceCulture);
            }
        }
        
        internal static string Track_replacements {
            get {
                return ResourceManager.GetString("Track_replacements", resourceCulture);
            }
        }
        
        internal static string Sector_replacements {
            get {
                return ResourceManager.GetString("Sector_replacements", resourceCulture);
            }
        }
        
        internal static string Raw_data_swap {
            get {
                return ResourceManager.GetString("Raw_data_swap", resourceCulture);
            }
        }
        
        internal static string Whole_device {
            get {
                return ResourceManager.GetString("Whole_device", resourceCulture);
            }
        }
        
        internal static string Logical_volume {
            get {
                return ResourceManager.GetString("Logical_volume", resourceCulture);
            }
        }
        
        internal static string Raw_logical_volume {
            get {
                return ResourceManager.GetString("Raw_logical_volume", resourceCulture);
            }
        }
        
        internal static string XFS {
            get {
                return ResourceManager.GetString("XFS", resourceCulture);
            }
        }
        
        internal static string XFS_log_device {
            get {
                return ResourceManager.GetString("XFS_log_device", resourceCulture);
            }
        }
        
        internal static string XLV_volume {
            get {
                return ResourceManager.GetString("XLV_volume", resourceCulture);
            }
        }
        
        internal static string SGI_XVM {
            get {
                return ResourceManager.GetString("SGI_XVM", resourceCulture);
            }
        }
        
        internal static string Linux_swap {
            get {
                return ResourceManager.GetString("Linux_swap", resourceCulture);
            }
        }
        
        internal static string SunDisklabel_Name {
            get {
                return ResourceManager.GetString("SunDisklabel_Name", resourceCulture);
            }
        }
        
        internal static string SunOS_partition {
            get {
                return ResourceManager.GetString("SunOS_partition", resourceCulture);
            }
        }
        
        internal static string Partition_timestamped_on_0 {
            get {
                return ResourceManager.GetString("Partition_timestamped_on_0", resourceCulture);
            }
        }
        
        internal static string Swapping_dk_label {
            get {
                return ResourceManager.GetString("Swapping_dk_label", resourceCulture);
            }
        }
        
        internal static string Swapping_dk_label8 {
            get {
                return ResourceManager.GetString("Swapping_dk_label8", resourceCulture);
            }
        }
        
        internal static string Swapping_dk_label16 {
            get {
                return ResourceManager.GetString("Swapping_dk_label16", resourceCulture);
            }
        }
        
        internal static string Unmountable {
            get {
                return ResourceManager.GetString("Unmountable", resourceCulture);
            }
        }
        
        internal static string Read_only {
            get {
                return ResourceManager.GetString("Read_only", resourceCulture);
            }
        }
        
        internal static string LVM {
            get {
                return ResourceManager.GetString("LVM", resourceCulture);
            }
        }
        
        internal static string Sun_boot {
            get {
                return ResourceManager.GetString("Sun_boot", resourceCulture);
            }
        }
        
        internal static string Sun_home {
            get {
                return ResourceManager.GetString("Sun_home", resourceCulture);
            }
        }
        
        internal static string Sun_root {
            get {
                return ResourceManager.GetString("Sun_root", resourceCulture);
            }
        }
        
        internal static string Sun_stand {
            get {
                return ResourceManager.GetString("Sun_stand", resourceCulture);
            }
        }
        
        internal static string Sun_swap {
            get {
                return ResourceManager.GetString("Sun_swap", resourceCulture);
            }
        }
        
        internal static string Sun_usr {
            get {
                return ResourceManager.GetString("Sun_usr", resourceCulture);
            }
        }
        
        internal static string Sun_var {
            get {
                return ResourceManager.GetString("Sun_var", resourceCulture);
            }
        }
        
        internal static string Whole_disk {
            get {
                return ResourceManager.GetString("Whole_disk", resourceCulture);
            }
        }
        
        internal static string Replacement_sectors {
            get {
                return ResourceManager.GetString("Replacement_sectors", resourceCulture);
            }
        }
        
        internal static string Sun_cachefs {
            get {
                return ResourceManager.GetString("Sun_cachefs", resourceCulture);
            }
        }
        
        internal static string Reserved_for_SMI {
            get {
                return ResourceManager.GetString("Reserved_for_SMI", resourceCulture);
            }
        }
        
        internal static string Veritas_public {
            get {
                return ResourceManager.GetString("Veritas_public", resourceCulture);
            }
        }
        
        internal static string Veritas_private {
            get {
                return ResourceManager.GetString("Veritas_private", resourceCulture);
            }
        }
        
        internal static string FreeBSD_swap {
            get {
                return ResourceManager.GetString("FreeBSD_swap", resourceCulture);
            }
        }
        
        internal static string Vinum {
            get {
                return ResourceManager.GetString("Vinum", resourceCulture);
            }
        }
        
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        internal static string error_log {
            get {
                return ResourceManager.GetString("error_log", resourceCulture);
            }
        }
        
        internal static string errorlog {
            get {
                return ResourceManager.GetString("errorlog", resourceCulture);
            }
        }
        
        internal static string swap {
            get {
                return ResourceManager.GetString("swap", resourceCulture);
            }
        }
        
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        internal static string maintenance_area {
            get {
                return ResourceManager.GetString("maintenance_area", resourceCulture);
            }
        }
        
        internal static string maintenance {
            get {
                return ResourceManager.GetString("maintenance", resourceCulture);
            }
        }
        
        internal static string bad_sector_file {
            get {
                return ResourceManager.GetString("bad_sector_file", resourceCulture);
            }
        }
        
        internal static string bad {
            get {
                return ResourceManager.GetString("bad", resourceCulture);
            }
        }
        
        internal static string UNIX_Name {
            get {
                return ResourceManager.GetString("UNIX_Name", resourceCulture);
            }
        }
        
        internal static string VTOC_Name {
            get {
                return ResourceManager.GetString("VTOC_Name", resourceCulture);
            }
        }
        
        internal static string sanity_at_0_is_1_X8_should_be_2_X8_or_3_X8 {
            get {
                return ResourceManager.GetString("sanity_at_0_is_1_X8_should_be_2_X8_or_3_X8", resourceCulture);
            }
        }
        
        internal static string New_VTOC_found_at_0 {
            get {
                return ResourceManager.GetString("New_VTOC_found_at_0", resourceCulture);
            }
        }
        
        internal static string Old_VTOC_found_at_0 {
            get {
                return ResourceManager.GetString("Old_VTOC_found_at_0", resourceCulture);
            }
        }
        
        internal static string Searching_for_VTOC_on_relative_byte_0 {
            get {
                return ResourceManager.GetString("Searching_for_VTOC_on_relative_byte_0", resourceCulture);
            }
        }
        
        internal static string Going_to_read_0_sectors_from_sector_1_getting_VTOC_from_byte_2 {
            get {
                return ResourceManager.GetString("Going_to_read_0_sectors_from_sector_1_getting_VTOC_from_byte_2", resourceCulture);
            }
        }
        
        internal static string Going_to_read_past_device_size_aborting {
            get {
                return ResourceManager.GetString("Going_to_read_past_device_size_aborting", resourceCulture);
            }
        }
        
        internal static string New_VTOC_found {
            get {
                return ResourceManager.GetString("New_VTOC_found", resourceCulture);
            }
        }
        
        internal static string Cannot_find_VTOC {
            get {
                return ResourceManager.GetString("Cannot_find_VTOC", resourceCulture);
            }
        }
        
        internal static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
        
        internal static string _unmountable_ {
            get {
                return ResourceManager.GetString("_unmountable_", resourceCulture);
            }
        }
        
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        internal static string alternate_sector_mapping {
            get {
                return ResourceManager.GetString("alternate_sector_mapping", resourceCulture);
            }
        }
        
        internal static string _read_only_ {
            get {
                return ResourceManager.GetString("_read_only_", resourceCulture);
            }
        }
        
        internal static string created_on_0 {
            get {
                return ResourceManager.GetString("created_on_0", resourceCulture);
            }
        }
        
        internal static string Unused {
            get {
                return ResourceManager.GetString("Unused", resourceCulture);
            }
        }
        
        internal static string Alternate_sector_space {
            get {
                return ResourceManager.GetString("Alternate_sector_space", resourceCulture);
            }
        }
        
        internal static string non_UNIX {
            get {
                return ResourceManager.GetString("non_UNIX", resourceCulture);
            }
        }
        
        internal static string Alternate_track_space {
            get {
                return ResourceManager.GetString("Alternate_track_space", resourceCulture);
            }
        }
        
        internal static string Alternate_sector_track {
            get {
                return ResourceManager.GetString("Alternate_sector_track", resourceCulture);
            }
        }
        
        internal static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        internal static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        internal static string dump {
            get {
                return ResourceManager.GetString("dump", resourceCulture);
            }
        }
        
        internal static string volume_mgt_public_partition {
            get {
                return ResourceManager.GetString("volume_mgt_public_partition", resourceCulture);
            }
        }
        
        internal static string volume_mgt_private_partition {
            get {
                return ResourceManager.GetString("volume_mgt_private_partition", resourceCulture);
            }
        }
        
        internal static string Unknown_TAG_0 {
            get {
                return ResourceManager.GetString("Unknown_TAG_0", resourceCulture);
            }
        }
        
        internal static string Xbox_Name {
            get {
                return ResourceManager.GetString("Xbox_Name", resourceCulture);
            }
        }
        
        internal static string Content_volume {
            get {
                return ResourceManager.GetString("Content_volume", resourceCulture);
            }
        }
        
        internal static string Dashboard_volume {
            get {
                return ResourceManager.GetString("Dashboard_volume", resourceCulture);
            }
        }
        
        internal static string System_cache {
            get {
                return ResourceManager.GetString("System_cache", resourceCulture);
            }
        }
        
        internal static string Data_volume {
            get {
                return ResourceManager.GetString("Data_volume", resourceCulture);
            }
        }
        
        internal static string Security_sectors {
            get {
                return ResourceManager.GetString("Security_sectors", resourceCulture);
            }
        }
        
        internal static string Game_cache {
            get {
                return ResourceManager.GetString("Game_cache", resourceCulture);
            }
        }
        
        internal static string System_volume {
            get {
                return ResourceManager.GetString("System_volume", resourceCulture);
            }
        }
        
        internal static string System_volume_2 {
            get {
                return ResourceManager.GetString("System_volume_2", resourceCulture);
            }
        }
        
        internal static string Xbox_backwards_compatibility {
            get {
                return ResourceManager.GetString("Xbox_backwards_compatibility", resourceCulture);
            }
        }
        
        internal static string XENIX_Name {
            get {
                return ResourceManager.GetString("XENIX_Name", resourceCulture);
            }
        }
    }
}
