//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace DiscImageChef.Server {
	
	
	public partial class Statistics {
		
		protected HtmlGenericControl body;
		
		protected Label lblVersion;
		
		protected HtmlGenericControl content;
		
		protected HtmlGenericControl divOperatingSystems;
		
		protected Repeater repOperatingSystems;
		
		protected HtmlGenericControl divVersions;
		
		protected Repeater repVersions;
		
		protected HtmlGenericControl divCommands;
		
		protected Label lblAnalyze;
		
		protected Label lblBenchmark;
		
		protected Label lblChecksum;
		
		protected Label lblCompare;
		
	    protected Label lblConvertImage;
		
	    protected Label lblCreateSidecar;
		
		protected Label lblDecode;
		
		protected Label lblDeviceInfo;
		
		protected Label lblDeviceReport;
		
		protected Label lblDumpMedia;
		
		protected Label lblEntropy;
		
		protected Label lblExtractFiles;
		
		protected Label lblFormats;
		
		protected Label lblListDevices;
		
		protected Label lblListEncodings;
		
		protected Label lblLs;
		
		protected Label lblMediaInfo;
		
		protected Label lblMediaScan;
		
		protected Label lblPrintHex;
		
		protected Label lblVerify;
		
		protected HtmlGenericControl divFilters;
		
		protected Repeater repFilters;
		
		protected HtmlGenericControl divMediaImages;
		
		protected Repeater repMediaImages;
		
		protected HtmlGenericControl divPartitions;
		
		protected Repeater repPartitions;
		
		protected HtmlGenericControl divFilesystems;
		
		protected Repeater repFilesystems;
		
		protected HtmlGenericControl divVirtualMedia;
		
		protected Repeater repVirtualMedia;
		
		protected HtmlGenericControl divRealMedia;
		
		protected Repeater repRealMedia;
		
		protected HtmlGenericControl divDevices;
		
		protected Repeater repDevices;
	}
}
