//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace DiscImageChef.Server {
	
	
	public partial class ViewReport {
		
		protected HtmlGenericControl content;
		
		protected Label lblManufacturer;
		
		protected Label lblModel;
		
		protected Label lblRevision;
		
		protected HtmlGenericControl divUsb;
		
		protected Label lblUsbManufacturer;
		
		protected Label lblUsbProduct;
		
		protected Label lblUsbVendor;
		
		protected Label lblUsbVendorDescription;
		
		protected Label lblUsbProductId;
		
		protected Label lblUsbProductDescription;
		
		protected HtmlGenericControl divFirewire;
		
		protected Label lblFirewireManufacturer;
		
		protected Label lblFirewireProduct;
		
		protected Label lblFirewireVendor;
		
		protected Label lblFirewireProductId;
		
		protected HtmlGenericControl divPcmcia;
		
		protected Label lblPcmciaManufacturer;
		
		protected Label lblPcmciaProduct;
		
		protected Label lblPcmciaManufacturerCode;
		
		protected Label lblPcmciaCardCode;
		
		protected Label lblPcmciaCompliance;
		
		protected Repeater repPcmciaTuples;
		
		protected HtmlGenericControl divAta;
		
		protected Label lblAtapi;
		
		protected Label lblAtaDeviceType;
		
		protected Repeater repAtaTwo;
		
		protected Repeater repAtaOne;
		
		protected HtmlGenericControl divScsi;
		
		protected Label lblScsiVendor;
		
		protected Label lblScsiProduct;
		
		protected Label lblScsiRevision;
		
		protected Repeater repScsi;
		
		protected HtmlGenericControl divScsiModeSense;
		
		protected Repeater repModeSense;
		
		protected HtmlGenericControl divScsiEvpd;
		
		protected Repeater repEvpd;
		
		protected HtmlGenericControl divScsiMmcMode;
		
		protected Repeater repScsiMmcMode;
		
		protected HtmlGenericControl divScsiMmcFeatures;
		
		protected Repeater repScsiMmcFeatures;
		
		protected HtmlGenericControl divScsiSsc;
		
		protected Label lblScsiSscGranularity;
		
		protected Label lblScsiSscMaxBlock;
		
		protected Label lblScsiSscMinBlock;
		
		protected Repeater repScsiSscDensities;
		
		protected Repeater repScsiSscMedias;
		
		protected HtmlGenericControl divTestedMedia;
		
		protected Repeater repTestedMedia;
		
		protected HtmlGenericControl divMMC;
		
		protected Repeater repMMC;
		
		protected HtmlGenericControl divSD;
		
		protected Repeater repSD;
	}
}
