// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiscImageChef.Server {
	
	
	public partial class ViewReport {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl content;
		
		protected System.Web.UI.WebControls.Label lblManufacturer;
		
		protected System.Web.UI.WebControls.Label lblModel;
		
		protected System.Web.UI.WebControls.Label lblRevision;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divUsb;
		
		protected System.Web.UI.WebControls.Label lblUsbManufacturer;
		
		protected System.Web.UI.WebControls.Label lblUsbProduct;
		
		protected System.Web.UI.WebControls.Label lblUsbVendor;
		
		protected System.Web.UI.WebControls.Label lblUsbVendorDescription;
		
		protected System.Web.UI.WebControls.Label lblUsbProductId;
		
		protected System.Web.UI.WebControls.Label lblUsbProductDescription;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divFirewire;
		
		protected System.Web.UI.WebControls.Label lblFirewireManufacturer;
		
		protected System.Web.UI.WebControls.Label lblFirewireProduct;
		
		protected System.Web.UI.WebControls.Label lblFirewireVendor;
		
		protected System.Web.UI.WebControls.Label lblFirewireProductId;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divPcmcia;
		
		protected System.Web.UI.WebControls.Label lblPcmciaManufacturer;
		
		protected System.Web.UI.WebControls.Label lblPcmciaProduct;
		
		protected System.Web.UI.WebControls.Label lblPcmciaManufacturerCode;
		
		protected System.Web.UI.WebControls.Label lblPcmciaCardCode;
		
		protected System.Web.UI.WebControls.Label lblPcmciaCompliance;
		
		protected System.Web.UI.WebControls.Repeater repPcmciaTuples;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divAta;
		
		protected System.Web.UI.WebControls.Label lblAtapi;
		
		protected System.Web.UI.WebControls.Label lblAtaDeviceType;
		
		protected System.Web.UI.WebControls.Repeater repAtaTwo;
		
		protected System.Web.UI.WebControls.Repeater repAtaOne;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divScsi;
		
		protected System.Web.UI.WebControls.Label lblScsiVendor;
		
		protected System.Web.UI.WebControls.Label lblScsiProduct;
		
		protected System.Web.UI.WebControls.Label lblScsiRevision;
		
		protected System.Web.UI.WebControls.Repeater repScsi;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divScsiModeSense;
		
		protected System.Web.UI.WebControls.Repeater repModeSense;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divScsiEvpd;
		
		protected System.Web.UI.WebControls.Repeater repEvpd;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divScsiMmcMode;
		
		protected System.Web.UI.WebControls.Repeater repScsiMmcMode;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divScsiMmcFeatures;
		
		protected System.Web.UI.WebControls.Repeater repScsiMmcFeatures;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divScsiSsc;
		
		protected System.Web.UI.WebControls.Label lblScsiSscGranularity;
		
		protected System.Web.UI.WebControls.Label lblScsiSscMaxBlock;
		
		protected System.Web.UI.WebControls.Label lblScsiSscMinBlock;
		
		protected System.Web.UI.WebControls.Repeater repScsiSscDensities;
		
		protected System.Web.UI.WebControls.Repeater repScsiSscMedias;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divTestedMedia;
		
		protected System.Web.UI.WebControls.Repeater repTestedMedia;
	}
}
