<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Consolonia"/>
    <PackageReference Include="Consolonia.ManagedWindows"/>
    <PackageReference Include="Prism.Avalonia"/>
    <PackageReference Include="Prism.DryIoc.Avalonia"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Windows\MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Windows\HexViewWindow.axaml.cs">
      <DependentUpon>HexViewWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\GoToSectorDialog.axaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\ImageHelpDialog.axaml.cs">
      <DependentUpon>ImageHelpDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\HexViewHelpDialog.axaml.cs">
      <DependentUpon>HexViewHelpDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aaru.CommonTypes\Aaru.CommonTypes.csproj"/>
    <ProjectReference Include="..\Aaru.Core\Aaru.Core.csproj"/>
    <ProjectReference Include="..\Aaru.Helpers\Aaru.Helpers.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
