//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Core {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Core() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aaru.Localization.Core", typeof(Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Querying_ATA_IDENTIFY {
            get {
                return ResourceManager.GetString("Querying_ATA_IDENTIFY", resourceCulture);
            }
        }
        
        public static string Querying_USB_information {
            get {
                return ResourceManager.GetString("Querying_USB_information", resourceCulture);
            }
        }
        
        public static string Querying_PCMCIA_information {
            get {
                return ResourceManager.GetString("Querying_PCMCIA_information", resourceCulture);
            }
        }
        
        public static string NVMe_devices_not_yet_supported {
            get {
                return ResourceManager.GetString("NVMe_devices_not_yet_supported", resourceCulture);
            }
        }
        
        public static string Querying_ATAPI_IDENTIFY {
            get {
                return ResourceManager.GetString("Querying_ATAPI_IDENTIFY", resourceCulture);
            }
        }
        
        public static string Waiting_for_drive_to_become_ready {
            get {
                return ResourceManager.GetString("Waiting_for_drive_to_become_ready", resourceCulture);
            }
        }
        
        public static string Device_not_ready_Sense {
            get {
                return ResourceManager.GetString("Device_not_ready_Sense", resourceCulture);
            }
        }
        
        public static string Got_sense_status_but_no_sense_buffer {
            get {
                return ResourceManager.GetString("Got_sense_status_but_no_sense_buffer", resourceCulture);
            }
        }
        
        public static string Try_to_find_SCSI_READ_LONG_size {
            get {
                return ResourceManager.GetString("Try_to_find_SCSI_READ_LONG_size", resourceCulture);
            }
        }
        
        public static string Trying_to_READ_LONG {
            get {
                return ResourceManager.GetString("Trying_to_READ_LONG", resourceCulture);
            }
        }
        
        public static string Trying_READ_LONG_with_size_0 {
            get {
                return ResourceManager.GetString("Trying_READ_LONG_with_size_0", resourceCulture);
            }
        }
        
        public static string Trying_SCSI_READ_LONG_10 {
            get {
                return ResourceManager.GetString("Trying_SCSI_READ_LONG_10", resourceCulture);
            }
        }
        
        public static string Trying_SCSI_READ_LONG_16 {
            get {
                return ResourceManager.GetString("Trying_SCSI_READ_LONG_16", resourceCulture);
            }
        }
        
        public static string Please_write_media_manufacturer {
            get {
                return ResourceManager.GetString("Please_write_media_manufacturer", resourceCulture);
            }
        }
        
        public static string Media_Type_Name_MMD_140A {
            get {
                return ResourceManager.GetString("Media_Type_Name_MMD_140A", resourceCulture);
            }
        }
        
        public static string Media_Type_Name_MDW_60 {
            get {
                return ResourceManager.GetString("Media_Type_Name_MDW_60", resourceCulture);
            }
        }
        
        public static string Media_Type_Name_MDW_74 {
            get {
                return ResourceManager.GetString("Media_Type_Name_MDW_74", resourceCulture);
            }
        }
        
        public static string Media_Type_Name_MDW_80 {
            get {
                return ResourceManager.GetString("Media_Type_Name_MDW_80", resourceCulture);
            }
        }
        
        public static string Media_Type_Name_MiniDisc {
            get {
                return ResourceManager.GetString("Media_Type_Name_MiniDisc", resourceCulture);
            }
        }
        
        public static string Unknown_device_type {
            get {
                return ResourceManager.GetString("Unknown_device_type", resourceCulture);
            }
        }
        
        public static string Device_supports_MCPT_Command_Set {
            get {
                return ResourceManager.GetString("Device_supports_MCPT_Command_Set", resourceCulture);
            }
        }
        
        public static string Device_reports_incorrect_media_card_type {
            get {
                return ResourceManager.GetString("Device_reports_incorrect_media_card_type", resourceCulture);
            }
        }
        
        public static string Device_contains_SD_card {
            get {
                return ResourceManager.GetString("Device_contains_SD_card", resourceCulture);
            }
        }
        
        public static string Device_contains_MMC {
            get {
                return ResourceManager.GetString("Device_contains_MMC", resourceCulture);
            }
        }
        
        public static string Device_contains_SDIO_card {
            get {
                return ResourceManager.GetString("Device_contains_SDIO_card", resourceCulture);
            }
        }
        
        public static string Device_contains_SM_card {
            get {
                return ResourceManager.GetString("Device_contains_SM_card", resourceCulture);
            }
        }
        
        public static string Device_contains_unknown_media_card_type_0 {
            get {
                return ResourceManager.GetString("Device_contains_unknown_media_card_type_0", resourceCulture);
            }
        }
        
        public static string Media_card_is_write_protected {
            get {
                return ResourceManager.GetString("Media_card_is_write_protected", resourceCulture);
            }
        }
        
        public static string Card_specific_data_0 {
            get {
                return ResourceManager.GetString("Card_specific_data_0", resourceCulture);
            }
        }
        
        public static string Media_identified_as_0 {
            get {
                return ResourceManager.GetString("Media_identified_as_0", resourceCulture);
            }
        }
        
        public static string Device_identified_as_0 {
            get {
                return ResourceManager.GetString("Device_identified_as_0", resourceCulture);
            }
        }
        
        public static string ASCII_Page_0_1 {
            get {
                return ResourceManager.GetString("ASCII_Page_0_1", resourceCulture);
            }
        }
        
        public static string Unit_Serial_Number_0 {
            get {
                return ResourceManager.GetString("Unit_Serial_Number_0", resourceCulture);
            }
        }
        
        public static string ASCII_implemented_operating_definitions_0 {
            get {
                return ResourceManager.GetString("ASCII_implemented_operating_definitions_0", resourceCulture);
            }
        }
        
        public static string Manufacturer_assigned_Serial_Number_0 {
            get {
                return ResourceManager.GetString("Manufacturer_assigned_Serial_Number_0", resourceCulture);
            }
        }
        
        public static string TapeAlert_Supported_Flags_Bitmap_0 {
            get {
                return ResourceManager.GetString("TapeAlert_Supported_Flags_Bitmap_0", resourceCulture);
            }
        }
        
        public static string Automation_Device_Serial_Number_0 {
            get {
                return ResourceManager.GetString("Automation_Device_Serial_Number_0", resourceCulture);
            }
        }
        
        public static string Data_Transfer_Device_Element_Address_0 {
            get {
                return ResourceManager.GetString("Data_Transfer_Device_Element_Address_0", resourceCulture);
            }
        }
        
        public static string Found_undecoded_SCSI_VPD_page_0 {
            get {
                return ResourceManager.GetString("Found_undecoded_SCSI_VPD_page_0", resourceCulture);
            }
        }
        
        public static string GET_CONFIGURATION_length_is_0 {
            get {
                return ResourceManager.GetString("GET_CONFIGURATION_length_is_0", resourceCulture);
            }
        }
        
        public static string GET_CONFIGURATION_current_profile_is_0 {
            get {
                return ResourceManager.GetString("GET_CONFIGURATION_current_profile_is_0", resourceCulture);
            }
        }
        
        public static string Feature_0 {
            get {
                return ResourceManager.GetString("Feature_0", resourceCulture);
            }
        }
        
        public static string Found_unknown_feature_code_0 {
            get {
                return ResourceManager.GetString("Found_unknown_feature_code_0", resourceCulture);
            }
        }
        
        public static string GET_CONFIGURATION_returned_no_feature_descriptors {
            get {
                return ResourceManager.GetString("GET_CONFIGURATION_returned_no_feature_descriptors", resourceCulture);
            }
        }
        
        public static string Drive_has_loaded_a_total_of_0_discs {
            get {
                return ResourceManager.GetString("Drive_has_loaded_a_total_of_0_discs", resourceCulture);
            }
        }
        
        public static string Drive_has_spent_0_hours_1_minutes_and_2_seconds_reading_CDs {
            get {
                return ResourceManager.GetString("Drive_has_spent_0_hours_1_minutes_and_2_seconds_reading_CDs", resourceCulture);
            }
        }
        
        public static string Drive_has_spent_0_hours_1_minutes_and_2_seconds_writing_CDs {
            get {
                return ResourceManager.GetString("Drive_has_spent_0_hours_1_minutes_and_2_seconds_writing_CDs", resourceCulture);
            }
        }
        
        public static string Drive_has_spent_0_hours_1_minutes_and_2_seconds_reading_DVDs {
            get {
                return ResourceManager.GetString("Drive_has_spent_0_hours_1_minutes_and_2_seconds_reading_DVDs", resourceCulture);
            }
        }
        
        public static string Drive_has_spent_0_hours_1_minutes_and_2_seconds_writing_DVDs {
            get {
                return ResourceManager.GetString("Drive_has_spent_0_hours_1_minutes_and_2_seconds_writing_DVDs", resourceCulture);
            }
        }
        
        public static string Drive_supports_PoweRec_is_enabled_and_recommends_0 {
            get {
                return ResourceManager.GetString("Drive_supports_PoweRec_is_enabled_and_recommends_0", resourceCulture);
            }
        }
        
        public static string Drive_supports_PoweRec_and_has_it_enabled {
            get {
                return ResourceManager.GetString("Drive_supports_PoweRec_and_has_it_enabled", resourceCulture);
            }
        }
        
        public static string Selected_PoweRec_speed_for_currently_inserted_media_is_0_1 {
            get {
                return ResourceManager.GetString("Selected_PoweRec_speed_for_currently_inserted_media_is_0_1", resourceCulture);
            }
        }
        
        public static string Maximum_PoweRec_speed_for_currently_inserted_media_is_0_1 {
            get {
                return ResourceManager.GetString("Maximum_PoweRec_speed_for_currently_inserted_media_is_0_1", resourceCulture);
            }
        }
        
        public static string Last_used_PoweRec_was_0_1 {
            get {
                return ResourceManager.GetString("Last_used_PoweRec_was_0_1", resourceCulture);
            }
        }
        
        public static string Drive_supports_PoweRec_and_has_it_disabled {
            get {
                return ResourceManager.GetString("Drive_supports_PoweRec_and_has_it_disabled", resourceCulture);
            }
        }
        
        public static string Drive_supports_Plextor_SilentMode {
            get {
                return ResourceManager.GetString("Drive_supports_Plextor_SilentMode", resourceCulture);
            }
        }
        
        public static string Plextor_SilentMode_is_enabled {
            get {
                return ResourceManager.GetString("Plextor_SilentMode_is_enabled", resourceCulture);
            }
        }
        
        public static string Access_time_is_slow {
            get {
                return ResourceManager.GetString("Access_time_is_slow", resourceCulture);
            }
        }
        
        public static string Access_time_is_fast {
            get {
                return ResourceManager.GetString("Access_time_is_fast", resourceCulture);
            }
        }
        
        public static string CD_read_speed_limited_to_0 {
            get {
                return ResourceManager.GetString("CD_read_speed_limited_to_0", resourceCulture);
            }
        }
        
        public static string DVD_read_speed_limited_to_0 {
            get {
                return ResourceManager.GetString("DVD_read_speed_limited_to_0", resourceCulture);
            }
        }
        
        public static string CD_write_speed_limited_to_0 {
            get {
                return ResourceManager.GetString("CD_write_speed_limited_to_0", resourceCulture);
            }
        }
        
        public static string Drive_supports_Plextor_GigaRec {
            get {
                return ResourceManager.GetString("Drive_supports_Plextor_GigaRec", resourceCulture);
            }
        }
        
        public static string Drive_supports_Plextor_SecuRec {
            get {
                return ResourceManager.GetString("Drive_supports_Plextor_SecuRec", resourceCulture);
            }
        }
        
        public static string Drive_supports_Plextor_SpeedRead {
            get {
                return ResourceManager.GetString("Drive_supports_Plextor_SpeedRead", resourceCulture);
            }
        }
        
        public static string Drive_supports_Plextor_SpeedRead_and_has_it_enabled {
            get {
                return ResourceManager.GetString("Drive_supports_Plextor_SpeedRead_and_has_it_enabled", resourceCulture);
            }
        }
        
        public static string Drive_supports_hiding_CDRs_and_forcing_single_session {
            get {
                return ResourceManager.GetString("Drive_supports_hiding_CDRs_and_forcing_single_session", resourceCulture);
            }
        }
        
        public static string Drive_currently_hides_CDRs {
            get {
                return ResourceManager.GetString("Drive_currently_hides_CDRs", resourceCulture);
            }
        }
        
        public static string Drive_currently_forces_single_session {
            get {
                return ResourceManager.GetString("Drive_currently_forces_single_session", resourceCulture);
            }
        }
        
        public static string Drive_supports_Plextor_VariRec {
            get {
                return ResourceManager.GetString("Drive_supports_Plextor_VariRec", resourceCulture);
            }
        }
        
        public static string Drive_supports_Plextor_VariRec_for_DVDs {
            get {
                return ResourceManager.GetString("Drive_supports_Plextor_VariRec_for_DVDs", resourceCulture);
            }
        }
        
        public static string Drive_supports_bitsetting_DVD_R_book_type {
            get {
                return ResourceManager.GetString("Drive_supports_bitsetting_DVD_R_book_type", resourceCulture);
            }
        }
        
        public static string Drive_supports_bitsetting_DVD_R_DL_book_type {
            get {
                return ResourceManager.GetString("Drive_supports_bitsetting_DVD_R_DL_book_type", resourceCulture);
            }
        }
        
        public static string Drive_supports_test_writing_DVD_Plus {
            get {
                return ResourceManager.GetString("Drive_supports_test_writing_DVD_Plus", resourceCulture);
            }
        }
        
        public static string Can_do_challenge_response_with_Xbox_discs {
            get {
                return ResourceManager.GetString("Can_do_challenge_response_with_Xbox_discs", resourceCulture);
            }
        }
        
        public static string Can_read_and_decrypt_SS_from_Xbox_discs {
            get {
                return ResourceManager.GetString("Can_read_and_decrypt_SS_from_Xbox_discs", resourceCulture);
            }
        }
        
        public static string Can_set_xtreme_unlock_state_with_Xbox_discs {
            get {
                return ResourceManager.GetString("Can_set_xtreme_unlock_state_with_Xbox_discs", resourceCulture);
            }
        }
        
        public static string Can_set_wxripper_unlock_state_with_Xbox_discs {
            get {
                return ResourceManager.GetString("Can_set_wxripper_unlock_state_with_Xbox_discs", resourceCulture);
            }
        }
        
        public static string Can_do_challenge_response_with_Xbox_360_discs {
            get {
                return ResourceManager.GetString("Can_do_challenge_response_with_Xbox_360_discs", resourceCulture);
            }
        }
        
        public static string Can_read_and_decrypt_SS_from_Xbox_360_discs {
            get {
                return ResourceManager.GetString("Can_read_and_decrypt_SS_from_Xbox_360_discs", resourceCulture);
            }
        }
        
        public static string Can_set_xtreme_unlock_state_with_Xbox_360_discs {
            get {
                return ResourceManager.GetString("Can_set_xtreme_unlock_state_with_Xbox_360_discs", resourceCulture);
            }
        }
        
        public static string Can_set_wxripper_unlock_state_with_Xbox_360_discs {
            get {
                return ResourceManager.GetString("Can_set_wxripper_unlock_state_with_Xbox_360_discs", resourceCulture);
            }
        }
        
        public static string Can_set_Kreon_locked_state {
            get {
                return ResourceManager.GetString("Can_set_Kreon_locked_state", resourceCulture);
            }
        }
        
        public static string Kreon_Can_skip_read_errors {
            get {
                return ResourceManager.GetString("Kreon_Can_skip_read_errors", resourceCulture);
            }
        }
        
        public static string Block_limits_for_device {
            get {
                return ResourceManager.GetString("Block_limits_for_device", resourceCulture);
            }
        }
        
        public static string Generating_subchannels {
            get {
                return ResourceManager.GetString("Generating_subchannels", resourceCulture);
            }
        }
        
        public static string Writing_metadata_sidecar {
            get {
                return ResourceManager.GetString("Writing_metadata_sidecar", resourceCulture);
            }
        }
        
        public static string Cannot_create_a_sidecar_from_a_directory {
            get {
                return ResourceManager.GetString("Cannot_create_a_sidecar_from_a_directory", resourceCulture);
            }
        }
        
        public static string Stack_trace_0 {
            get {
                return ResourceManager.GetString("Stack_trace_0", resourceCulture);
            }
        }
        
        public static string Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_TiB {
            get {
                return ResourceManager.GetString("Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_TiB", resourceCulture);
            }
        }
        
        public static string Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_GiB {
            get {
                return ResourceManager.GetString("Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_GiB", resourceCulture);
            }
        }
        
        public static string Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_MiB {
            get {
                return ResourceManager.GetString("Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_MiB", resourceCulture);
            }
        }
        
        public static string Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_KiB {
            get {
                return ResourceManager.GetString("Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_KiB", resourceCulture);
            }
        }
        
        public static string Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_bytes {
            get {
                return ResourceManager.GetString("Media_has_0_blocks_of_1_bytes_each_for_a_total_of_2_bytes", resourceCulture);
            }
        }
        
        public static string Xbox_DMI {
            get {
                return ResourceManager.GetString("Xbox_DMI", resourceCulture);
            }
        }
        
        public static string Xbox_360_DMI {
            get {
                return ResourceManager.GetString("Xbox_360_DMI", resourceCulture);
            }
        }
        
        public static string Lead_In_CMI {
            get {
                return ResourceManager.GetString("Lead_In_CMI", resourceCulture);
            }
        }
        
        public static string Disc_Definition_Structure {
            get {
                return ResourceManager.GetString("Disc_Definition_Structure", resourceCulture);
            }
        }
        
        public static string Medium_Status {
            get {
                return ResourceManager.GetString("Medium_Status", resourceCulture);
            }
        }
        
        public static string Spare_Area_Information {
            get {
                return ResourceManager.GetString("Spare_Area_Information", resourceCulture);
            }
        }
        
        public static string DVD_RW_Pre_Recorded_Information {
            get {
                return ResourceManager.GetString("DVD_RW_Pre_Recorded_Information", resourceCulture);
            }
        }
        
        public static string DVD_RW_PFI {
            get {
                return ResourceManager.GetString("DVD_RW_PFI", resourceCulture);
            }
        }
        
        public static string Bluray_Disc_Information {
            get {
                return ResourceManager.GetString("Bluray_Disc_Information", resourceCulture);
            }
        }
        
        public static string Bluray_Burst_Cutting_Area {
            get {
                return ResourceManager.GetString("Bluray_Burst_Cutting_Area", resourceCulture);
            }
        }
        
        public static string Bluray_Disc_Definition_Structure {
            get {
                return ResourceManager.GetString("Bluray_Disc_Definition_Structure", resourceCulture);
            }
        }
        
        public static string Bluray_Cartridge_Status {
            get {
                return ResourceManager.GetString("Bluray_Cartridge_Status", resourceCulture);
            }
        }
        
        public static string Bluray_Spare_Area_Information {
            get {
                return ResourceManager.GetString("Bluray_Spare_Area_Information", resourceCulture);
            }
        }
        
        public static string Track_Resources_Information {
            get {
                return ResourceManager.GetString("Track_Resources_Information", resourceCulture);
            }
        }
        
        public static string POW_Resources_Information {
            get {
                return ResourceManager.GetString("POW_Resources_Information", resourceCulture);
            }
        }
        
        public static string TOC {
            get {
                return ResourceManager.GetString("TOC", resourceCulture);
            }
        }
        
        public static string ATIP {
            get {
                return ResourceManager.GetString("ATIP", resourceCulture);
            }
        }
        
        public static string Standard_Disc_Information {
            get {
                return ResourceManager.GetString("Standard_Disc_Information", resourceCulture);
            }
        }
        
        public static string Session_information {
            get {
                return ResourceManager.GetString("Session_information", resourceCulture);
            }
        }
        
        public static string Raw_TOC {
            get {
                return ResourceManager.GetString("Raw_TOC", resourceCulture);
            }
        }
        
        public static string PMA {
            get {
                return ResourceManager.GetString("PMA", resourceCulture);
            }
        }
        
        public static string CD_TEXT_on_Lead_In {
            get {
                return ResourceManager.GetString("CD_TEXT_on_Lead_In", resourceCulture);
            }
        }
        
        public static string MCN {
            get {
                return ResourceManager.GetString("MCN", resourceCulture);
            }
        }
        
        public static string Tracks_0_ISRC {
            get {
                return ResourceManager.GetString("Tracks_0_ISRC", resourceCulture);
            }
        }
        
        public static string Xbox_Security_Sector {
            get {
                return ResourceManager.GetString("Xbox_Security_Sector", resourceCulture);
            }
        }
        
        public static string Video_layer_zero_size {
            get {
                return ResourceManager.GetString("Video_layer_zero_size", resourceCulture);
            }
        }
        
        public static string Video_layer_one_size {
            get {
                return ResourceManager.GetString("Video_layer_one_size", resourceCulture);
            }
        }
        
        public static string Middle_zone_size {
            get {
                return ResourceManager.GetString("Middle_zone_size", resourceCulture);
            }
        }
        
        public static string Game_data_size {
            get {
                return ResourceManager.GetString("Game_data_size", resourceCulture);
            }
        }
        
        public static string Total_size {
            get {
                return ResourceManager.GetString("Total_size", resourceCulture);
            }
        }
        
        public static string Real_layer_break {
            get {
                return ResourceManager.GetString("Real_layer_break", resourceCulture);
            }
        }
        
        public static string Media_Serial_Number {
            get {
                return ResourceManager.GetString("Media_Serial_Number", resourceCulture);
            }
        }
        
        public static string Media_identified_as {
            get {
                return ResourceManager.GetString("Media_identified_as", resourceCulture);
            }
        }
        
        public static string Track_calculations {
            get {
                return ResourceManager.GetString("Track_calculations", resourceCulture);
            }
        }
        
        public static string Offsets {
            get {
                return ResourceManager.GetString("Offsets", resourceCulture);
            }
        }
        
        public static string Drive_reading_offset_not_found_in_database {
            get {
                return ResourceManager.GetString("Drive_reading_offset_not_found_in_database", resourceCulture);
            }
        }
        
        public static string Disc_offset_cannot_be_calculated {
            get {
                return ResourceManager.GetString("Disc_offset_cannot_be_calculated", resourceCulture);
            }
        }
        
        public static string Drive_reading_offset_is_0_bytes_1_samples {
            get {
                return ResourceManager.GetString("Drive_reading_offset_is_0_bytes_1_samples", resourceCulture);
            }
        }
        
        public static string Disc_write_offset_is_unknown {
            get {
                return ResourceManager.GetString("Disc_write_offset_is_unknown", resourceCulture);
            }
        }
        
        public static string Combined_disc_and_drive_offset_are_0_bytes_1_samples {
            get {
                return ResourceManager.GetString("Combined_disc_and_drive_offset_are_0_bytes_1_samples", resourceCulture);
            }
        }
        
        public static string Combined_offset_is_0_bytes_1_samples {
            get {
                return ResourceManager.GetString("Combined_offset_is_0_bytes_1_samples", resourceCulture);
            }
        }
        
        public static string Disc_offset_is_0_bytes_1_samples {
            get {
                return ResourceManager.GetString("Disc_offset_is_0_bytes_1_samples", resourceCulture);
            }
        }
        
        public static string Took_a_total_of_0_seconds_1_processing_commands {
            get {
                return ResourceManager.GetString("Took_a_total_of_0_seconds_1_processing_commands", resourceCulture);
            }
        }
        
        public static string Average_speed_0_MiB_sec {
            get {
                return ResourceManager.GetString("Average_speed_0_MiB_sec", resourceCulture);
            }
        }
        
        public static string Fastest_speed_burst_0_MiB_sec {
            get {
                return ResourceManager.GetString("Fastest_speed_burst_0_MiB_sec", resourceCulture);
            }
        }
        
        public static string Slowest_speed_burst_0_MiB_sec {
            get {
                return ResourceManager.GetString("Slowest_speed_burst_0_MiB_sec", resourceCulture);
            }
        }
        
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        public static string _0_sectors_took_less_than_3_ms {
            get {
                return ResourceManager.GetString("_0_sectors_took_less_than_3_ms", resourceCulture);
            }
        }
        
        public static string _0_sectors_took_less_than_10_ms_but_more_than_3_ms {
            get {
                return ResourceManager.GetString("_0_sectors_took_less_than_10_ms_but_more_than_3_ms", resourceCulture);
            }
        }
        
        public static string _0_sectors_took_less_than_50_ms_but_more_than_10_ms {
            get {
                return ResourceManager.GetString("_0_sectors_took_less_than_50_ms_but_more_than_10_ms", resourceCulture);
            }
        }
        
        public static string _0_sectors_took_less_than_150_ms_but_more_than_50_ms {
            get {
                return ResourceManager.GetString("_0_sectors_took_less_than_150_ms_but_more_than_50_ms", resourceCulture);
            }
        }
        
        public static string _0_sectors_took_less_than_500_ms_but_more_than_150_ms {
            get {
                return ResourceManager.GetString("_0_sectors_took_less_than_500_ms_but_more_than_150_ms", resourceCulture);
            }
        }
        
        public static string _0_sectors_took_more_than_500_ms {
            get {
                return ResourceManager.GetString("_0_sectors_took_more_than_500_ms", resourceCulture);
            }
        }
        
        public static string _0_sectors_could_not_be_read {
            get {
                return ResourceManager.GetString("_0_sectors_could_not_be_read", resourceCulture);
            }
        }
        
        public static string Sector_0_could_not_be_read {
            get {
                return ResourceManager.GetString("Sector_0_could_not_be_read", resourceCulture);
            }
        }
        
        public static string Testing_0_seeks_longest_seek_took_1_ms_fastest_one_took_2_ms_3_ms_average {
            get {
                return ResourceManager.GetString("Testing_0_seeks_longest_seek_took_1_ms_fastest_one_took_2_ms_3_ms_average", resourceCulture);
            }
        }
        
        public static string Whole_device {
            get {
                return ResourceManager.GetString("Whole_device", resourceCulture);
            }
        }
    }
}
